window.NEWS_DATA =
{
  "generated": "2026-06-11T23:59:29.767Z",
  "hellmuth": [
    {
      "title": "Die Sober-Curious-Bühne wird zur Hauptbühne",
      "date": "2026-06-11",
      "created": "2026-06-11T23:58:34.512Z",
      "slug": "die-sober-curious-buhne-wird-zur-hauptbuhne",
      "rubrik": "hellmuth",
      "lead": "Was vor drei Jahren als Nischenpanel lief, eröffnet jetzt die Branchenkonferenz.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/bevnet-live-day-one-recap-sober-curious-founders-take-the-stage",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/die-sober-curious-buhne-wird-zur-hauptbuhne/"
    },
    {
      "title": "Nüchterne Getränke treiben den M&A-Markt",
      "date": "2026-06-11",
      "created": "2026-06-11T23:57:57.457Z",
      "slug": "nuchterne-getranke-treiben-den-m-a-markt",
      "rubrik": "hellmuth",
      "lead": "Funktionale und alkoholfreie Drinks sind zur Übernahmewährung im globalen Lebensmittelsektor geworden.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/low-and-no-drinks-fuel-food-and-beverage-dealmaking-as-asia-pacific-leads-global-ma-market/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/nuchterne-getranke-treiben-den-m-a-markt/"
    },
    {
      "title": "Baijiu zwischen Heimmarkt und Weltanspruch",
      "date": "2026-06-11",
      "created": "2026-06-11T23:57:20.736Z",
      "slug": "baijiu-zwischen-heimmarkt-und-weltanspruch",
      "rubrik": "hellmuth",
      "lead": "Die größte Spirituose der Welt ist außerhalb Chinas fast unsichtbar, und genau das wird zum Verkaufsargument der Branche.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/10/baijiu-top-brands-and-their-global-opportunity/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/baijiu-zwischen-heimmarkt-und-weltanspruch/"
    },
    {
      "title": "Impossibrew sammelt wieder ein",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:55.813Z",
      "slug": "impossibrew-sammelt-wieder-ein",
      "rubrik": "hellmuth",
      "lead": "Eine alkoholfreie Funktionsbier-Marke geht zurück an die Crowd, und das sagt mehr über die Kategorie als über die Marke.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/whats-next-for-impossibrew/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/impossibrew-sammelt-wieder-ein/"
    },
    {
      "title": "Südkorea trinkt sich nüchtern",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:40.228Z",
      "slug": "sudkorea-trinkt-sich-nuchtern",
      "rubrik": "hellmuth",
      "lead": "Der koreanische Alkoholmarkt erlebt im ersten Quartal 2026 den steilsten Rückgang seit sieben Jahren.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/alcohol-spending-in-south-korea-posts-sharpest-drop-in-seven-years/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/sudkorea-trinkt-sich-nuchtern/"
    },
    {
      "title": "Pflanzenfarben im Glas",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:19.068Z",
      "slug": "pflanzenfarben-im-glas",
      "rubrik": "hellmuth",
      "lead": "Die Getränkeindustrie tauscht synthetische Farbstoffe gegen Pflanzenextrakte, weil der Regulator und der Regalverkäufer es verlangen.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/Plant-based-natural-colors-in-soft-drinks-and-alcoholic-beverages/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/pflanzenfarben-im-glas/"
    },
    {
      "title": "Hoplark poliert die Marke",
      "date": "2026-06-09",
      "created": "2026-06-09T23:47:33.332Z",
      "slug": "hoplark-poliert-die-marke",
      "rubrik": "hellmuth",
      "lead": "Hopfen ohne Alkohol wird ein Regalproblem, kein Konzeptproblem.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/hoplarks-refresh-aims-to-boost-discovery-across-channels",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/hoplark-poliert-die-marke/"
    },
    {
      "title": "Präbiotik-Soda sucht europäischen Gaumen",
      "date": "2026-06-09",
      "created": "2026-06-09T23:46:31.565Z",
      "slug": "prabiotik-soda-sucht-europaischen-gaumen",
      "rubrik": "hellmuth",
      "lead": "Was in den USA als Funktionsgetränk durchmarschiert, stößt in Europa auf einen Geschmack, der Süße misstraut.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/prebiotic-fibre-soda-reaching-eu-market/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/prabiotik-soda-sucht-europaischen-gaumen/"
    },
    {
      "title": "Ballaststoffe als Limonade",
      "date": "2026-06-09",
      "created": "2026-06-09T23:46:06.926Z",
      "slug": "ballaststoffe-als-limonade",
      "rubrik": "hellmuth",
      "lead": "Was als Ernährungspflicht galt, wird zur Geschmacksrichtung.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/09/fibremaxxing-drives-rise-of-fibre-soda/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/ballaststoffe-als-limonade/"
    },
    {
      "title": "Eistee als Pulverstift",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:38.875Z",
      "slug": "eistee-als-pulverstift",
      "rubrik": "hellmuth",
      "lead": "Der Eistee verliert seine Flasche und damit sein Format.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/review-summer-camp-puts-craft-iced-tea-in-your-pocket",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/eistee-als-pulverstift/"
    },
    {
      "title": "RTD-Markt sortiert sich, die Marken stellen sich in die Auslage",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:24.853Z",
      "slug": "rtd-markt-sortiert-sich-die-marken-stellen-sich-in-die-auslage",
      "rubrik": "hellmuth",
      "lead": "Der US-Markt für trinkfertige Alkoholmischungen hat die Wachstumsphase hinter sich und beginnt die Konsolidierungsphase.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/inside-the-rtd-ma-frenzy-carbliss-spikedade-and-happy-dad-talk-different-strategies",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/rtd-markt-sortiert-sich-die-marken-stellen-sich-in-die-auslage/"
    },
    {
      "title": "Saint Spritz gegen die RTD-Doktrin",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:12.796Z",
      "slug": "saint-spritz-gegen-die-rtd-doktrin",
      "rubrik": "hellmuth",
      "lead": "Die Gründerregel für Ready-to-Drink-Marken lautet seit Jahren: ein Format, eine Geschmacksrichtung, eine Vertriebsschiene, erst Tempo beweisen, dann erweitern.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/why-saint-spritz-broke-the-rules",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/saint-spritz-gegen-die-rtd-doktrin/"
    },
    {
      "title": "Hydration trifft Koffein, der nächste Etikettentrick",
      "date": "2026-06-08",
      "created": "2026-06-08T08:07:24.250Z",
      "slug": "hydration-trifft-koffein-der-nachste-etikettentrick",
      "rubrik": "hellmuth",
      "lead": "Das US-Startup PHX fusioniert zwei gesättigte Kategorien zu einer dritten und nennt das Innovation.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/05/28/phx-blends-hydration-and-energy/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/hydration-trifft-koffein-der-nachste-etikettentrick/"
    },
    {
      "title": "Texas nimmt sich Celsius vor",
      "date": "2026-06-08",
      "created": "2026-06-08T08:06:52.465Z",
      "slug": "texas-nimmt-sich-celsius-vor",
      "rubrik": "hellmuth",
      "lead": "Der texanische Generalstaatsanwalt prüft, ob Celsius und die Schwestermarke Alani Nu ihre Koffeinbomben gezielt an Minderjährige vermarkten.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/05/texas-ag-investigates-celsius-alani-nu-over-caffeine-and-youth-marketing/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/texas-nimmt-sich-celsius-vor/"
    },
    {
      "title": "Apfelessig wird zur süßen Limonade",
      "date": "2026-06-08",
      "created": "2026-06-08T08:05:42.338Z",
      "slug": "apfelessig-wird-zur-sussen-limonade",
      "rubrik": "hellmuth",
      "lead": "Ein chinesischer Hersteller verschiebt Apfelessig aus dem Wellness-Regal in die Kühltheke der Erfrischungsgetränke.",
      "source_name": "FoodNavigator Asia",
      "source_url": "https://www.foodnavigator-asia.com/Article/2026/05/28/china-firm-reinvents-apple-cider-vinegar-for-rtd/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/apfelessig-wird-zur-sussen-limonade/"
    },
    {
      "title": "Joony's nennt sein Wasser mit Saftschuss eine neue Kategorie",
      "date": "2026-06-07",
      "created": "2026-06-07T21:39:02.938Z",
      "slug": "joony-s-nennt-sein-wasser-mit-saftschuss-eine-neue-kategorie",
      "rubrik": "hellmuth",
      "lead": "Ein Hersteller erklärt sein Produkt zur Gattung und hofft, dass der Handel mitspielt.",
      "source_name": "about-drinks",
      "source_url": "https://www.about-drinks.com/neue-kategorie-im-getraenkeregal-joonys-launcht-natural-soda/",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/joony-s-nennt-sein-wasser-mit-saftschuss-eine-neue-kategorie/"
    },
    {
      "title": "Knut Hansen baut eine Elf aus Gin-Cocktails",
      "date": "2026-06-07",
      "created": "2026-06-07T21:38:30.888Z",
      "slug": "knut-hansen-baut-eine-elf-aus-gin-cocktails",
      "rubrik": "hellmuth",
      "lead": "Eine Hamburger Destillerie inszeniert ihre Cocktailkarte zur Fußball-WM 2026 als Mannschaftsaufstellung.",
      "source_name": "about-drinks",
      "source_url": "https://www.about-drinks.com/knut-hansen-startelf-drinks-zur-fussball-wm-2026/",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/knut-hansen-baut-eine-elf-aus-gin-cocktails/"
    },
    {
      "title": "Gummi arabicum: Der Rohstoff, der Cola homogen hält, kommt aus einem Kriegsgebiet",
      "date": "2026-06-07",
      "created": "2026-06-07T16:17:06.492Z",
      "slug": "gummi-arabicum-der-rohstoff-der-cola-homogen-halt-kommt-aus-einem-kriegsgebiet",
      "rubrik": "hellmuth",
      "lead": "Siebzig bis achtzig Prozent des weltweit verbrauchten Gummi arabicum stammen aus dem Sudan, wo seit 2023 Krieg herrscht.",
      "source_name": "AP Food Online",
      "source_url": "https://www.apfoodonline.com/sudan-conflict-affects-gum-arabic-supply/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/gummi-arabicum-der-rohstoff-der-cola-homogen-halt-kommt-aus-einem-kriegsgebiet/"
    },
    {
      "title": "Refresher verlassen die Theke",
      "date": "2026-06-07",
      "created": "2026-06-07T16:14:57.978Z",
      "slug": "refresher-verlassen-die-theke",
      "rubrik": "hellmuth",
      "lead": "Was Starbucks und Dunkin' als koffeinierte Fruchtgetränke etabliert haben, wandert ins Supermarktregal.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/the-energy-refreshers-wave-is-moving-from-qsrs-to-cpg",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/refresher-verlassen-die-theke/"
    },
    {
      "title": "Ginseng als Alltagsware",
      "date": "2026-06-07",
      "created": "2026-06-07T16:12:32.319Z",
      "slug": "ginseng-als-alltagsware",
      "rubrik": "hellmuth",
      "lead": "Was Apotheke war, soll Snack werden.",
      "source_name": "FoodNavigator Asia",
      "source_url": "https://www.foodnavigator-asia.com/Article/2026/05/12/ginseng-democratisation-advancing-food-as-medicine/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/ginseng-als-alltagsware/"
    },
    {
      "title": "Sake-RTD im US-Massenmarkt, europäischer Cocktail bei Total Wine",
      "date": "2026-06-07",
      "created": "2026-06-07T13:57:51.230Z",
      "slug": "sake-rtd-im-us-massenmarkt-europaischer-cocktail-bei-total-wine",
      "rubrik": "hellmuth",
      "lead": "Die US-Spirituosen-Distribution sortiert sich nach dem Rückzug von RNDC neu, und die Lücken füllen Außenseiter.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/spirits-distribution-punch-club-lands-at-total-wine-oishii-signs-with-sgws",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/sake-rtd-im-us-massenmarkt-europaischer-cocktail-bei-total-wine/"
    },
    {
      "title": "Koreanischer Reiswein drängt nach Süden",
      "date": "2026-06-07",
      "created": "2026-06-07T12:55:35.667Z",
      "slug": "koreanischer-reiswein-drangt-nach-suden",
      "rubrik": "hellmuth",
      "lead": "Was in Seoul Handwerk ist, wird in Shenzhen langsam zur Karte.",
      "source_name": "SCMP Food & Drink",
      "source_url": "https://www.scmp.com/lifestyle/food-drink/article/3355137/why-korean-rice-wine-could-be-next-big-drink-hong-kong-and-mainland-china?utm_source=rss_feed",
      "preprint": false,
      "press_review": true,
      "minutes": 1,
      "href": "/news/hellmuth/koreanischer-reiswein-drangt-nach-suden/"
    }
  ],
  "science": [
    {
      "title": "Wert kommt nicht mehr an",
      "date": "2026-06-11",
      "created": "2026-06-11T23:59:29.748Z",
      "slug": "wert-kommt-nicht-mehr-an",
      "rubrik": "science",
      "lead": "Angst und Depression verzerren Entscheidungen nicht durch übertriebene Vorsicht, sondern durch eine geschwächte Übersetzung von Wert in Evidenz.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.09.731091v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wert-kommt-nicht-mehr-an/"
    },
    {
      "title": "Clozapin frisst Hirnsubstanz dort, wo Serotonin sitzt",
      "date": "2026-06-11",
      "created": "2026-06-11T23:59:10.098Z",
      "slug": "clozapin-frisst-hirnsubstanz-dort-wo-serotonin-sitzt",
      "rubrik": "science",
      "lead": "Ein Preprint kartiert, wo das letzte Mittel gegen therapieresistente Schizophrenie strukturell zugreift, und findet das Muster nicht im Dopamin-, sondern im Serotoninsystem.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.06.26354980v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/clozapin-frisst-hirnsubstanz-dort-wo-serotonin-sitzt/"
    },
    {
      "title": "Trauma, Cannabis und das Methylom des Teenagers",
      "date": "2026-06-11",
      "created": "2026-06-11T23:58:55.157Z",
      "slug": "trauma-cannabis-und-das-methylom-des-teenagers",
      "rubrik": "science",
      "lead": "Eine Preprint-Studie aus der ALSPAC-Kohorte sucht die biologische Spur früher Gewalt im Blut Siebzehnjähriger.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26355257v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/trauma-cannabis-und-das-methylom-des-teenagers/"
    },
    {
      "title": "Bewusstlosigkeit zieht das Gehirn zurück auf seine Anatomie",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:44.495Z",
      "slug": "bewusstlosigkeit-zieht-das-gehirn-zuruck-auf-seine-anatomie",
      "rubrik": "science",
      "lead": "Wenn das Bewusstsein wegbricht, folgt die funktionelle Architektur des Gehirns nicht mehr der Kognition, sondern der Hardware.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.07.730661v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/bewusstlosigkeit-zieht-das-gehirn-zuruck-auf-seine-anatomie/"
    },
    {
      "title": "Entzündung sagt Altersdepression voraus, Aspirin ändert daran nichts",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:27.352Z",
      "slug": "entzundung-sagt-altersdepression-voraus-aspirin-andert-daran-nichts",
      "rubrik": "science",
      "lead": "Ein erhöhter Entzündungsmarker im Blut älterer Menschen erhöht das Risiko späterer depressiver Symptome, doch niedrig dosiertes Aspirin bricht diesen Zusammenhang nicht.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.05.26354416v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/entzundung-sagt-altersdepression-voraus-aspirin-andert-daran-nichts/"
    },
    {
      "title": "Ein MRT, ein Jahr Vorlauf",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:12.423Z",
      "slug": "ein-mrt-ein-jahr-vorlauf",
      "rubrik": "science",
      "lead": "Adoleszente Depression und Angst lassen sich aus einem einzigen Ruhe-MRT vorhersagen, bevor Symptome sich verfestigen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.08.26355206v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/ein-mrt-ein-jahr-vorlauf/"
    },
    {
      "title": "BDNF zwischen Leber und Hirn",
      "date": "2026-06-09",
      "created": "2026-06-09T23:48:18.199Z",
      "slug": "bdnf-zwischen-leber-und-hirn",
      "rubrik": "science",
      "lead": "Alkoholabhängigkeit wird zunehmend als Stoffwechselkrankheit gelesen, die im Kopf endet.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1134/S000629792660078X",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/bdnf-zwischen-leber-und-hirn/"
    },
    {
      "title": "Was Raucher sehen, wenn sie eine Zigarette sehen",
      "date": "2026-06-09",
      "created": "2026-06-09T23:48:06.380Z",
      "slug": "was-raucher-sehen-wenn-sie-eine-zigarette-sehen",
      "rubrik": "science",
      "lead": "Bei Tabakabhängigkeit verschiebt sich nicht der Geschmack, sondern die Aufmerksamkeit.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1111/adb.70151",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/was-raucher-sehen-wenn-sie-eine-zigarette-sehen/"
    },
    {
      "title": "Pränatale Substanzexposition senkt das Geburtsgewicht",
      "date": "2026-06-09",
      "created": "2026-06-09T23:47:52.664Z",
      "slug": "pranatale-substanzexposition-senkt-das-geburtsgewicht",
      "rubrik": "science",
      "lead": "Eine US-Kohortenstudie verknüpft Drogenkonsum in der Schwangerschaft mit messbar leichteren Neugeborenen.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1542/peds.2025-074604",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/pranatale-substanzexposition-senkt-das-geburtsgewicht/"
    },
    {
      "title": "Hirnstamm in Hochauflösung",
      "date": "2026-06-08",
      "created": "2026-06-08T23:44:02.974Z",
      "slug": "hirnstamm-in-hochauflosung",
      "rubrik": "science",
      "lead": "Ein neuer Atlas kartiert die unterste Etage des Gehirns über drei Lebensalter hinweg, in einer Tiefe, die bisher fehlte.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.03.727794v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hirnstamm-in-hochauflosung/"
    },
    {
      "title": "Zwei Krankheiten, ein mitochondrialer Bruch",
      "date": "2026-06-08",
      "created": "2026-06-08T23:43:16.784Z",
      "slug": "zwei-krankheiten-ein-mitochondrialer-bruch",
      "rubrik": "science",
      "lead": "Leigh-Syndrom und Chorea Huntington haben nichts gemeinsam, außer dem Punkt, an dem die Zelle aufhört zu funktionieren.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.08.730157v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwei-krankheiten-ein-mitochondrialer-bruch/"
    },
    {
      "title": "Polygenes Risiko vererbt sich auch an die Gesunden",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:54.731Z",
      "slug": "polygenes-risiko-vererbt-sich-auch-an-die-gesunden",
      "rubrik": "science",
      "lead": "Eine kanadische Familienstudie als Preprint findet erhöhte Schizophrenie- und Bipolar-Risikoscores nicht nur bei Erkrankten, sondern auch bei deren symptomfreien erwachsenen Verwandten.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.08.26354912v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/polygenes-risiko-vererbt-sich-auch-an-die-gesunden/"
    },
    {
      "title": "Darmbakterien greifen in den Hormonhaushalt ein",
      "date": "2026-06-08",
      "created": "2026-06-08T07:38:01.534Z",
      "slug": "darmbakterien-greifen-in-den-hormonhaushalt-ein",
      "rubrik": "science",
      "lead": "Die Mikrobiota verstoffwechselt Sexualhormone und steuert darüber die Motorik des Darms.",
      "source_name": "Nature Neuroscience",
      "source_url": "https://www.nature.com/articles/s41593-026-02338-5",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/darmbakterien-greifen-in-den-hormonhaushalt-ein/"
    },
    {
      "title": "Mikroglia entscheiden über Demenz oder Resilienz",
      "date": "2026-06-08",
      "created": "2026-06-08T07:37:46.019Z",
      "slug": "mikroglia-entscheiden-uber-demenz-oder-resilienz",
      "rubrik": "science",
      "lead": "Der Kipppunkt zwischen Amyloid und Tau liegt nicht in den Plaques, sondern in den Immunzellen des Gehirns.",
      "source_name": "Nature Medicine",
      "source_url": "https://www.nature.com/articles/s41591-026-04393-8",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/mikroglia-entscheiden-uber-demenz-oder-resilienz/"
    },
    {
      "title": "Astrozyten aus der Schublade",
      "date": "2026-06-08",
      "created": "2026-06-08T07:37:17.163Z",
      "slug": "astrozyten-aus-der-schublade",
      "rubrik": "science",
      "lead": "Die Sternzellen des Gehirns lassen sich in Tagen statt Monaten herstellen, und das verschiebt den Zugriff auf das Immunsystem im Kopf.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.04.730242v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/astrozyten-aus-der-schublade/"
    },
    {
      "title": "Wie das Gehirn mehr Botenstoffe unterscheidet als Schaltkreise",
      "date": "2026-06-08",
      "created": "2026-06-08T07:36:59.920Z",
      "slug": "wie-das-gehirn-mehr-botenstoffe-unterscheidet-als-schaltkreise",
      "rubrik": "science",
      "lead": "Ein Preprint aus der Neurowissenschaft liefert eine Antwort auf ein altes Bottleneck-Problem der Hirnchemie.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.03.729927v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wie-das-gehirn-mehr-botenstoffe-unterscheidet-als-schaltkreise/"
    },
    {
      "title": "Hebbs Regel bekommt eine Ableitung",
      "date": "2026-06-08",
      "created": "2026-06-08T07:36:31.730Z",
      "slug": "hebbs-regel-bekommt-eine-ableitung",
      "rubrik": "science",
      "lead": "Im Hippocampus richtet sich die Richtung synaptischer Plastizität nach der zeitlichen Änderung der Aktivität, nicht nach ihrem Niveau.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.05.730489v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hebbs-regel-bekommt-eine-ableitung/"
    },
    {
      "title": "Darmflora und Innenwelt teilen sich Gene",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:44.453Z",
      "slug": "darmflora-und-innenwelt-teilen-sich-gene",
      "rubrik": "science",
      "lead": "Eine Mendel-Randomisierung verschiebt die Darm-Hirn-Achse von der Korrelation in Richtung gemeinsamer genetischer Architektur, allerdings nur für eine Achse der Psyche.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.05.31.26354553v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/darmflora-und-innenwelt-teilen-sich-gene/"
    },
    {
      "title": "Erstpsychose ohne Hirnalterung",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:31.747Z",
      "slug": "erstpsychose-ohne-hirnalterung",
      "rubrik": "science",
      "lead": "Ein Preprint stellt eine zentrale Annahme der biologischen Psychiatrie infrage.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.05.25.26353865v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/erstpsychose-ohne-hirnalterung/"
    },
    {
      "title": "Psychose, Stimmung, Bildung: ostasiatische Genetik bricht das europäische Muster nicht",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:15.379Z",
      "slug": "psychose-stimmung-bildung-ostasiatische-genetik-bricht-das-europaische-muster-ni",
      "rubrik": "science",
      "lead": "Ein Preprint findet in ostasiatischen Kohorten dieselbe paradoxe Überlappung zwischen Schizophrenie- und Bildungsgenen, die aus europäischen Daten bekannt ist.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.01.26354666v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/psychose-stimmung-bildung-ostasiatische-genetik-bricht-das-europaische-muster-ni/"
    },
    {
      "title": "Widrigkeit schreibt sich in die Mitochondrien der Immunzellen",
      "date": "2026-06-07",
      "created": "2026-06-07T16:20:59.327Z",
      "slug": "widrigkeit-schreibt-sich-in-die-mitochondrien-der-immunzellen",
      "rubrik": "science",
      "lead": "Ein Preprint aus der MiSBIE-Studie verknüpft Lebensbelastung, depressive Symptome und die Energieproduktion einzelner Immunzelltypen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.02.26354718v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/widrigkeit-schreibt-sich-in-die-mitochondrien-der-immunzellen/"
    },
    {
      "title": "Hirnscans sagen psychotische Erfahrungen bei Jugendlichen voraus",
      "date": "2026-06-07",
      "created": "2026-06-07T16:20:37.089Z",
      "slug": "hirnscans-sagen-psychotische-erfahrungen-bei-jugendlichen-voraus",
      "rubrik": "science",
      "lead": "Ein Preprint koppelt MRT-Daten von Neunjährigen an die Bahn, auf der psychosenahe Erlebnisse über Jahre verlaufen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.03.26354754v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/hirnscans-sagen-psychotische-erfahrungen-bei-jugendlichen-voraus/"
    },
    {
      "title": "Zwei Depressionen im Hirn",
      "date": "2026-06-07",
      "created": "2026-06-07T14:02:09.547Z",
      "slug": "zwei-depressionen-im-hirn",
      "rubrik": "science",
      "lead": "Ein Preprint findet zwei neuroanatomische Muster bei jungen Depressiven, und nur eines davon trägt eine Entzündungssignatur.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.01.26354320v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwei-depressionen-im-hirn/"
    },
    {
      "title": "Wenn das Belohnungszentrum vor Nähe warnt",
      "date": "2026-06-07",
      "created": "2026-06-07T12:52:57.683Z",
      "slug": "wenn-das-belohnungszentrum-vor-nahe-warnt",
      "rubrik": "science",
      "lead": "Im Mausmodell für Autismus codiert der Nucleus accumbens soziale Begegnung als Bedrohung statt als Belohnung.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.04.730003v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/wenn-das-belohnungszentrum-vor-nahe-warnt/"
    }
  ]
}
;
