window.NEWS_DATA =
{
  "generated": "2026-06-21T03:04:58.950Z",
  "hellmuth": [
    {
      "title": "Hautcreme als Smoothie",
      "date": "2026-06-20",
      "created": "2026-06-20T23:39:18.633Z",
      "slug": "hautcreme-als-smoothie",
      "rubrik": "hellmuth",
      "lead": "Kosmetikmarken besetzen die Saftbar als neuen Verkaufsregalplatz.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/20/oh-juice-and-cerave-develop-smoothie-that-promote-glow-from-within/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/hautcreme-als-smoothie/"
    },
    {
      "title": "BOSS Coffee dockt in Vietnam an den Energy-Drink-Markt an",
      "date": "2026-06-19",
      "created": "2026-06-19T23:18:55.841Z",
      "slug": "boss-coffee-dockt-in-vietnam-an-den-energy-drink-markt-an",
      "rubrik": "hellmuth",
      "lead": "Suntory PepsiCo verschiebt seine Kaffeemarke in das Regal, in dem Koffein nicht mehr getrunken, sondern dosiert wird.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/20/boss-coffee-expands-into-energy-drink-in-vietnam/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/boss-coffee-dockt-in-vietnam-an-den-energy-drink-markt-an/"
    },
    {
      "title": "Alkoholfreies Bier ist kein Ausstieg",
      "date": "2026-06-17",
      "created": "2026-06-17T23:54:26.360Z",
      "slug": "alkoholfreies-bier-ist-kein-ausstieg",
      "rubrik": "hellmuth",
      "lead": "94 Prozent der Konsumenten alkoholfreier Biere trinken weiterhin Alkohol.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/94-of-alcohol-free-beer-drinkers-also-consume-booze/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/alkoholfreies-bier-ist-kein-ausstieg/"
    },
    {
      "title": "Enzyme als Stillschweigevereinbarung der Getränkeindustrie",
      "date": "2026-06-17",
      "created": "2026-06-17T23:53:51.105Z",
      "slug": "enzyme-als-stillschweigevereinbarung-der-getrankeindustrie",
      "rubrik": "hellmuth",
      "lead": "Was die Branche als technologische Raffinesse feiert, ist die Industrialisierung der Abkürzung.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/16/enzyme-solutions-to-upfs-in-beer-brewing-alcohol-free-coffee/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/enzyme-als-stillschweigevereinbarung-der-getrankeindustrie/"
    },
    {
      "title": "Klares Whey frisst den Markt leer",
      "date": "2026-06-17",
      "created": "2026-06-17T23:53:34.748Z",
      "slug": "klares-whey-frisst-den-markt-leer",
      "rubrik": "hellmuth",
      "lead": "Funktionsgetränke mit Whey-Protein-Isolat treiben eine Nachfrage, der die Rohstoffbasis nicht mehr hinterherkommt.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/17/clear-whey-drives-functional-drinks-as-wpi-supply-tightens/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/klares-whey-frisst-den-markt-leer/"
    },
    {
      "title": "Kombucha lernt Kindergeburtstag",
      "date": "2026-06-16",
      "created": "2026-06-16T23:52:35.486Z",
      "slug": "kombucha-lernt-kindergeburtstag",
      "rubrik": "hellmuth",
      "lead": "Der Kombucha-Marktführer GT's koppelt sich an einen Sauerkirschsaft-Spezialisten und nennt das Ergebnis Shirley Temple.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/gts-cheribundi-team-up-for-shirley-temple-flavored-lto",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/kombucha-lernt-kindergeburtstag/"
    },
    {
      "title": "Zevia holt einen Red-Bull-Mann",
      "date": "2026-06-16",
      "created": "2026-06-16T23:52:12.355Z",
      "slug": "zevia-holt-einen-red-bull-mann",
      "rubrik": "hellmuth",
      "lead": "Die Stevia-Limonade Zevia sucht ihren Ausweg aus der Stagnation ausgerechnet bei einem Veteranen der Energydrink-Industrie.",
      "source_name": "Food Dive",
      "source_url": "https://www.fooddive.com/news/red-bull-coca-cola-celsius-executive-CEO-zevia/822996/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/zevia-holt-einen-red-bull-mann/"
    },
    {
      "title": "Nestlé USA streicht künstliche Farbstoffe",
      "date": "2026-06-16",
      "created": "2026-06-16T23:51:17.495Z",
      "slug": "nestl-usa-streicht-kunstliche-farbstoffe",
      "rubrik": "hellmuth",
      "lead": "Was als Verbraucherschutz inszeniert wird, ist Vorgriff auf eine absehbare Regulierung.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/15/nestle-usa-eliminates-artificial-colors-as-part-of-broader-reformulation-overhaul/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/nestl-usa-streicht-kunstliche-farbstoffe/"
    },
    {
      "title": "Niigata bekommt einen Newcomer, der gleich Preise sammelt",
      "date": "2026-06-16",
      "created": "2026-06-16T00:08:00.114Z",
      "slug": "niigata-bekommt-einen-newcomer-der-gleich-preise-sammelt",
      "rubrik": "hellmuth",
      "lead": "Eine der ältesten Sake-Regionen Japans öffnet sich für einen Quereinsteiger, der die Hierarchie nicht respektiert.",
      "source_name": "Japan Times Food & Drink",
      "source_url": "https://www.japantimes.co.jp/life/2026/06/14/food-drink/snow-satoyama-sake/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/niigata-bekommt-einen-newcomer-der-gleich-preise-sammelt/"
    },
    {
      "title": "Mangostan rückt in Thailands Kaffeeketten auf",
      "date": "2026-06-16",
      "created": "2026-06-16T00:06:17.388Z",
      "slug": "mangostan-ruckt-in-thailands-kaffeeketten-auf",
      "rubrik": "hellmuth",
      "lead": "Was als regionale Saisonfrucht galt, wird zur Sommerwährung der thailändischen Kaffeeketten.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/14/mangosteen-fever-punthai-and-starbucks-elevate-thailands-queen-of-fruits/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/mangostan-ruckt-in-thailands-kaffeeketten-auf/"
    },
    {
      "title": "Was die Getränkebranche unter Aufbruch versteht",
      "date": "2026-06-16",
      "created": "2026-06-16T00:05:33.795Z",
      "slug": "was-die-getrankebranche-unter-aufbruch-versteht",
      "rubrik": "hellmuth",
      "lead": "Der Mittelstand der neuen Marken steckt fest, und die Branche redet sich das schön.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/state-of-the-market-emerging-brands-at-mid-year",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/was-die-getrankebranche-unter-aufbruch-versteht/"
    },
    {
      "title": "Reis als Getränk, weil ihn keiner mehr isst",
      "date": "2026-06-14",
      "created": "2026-06-14T23:40:54.955Z",
      "slug": "reis-als-getrank-weil-ihn-keiner-mehr-isst",
      "rubrik": "hellmuth",
      "lead": "Thailands Reisindustrie sucht einen Ausweg aus dem Tellerrückgang und findet ihn im Tetrapak.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/14/clp-transforms-thai-rice-into-a-wellness-drink-with-sisod-rice-milk/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/reis-als-getrank-weil-ihn-keiner-mehr-isst/"
    },
    {
      "title": "Malaysias Modern-Soda-Markt bekommt eine Marke",
      "date": "2026-06-14",
      "created": "2026-06-14T23:40:35.210Z",
      "slug": "malaysias-modern-soda-markt-bekommt-eine-marke",
      "rubrik": "hellmuth",
      "lead": "Was in den USA längst Regal füllt, kommt nun nach Südostasien.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/14/70254/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/malaysias-modern-soda-markt-bekommt-eine-marke/"
    },
    {
      "title": "Funktionsgetränke 2026, der Geschmack als Alibi",
      "date": "2026-06-14",
      "created": "2026-06-14T23:40:10.516Z",
      "slug": "funktionsgetranke-2026-der-geschmack-als-alibi",
      "rubrik": "hellmuth",
      "lead": "Die europäische Getränkebranche stimmt sich auf ein Jahr ein, in dem Funktion und Aroma nicht mehr getrennt verhandelt werden.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/functional-beverage-trends-in-2026/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/funktionsgetranke-2026-der-geschmack-als-alibi/"
    },
    {
      "title": "Goldberg setzt auf Lavendel",
      "date": "2026-06-13",
      "created": "2026-06-13T23:40:05.160Z",
      "slug": "goldberg-setzt-auf-lavendel",
      "rubrik": "hellmuth",
      "lead": "Der Premium-Mixer-Markt sucht nach Differenzierung jenseits von Tonic und Ginger, und florale Noten sollen die Lücke schließen.",
      "source_name": "about-drinks",
      "source_url": "https://www.about-drinks.com/fuer-moderne-aperitivo-drinks-goldberg-launcht-die-limited-edition-lavender/",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/goldberg-setzt-auf-lavendel/"
    },
    {
      "title": "Fuze Tea tanzt nüchtern",
      "date": "2026-06-13",
      "created": "2026-06-13T23:36:29.913Z",
      "slug": "fuze-tea-tanzt-nuchtern",
      "rubrik": "hellmuth",
      "lead": "Coca-Colas RTD-Teemarke veranstaltet in Singapur und Malaysia alkoholfreie Tagesraves, um die Generation Z zu erreichen.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/13/fuze-tea-new-campaign-involves-tea-raves-and-pack-update-to-win-over-gen-z/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/fuze-tea-tanzt-nuchtern/"
    },
    {
      "title": "Süßstoff allein reicht der Industrie nicht mehr",
      "date": "2026-06-13",
      "created": "2026-06-13T23:35:52.814Z",
      "slug": "sussstoff-allein-reicht-der-industrie-nicht-mehr",
      "rubrik": "hellmuth",
      "lead": "Zucker raus heißt nicht Geschmack rein, und die Getränkebranche hat das verstanden.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/Low-and-no-sugar-soft-drinks-with-FMPs-for-improved-sweetness-and-mouthfeel/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/sussstoff-allein-reicht-der-industrie-nicht-mehr/"
    },
    {
      "title": "Tealive und Dutch Lady füllen den Bubble-Tea-Hype in Tetra Pak",
      "date": "2026-06-12",
      "created": "2026-06-12T23:58:35.187Z",
      "slug": "tealive-und-dutch-lady-fullen-den-bubble-tea-hype-in-tetra-pak",
      "rubrik": "hellmuth",
      "lead": "Was als Kassenschlange vor dem Tresen begann, landet jetzt im Kühlregal des Supermarkts.",
      "source_name": "Mini Me Insights",
      "source_url": "https://www.minimeinsights.com/2026/06/12/tealive-and-dutch-lady-unveil-new-rtd-dairy-milk-teas/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/tealive-und-dutch-lady-fullen-den-bubble-tea-hype-in-tetra-pak/"
    },
    {
      "title": "Ooso Sparkling Tea, dritte Sorte",
      "date": "2026-06-12",
      "created": "2026-06-12T23:56:57.534Z",
      "slug": "ooso-sparkling-tea-dritte-sorte",
      "rubrik": "hellmuth",
      "lead": "Der Premium-Tee ohne Alkohol verlässt die Nische der frommen Absicht und wird zur eigenen Kategorie.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/review-ooso-sparkling-tea-impresses-again",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/ooso-sparkling-tea-dritte-sorte/"
    },
    {
      "title": "Klarheit schlägt Story",
      "date": "2026-06-12",
      "created": "2026-06-12T23:56:42.565Z",
      "slug": "klarheit-schlagt-story",
      "rubrik": "hellmuth",
      "lead": "Auf der BevNET Live NYC 2026 einigten sich Gründer, Händler und Investoren auf eine gemeinsame Diagnose des Getränkemarktes.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/taste-radio-a-live-take-in-a-crowded-market-clarity-wins",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/klarheit-schlagt-story/"
    },
    {
      "title": "Die Sober-Curious-Bühne wird zur Hauptbühne",
      "date": "2026-06-11",
      "created": "2026-06-11T23:58:34.512Z",
      "slug": "die-sober-curious-buhne-wird-zur-hauptbuhne",
      "rubrik": "hellmuth",
      "lead": "Was vor drei Jahren als Nischenpanel lief, eröffnet jetzt die Branchenkonferenz.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/bevnet-live-day-one-recap-sober-curious-founders-take-the-stage",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/die-sober-curious-buhne-wird-zur-hauptbuhne/"
    },
    {
      "title": "Nüchterne Getränke treiben den M&A-Markt",
      "date": "2026-06-11",
      "created": "2026-06-11T23:57:57.457Z",
      "slug": "nuchterne-getranke-treiben-den-m-a-markt",
      "rubrik": "hellmuth",
      "lead": "Funktionale und alkoholfreie Drinks sind zur Übernahmewährung im globalen Lebensmittelsektor geworden.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/low-and-no-drinks-fuel-food-and-beverage-dealmaking-as-asia-pacific-leads-global-ma-market/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/nuchterne-getranke-treiben-den-m-a-markt/"
    },
    {
      "title": "Baijiu zwischen Heimmarkt und Weltanspruch",
      "date": "2026-06-11",
      "created": "2026-06-11T23:57:20.736Z",
      "slug": "baijiu-zwischen-heimmarkt-und-weltanspruch",
      "rubrik": "hellmuth",
      "lead": "Die größte Spirituose der Welt ist außerhalb Chinas fast unsichtbar, und genau das wird zum Verkaufsargument der Branche.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/10/baijiu-top-brands-and-their-global-opportunity/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/baijiu-zwischen-heimmarkt-und-weltanspruch/"
    },
    {
      "title": "Impossibrew sammelt wieder ein",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:55.813Z",
      "slug": "impossibrew-sammelt-wieder-ein",
      "rubrik": "hellmuth",
      "lead": "Eine alkoholfreie Funktionsbier-Marke geht zurück an die Crowd, und das sagt mehr über die Kategorie als über die Marke.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/whats-next-for-impossibrew/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/impossibrew-sammelt-wieder-ein/"
    },
    {
      "title": "Südkorea trinkt sich nüchtern",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:40.228Z",
      "slug": "sudkorea-trinkt-sich-nuchtern",
      "rubrik": "hellmuth",
      "lead": "Der koreanische Alkoholmarkt erlebt im ersten Quartal 2026 den steilsten Rückgang seit sieben Jahren.",
      "source_name": "The Drinks Business",
      "source_url": "https://www.thedrinksbusiness.com/2026/06/alcohol-spending-in-south-korea-posts-sharpest-drop-in-seven-years/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/sudkorea-trinkt-sich-nuchtern/"
    },
    {
      "title": "Pflanzenfarben im Glas",
      "date": "2026-06-10",
      "created": "2026-06-10T23:52:19.068Z",
      "slug": "pflanzenfarben-im-glas",
      "rubrik": "hellmuth",
      "lead": "Die Getränkeindustrie tauscht synthetische Farbstoffe gegen Pflanzenextrakte, weil der Regulator und der Regalverkäufer es verlangen.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/Plant-based-natural-colors-in-soft-drinks-and-alcoholic-beverages/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/pflanzenfarben-im-glas/"
    },
    {
      "title": "Hoplark poliert die Marke",
      "date": "2026-06-09",
      "created": "2026-06-09T23:47:33.332Z",
      "slug": "hoplark-poliert-die-marke",
      "rubrik": "hellmuth",
      "lead": "Hopfen ohne Alkohol wird ein Regalproblem, kein Konzeptproblem.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/hoplarks-refresh-aims-to-boost-discovery-across-channels",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/hoplark-poliert-die-marke/"
    },
    {
      "title": "Präbiotik-Soda sucht europäischen Gaumen",
      "date": "2026-06-09",
      "created": "2026-06-09T23:46:31.565Z",
      "slug": "prabiotik-soda-sucht-europaischen-gaumen",
      "rubrik": "hellmuth",
      "lead": "Was in den USA als Funktionsgetränk durchmarschiert, stößt in Europa auf einen Geschmack, der Süße misstraut.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/News/Promotional-features/prebiotic-fibre-soda-reaching-eu-market/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/prabiotik-soda-sucht-europaischen-gaumen/"
    },
    {
      "title": "Ballaststoffe als Limonade",
      "date": "2026-06-09",
      "created": "2026-06-09T23:46:06.926Z",
      "slug": "ballaststoffe-als-limonade",
      "rubrik": "hellmuth",
      "lead": "Was als Ernährungspflicht galt, wird zur Geschmacksrichtung.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/09/fibremaxxing-drives-rise-of-fibre-soda/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/ballaststoffe-als-limonade/"
    },
    {
      "title": "Eistee als Pulverstift",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:38.875Z",
      "slug": "eistee-als-pulverstift",
      "rubrik": "hellmuth",
      "lead": "Der Eistee verliert seine Flasche und damit sein Format.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/review-summer-camp-puts-craft-iced-tea-in-your-pocket",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/eistee-als-pulverstift/"
    },
    {
      "title": "RTD-Markt sortiert sich, die Marken stellen sich in die Auslage",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:24.853Z",
      "slug": "rtd-markt-sortiert-sich-die-marken-stellen-sich-in-die-auslage",
      "rubrik": "hellmuth",
      "lead": "Der US-Markt für trinkfertige Alkoholmischungen hat die Wachstumsphase hinter sich und beginnt die Konsolidierungsphase.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/inside-the-rtd-ma-frenzy-carbliss-spikedade-and-happy-dad-talk-different-strategies",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/rtd-markt-sortiert-sich-die-marken-stellen-sich-in-die-auslage/"
    },
    {
      "title": "Saint Spritz gegen die RTD-Doktrin",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:12.796Z",
      "slug": "saint-spritz-gegen-die-rtd-doktrin",
      "rubrik": "hellmuth",
      "lead": "Die Gründerregel für Ready-to-Drink-Marken lautet seit Jahren: ein Format, eine Geschmacksrichtung, eine Vertriebsschiene, erst Tempo beweisen, dann erweitern.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/why-saint-spritz-broke-the-rules",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/saint-spritz-gegen-die-rtd-doktrin/"
    },
    {
      "title": "Hydration trifft Koffein, der nächste Etikettentrick",
      "date": "2026-06-08",
      "created": "2026-06-08T08:07:24.250Z",
      "slug": "hydration-trifft-koffein-der-nachste-etikettentrick",
      "rubrik": "hellmuth",
      "lead": "Das US-Startup PHX fusioniert zwei gesättigte Kategorien zu einer dritten und nennt das Innovation.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/05/28/phx-blends-hydration-and-energy/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/hydration-trifft-koffein-der-nachste-etikettentrick/"
    },
    {
      "title": "Texas nimmt sich Celsius vor",
      "date": "2026-06-08",
      "created": "2026-06-08T08:06:52.465Z",
      "slug": "texas-nimmt-sich-celsius-vor",
      "rubrik": "hellmuth",
      "lead": "Der texanische Generalstaatsanwalt prüft, ob Celsius und die Schwestermarke Alani Nu ihre Koffeinbomben gezielt an Minderjährige vermarkten.",
      "source_name": "Beverage Daily",
      "source_url": "https://www.beveragedaily.com/Article/2026/06/05/texas-ag-investigates-celsius-alani-nu-over-caffeine-and-youth-marketing/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/texas-nimmt-sich-celsius-vor/"
    },
    {
      "title": "Apfelessig wird zur süßen Limonade",
      "date": "2026-06-08",
      "created": "2026-06-08T08:05:42.338Z",
      "slug": "apfelessig-wird-zur-sussen-limonade",
      "rubrik": "hellmuth",
      "lead": "Ein chinesischer Hersteller verschiebt Apfelessig aus dem Wellness-Regal in die Kühltheke der Erfrischungsgetränke.",
      "source_name": "FoodNavigator Asia",
      "source_url": "https://www.foodnavigator-asia.com/Article/2026/05/28/china-firm-reinvents-apple-cider-vinegar-for-rtd/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/apfelessig-wird-zur-sussen-limonade/"
    },
    {
      "title": "Joony's nennt sein Wasser mit Saftschuss eine neue Kategorie",
      "date": "2026-06-07",
      "created": "2026-06-07T21:39:02.938Z",
      "slug": "joony-s-nennt-sein-wasser-mit-saftschuss-eine-neue-kategorie",
      "rubrik": "hellmuth",
      "lead": "Ein Hersteller erklärt sein Produkt zur Gattung und hofft, dass der Handel mitspielt.",
      "source_name": "about-drinks",
      "source_url": "https://www.about-drinks.com/neue-kategorie-im-getraenkeregal-joonys-launcht-natural-soda/",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/joony-s-nennt-sein-wasser-mit-saftschuss-eine-neue-kategorie/"
    },
    {
      "title": "Knut Hansen baut eine Elf aus Gin-Cocktails",
      "date": "2026-06-07",
      "created": "2026-06-07T21:38:30.888Z",
      "slug": "knut-hansen-baut-eine-elf-aus-gin-cocktails",
      "rubrik": "hellmuth",
      "lead": "Eine Hamburger Destillerie inszeniert ihre Cocktailkarte zur Fußball-WM 2026 als Mannschaftsaufstellung.",
      "source_name": "about-drinks",
      "source_url": "https://www.about-drinks.com/knut-hansen-startelf-drinks-zur-fussball-wm-2026/",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/knut-hansen-baut-eine-elf-aus-gin-cocktails/"
    },
    {
      "title": "Gummi arabicum: Der Rohstoff, der Cola homogen hält, kommt aus einem Kriegsgebiet",
      "date": "2026-06-07",
      "created": "2026-06-07T16:17:06.492Z",
      "slug": "gummi-arabicum-der-rohstoff-der-cola-homogen-halt-kommt-aus-einem-kriegsgebiet",
      "rubrik": "hellmuth",
      "lead": "Siebzig bis achtzig Prozent des weltweit verbrauchten Gummi arabicum stammen aus dem Sudan, wo seit 2023 Krieg herrscht.",
      "source_name": "AP Food Online",
      "source_url": "https://www.apfoodonline.com/sudan-conflict-affects-gum-arabic-supply/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/gummi-arabicum-der-rohstoff-der-cola-homogen-halt-kommt-aus-einem-kriegsgebiet/"
    },
    {
      "title": "Refresher verlassen die Theke",
      "date": "2026-06-07",
      "created": "2026-06-07T16:14:57.978Z",
      "slug": "refresher-verlassen-die-theke",
      "rubrik": "hellmuth",
      "lead": "Was Starbucks und Dunkin' als koffeinierte Fruchtgetränke etabliert haben, wandert ins Supermarktregal.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/news/2026/the-energy-refreshers-wave-is-moving-from-qsrs-to-cpg",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/hellmuth/refresher-verlassen-die-theke/"
    },
    {
      "title": "Ginseng als Alltagsware",
      "date": "2026-06-07",
      "created": "2026-06-07T16:12:32.319Z",
      "slug": "ginseng-als-alltagsware",
      "rubrik": "hellmuth",
      "lead": "Was Apotheke war, soll Snack werden.",
      "source_name": "FoodNavigator Asia",
      "source_url": "https://www.foodnavigator-asia.com/Article/2026/05/12/ginseng-democratisation-advancing-food-as-medicine/",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/ginseng-als-alltagsware/"
    },
    {
      "title": "Sake-RTD im US-Massenmarkt, europäischer Cocktail bei Total Wine",
      "date": "2026-06-07",
      "created": "2026-06-07T13:57:51.230Z",
      "slug": "sake-rtd-im-us-massenmarkt-europaischer-cocktail-bei-total-wine",
      "rubrik": "hellmuth",
      "lead": "Die US-Spirituosen-Distribution sortiert sich nach dem Rückzug von RNDC neu, und die Lücken füllen Außenseiter.",
      "source_name": "BevNet",
      "source_url": "https://www.bevnet.com/spirits/2026/spirits-distribution-punch-club-lands-at-total-wine-oishii-signs-with-sgws",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/hellmuth/sake-rtd-im-us-massenmarkt-europaischer-cocktail-bei-total-wine/"
    },
    {
      "title": "Koreanischer Reiswein drängt nach Süden",
      "date": "2026-06-07",
      "created": "2026-06-07T12:55:35.667Z",
      "slug": "koreanischer-reiswein-drangt-nach-suden",
      "rubrik": "hellmuth",
      "lead": "Was in Seoul Handwerk ist, wird in Shenzhen langsam zur Karte.",
      "source_name": "SCMP Food & Drink",
      "source_url": "https://www.scmp.com/lifestyle/food-drink/article/3355137/why-korean-rice-wine-could-be-next-big-drink-hong-kong-and-mainland-china?utm_source=rss_feed",
      "preprint": false,
      "press_review": true,
      "minutes": 1,
      "href": "/news/hellmuth/koreanischer-reiswein-drangt-nach-suden/"
    }
  ],
  "science": [
    {
      "title": "Wenn die Glia den Strom nicht mehr abführt",
      "date": "2026-06-20",
      "created": "2026-06-20T23:42:00.350Z",
      "slug": "wenn-die-glia-den-strom-nicht-mehr-abfuhrt",
      "rubrik": "science",
      "lead": "Ein Preprint verschiebt die Schuldfrage bei Epilepsie weg vom Neuron, hin zur Stützzelle.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.15.732359v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wenn-die-glia-den-strom-nicht-mehr-abfuhrt/"
    },
    {
      "title": "Schizophrenie-Erkennung wandert in die Hochfrequenz",
      "date": "2026-06-20",
      "created": "2026-06-20T23:41:44.206Z",
      "slug": "schizophrenie-erkennung-wandert-in-die-hochfrequenz",
      "rubrik": "science",
      "lead": "Ein Preprint verschiebt die Diagnostik früher Schizophrenie von der klinischen Beobachtung in die räumlichen Randbereiche der Hirnscans.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.15.732490v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/schizophrenie-erkennung-wandert-in-die-hochfrequenz/"
    },
    {
      "title": "Huntington beginnt im Fötus",
      "date": "2026-06-20",
      "created": "2026-06-20T23:41:18.575Z",
      "slug": "huntington-beginnt-im-fotus",
      "rubrik": "science",
      "lead": "Die Krankheit, die typischerweise erst in der Lebensmitte ausbricht, hinterlässt bereits im fetalen Striatum eine eigene Signatur.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.19.733377v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/huntington-beginnt-im-fotus/"
    },
    {
      "title": "Zwangsstörung als Attraktorfalle im Rattenhirn",
      "date": "2026-06-19",
      "created": "2026-06-19T23:21:41.047Z",
      "slug": "zwangsstorung-als-attraktorfalle-im-rattenhirn",
      "rubrik": "science",
      "lead": "Ein Preprint bringt die Zwangsstörung von der Symptomebene in die Schaltungsebene und liest sie als Verlust neuronaler Beweglichkeit.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.15.730877v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwangsstorung-als-attraktorfalle-im-rattenhirn/"
    },
    {
      "title": "Die Pille greift in die Stressachse ein, regional getrennt",
      "date": "2026-06-19",
      "created": "2026-06-19T23:21:25.885Z",
      "slug": "die-pille-greift-in-die-stressachse-ein-regional-getrennt",
      "rubrik": "science",
      "lead": "Ein Mausmodell zur kombinierten oralen Kontrazeption zeigt, dass synthetisches Östrogen plus Levonorgestrel die Glucocorticoid-Rückkopplung im Gehirn umbaut.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.15.731933v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/die-pille-greift-in-die-stressachse-ein-regional-getrennt/"
    },
    {
      "title": "Hemmung als Statik des Gehirns",
      "date": "2026-06-19",
      "created": "2026-06-19T23:21:06.677Z",
      "slug": "hemmung-als-statik-des-gehirns",
      "rubrik": "science",
      "lead": "Resilienz neuronaler Schaltkreise gegen Degeneration hängt nicht an der Menge erhaltener Verbindungen, sondern an der Position der hemmenden Neuronen.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.15.732346v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hemmung-als-statik-des-gehirns/"
    },
    {
      "title": "Kindheitstrauma verkabelt das Gehirn neu",
      "date": "2026-06-19",
      "created": "2026-06-19T00:08:04.703Z",
      "slug": "kindheitstrauma-verkabelt-das-gehirn-neu",
      "rubrik": "science",
      "lead": "Frühe Gewalt verschiebt die Schaltzentrale der Persönlichkeit von der Kognition in die Limbik.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.15.26354444v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/kindheitstrauma-verkabelt-das-gehirn-neu/"
    },
    {
      "title": "Hyperbolisches Ausschleichen ruht auf weicherem Boden als gedacht",
      "date": "2026-06-19",
      "created": "2026-06-19T00:07:49.928Z",
      "slug": "hyperbolisches-ausschleichen-ruht-auf-weicherem-boden-als-gedacht",
      "rubrik": "science",
      "lead": "Ein medRxiv-Preprint rechnet vor, dass die Kurve, an der sich das schonende Absetzen von SSRI ausrichtet, nicht die entscheidende ist.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26355019v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hyperbolisches-ausschleichen-ruht-auf-weicherem-boden-als-gedacht/"
    },
    {
      "title": "Predictive Processing zerfällt unter dem Faktoranalyse-Skalpell",
      "date": "2026-06-19",
      "created": "2026-06-19T00:07:34.779Z",
      "slug": "predictive-processing-zerfallt-unter-dem-faktoranalyse-skalpell",
      "rubrik": "science",
      "lead": "Die Annahme, dass eine einzige Größe »Vorhersageverarbeitung« über Aufgaben hinweg messbar sei, hält der ersten ernsthaften Prüfung nicht stand.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26354804v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/predictive-processing-zerfallt-unter-dem-faktoranalyse-skalpell/"
    },
    {
      "title": "Im Thalamus liegt die Rückfallstelle",
      "date": "2026-06-17",
      "created": "2026-06-17T23:55:12.012Z",
      "slug": "im-thalamus-liegt-die-ruckfallstelle",
      "rubrik": "science",
      "lead": "Wenn die Expositionstherapie versagt, liegt der Fehler tiefer als bislang adressiert.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.15.26355743v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/im-thalamus-liegt-die-ruckfallstelle/"
    },
    {
      "title": "Säuglings-EEG sortiert Kinder Jahre vor der Diagnose",
      "date": "2026-06-17",
      "created": "2026-06-17T23:54:56.247Z",
      "slug": "sauglings-eeg-sortiert-kinder-jahre-vor-der-diagnose",
      "rubrik": "science",
      "lead": "Ein Preprint aus medRxiv koppelt neurophysiologische Profile aus dem siebten Lebensmonat an Temperament und psychische Auffälligkeiten mit sieben.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.15.26355713v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/sauglings-eeg-sortiert-kinder-jahre-vor-der-diagnose/"
    },
    {
      "title": "Schizophrenie und bipolare Störung im fMRT",
      "date": "2026-06-17",
      "created": "2026-06-17T23:54:43.240Z",
      "slug": "schizophrenie-und-bipolare-storung-im-fmrt",
      "rubrik": "science",
      "lead": "Ein Preprint testet, ob Ruhezustands-Hirnscans zwei Diagnosen trennen können, die klinisch ineinanderfließen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.16.26355608v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/schizophrenie-und-bipolare-storung-im-fmrt/"
    },
    {
      "title": "Genie und Psychose teilen sich die Schaltung",
      "date": "2026-06-16",
      "created": "2026-06-16T23:53:26.926Z",
      "slug": "genie-und-psychose-teilen-sich-die-schaltung",
      "rubrik": "science",
      "lead": "Ein bioRxiv-Preprint liest schizophrene Risikogene als unterversorgte Hochleistungsarchitektur.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.14.732123v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/genie-und-psychose-teilen-sich-die-schaltung/"
    },
    {
      "title": "Psychiatrische Gene schreiben sich ins Blut",
      "date": "2026-06-16",
      "created": "2026-06-16T23:53:13.113Z",
      "slug": "psychiatrische-gene-schreiben-sich-ins-blut",
      "rubrik": "science",
      "lead": "Eine genetische Last für psychiatrische Diagnosen verschiebt das Stoffwechselprofil, bevor irgendjemand Diagnose oder Medikament gesehen hat.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.06.26354927v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/psychiatrische-gene-schreiben-sich-ins-blut/"
    },
    {
      "title": "Schizophrenie verschiebt das EEG, nicht den Metabolitenspiegel",
      "date": "2026-06-16",
      "created": "2026-06-16T23:52:54.260Z",
      "slug": "schizophrenie-verschiebt-das-eeg-nicht-den-metabolitenspiegel",
      "rubrik": "science",
      "lead": "Ein Preprint aus der Schizophrenieforschung trennt zwei Messebenen, die bislang als ein Befund galten.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.12.26354984v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/schizophrenie-verschiebt-das-eeg-nicht-den-metabolitenspiegel/"
    },
    {
      "title": "Cannabis und Tabak zusammen kippen die Psychose-Statistik",
      "date": "2026-06-16",
      "created": "2026-06-16T00:08:46.283Z",
      "slug": "cannabis-und-tabak-zusammen-kippen-die-psychose-statistik",
      "rubrik": "science",
      "lead": "In klinischen Hochrisikokohorten sagt der gleichzeitige Konsum von Cannabis und Tabak den Übergang in die Psychose voraus.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1038/s44220-026-00648-y",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/cannabis-und-tabak-zusammen-kippen-die-psychose-statistik/"
    },
    {
      "title": "Gruppentherapie unterm Scanner",
      "date": "2026-06-16",
      "created": "2026-06-16T00:08:34.988Z",
      "slug": "gruppentherapie-unterm-scanner",
      "rubrik": "science",
      "lead": "Eine Studie will messen, ob junge Trinker gemeinsam nüchterner werden, indem ihre Gehirne im fMRT synchronisieren.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1371/journal.pone.0349575",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/gruppentherapie-unterm-scanner/"
    },
    {
      "title": "Adoleszentes Nikotin hinterlässt eine Microglia-Spur",
      "date": "2026-06-16",
      "created": "2026-06-16T00:08:18.569Z",
      "slug": "adoleszentes-nikotin-hinterlasst-eine-microglia-spur",
      "rubrik": "science",
      "lead": "Eine Mausstudie verortet die Depression nach jugendlicher Nikotinexposition in einer einzigen Signalkaskade.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1007/s11064-026-04811-w",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/adoleszentes-nikotin-hinterlasst-eine-microglia-spur/"
    },
    {
      "title": "Die Angstschaltung hat ein viertes Zimmer",
      "date": "2026-06-14",
      "created": "2026-06-14T23:41:48.065Z",
      "slug": "die-angstschaltung-hat-ein-viertes-zimmer",
      "rubrik": "science",
      "lead": "Ein Preprint verschiebt das Standardmodell der Furchtkonditionierung um eine Hirnregion, die im Lehrbuch bislang als Nebenschauplatz galt.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.12.731865v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/die-angstschaltung-hat-ein-viertes-zimmer/"
    },
    {
      "title": "Alzheimer hat eine zweite Schrift",
      "date": "2026-06-14",
      "created": "2026-06-14T23:41:32.032Z",
      "slug": "alzheimer-hat-eine-zweite-schrift",
      "rubrik": "science",
      "lead": "Nicht welche Proteine im Gehirn liegen, sondern wie sie chemisch beschriftet sind, korreliert mit Plaques, Tangles und kognitivem Verfall.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.13.732018v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/alzheimer-hat-eine-zweite-schrift/"
    },
    {
      "title": "Halsableitung gegen Alzheimer",
      "date": "2026-06-14",
      "created": "2026-06-14T23:41:17.657Z",
      "slug": "halsableitung-gegen-alzheimer",
      "rubrik": "science",
      "lead": "Wer Lymphe aus dem Schädel abzieht, verändert offenbar, was im Gehirn an Plaques liegen bleibt.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.12.731621v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/halsableitung-gegen-alzheimer/"
    },
    {
      "title": "Zwei Suizidalitäts-Regime statt einer Symptomliste",
      "date": "2026-06-13",
      "created": "2026-06-13T23:41:00.993Z",
      "slug": "zwei-suizidalitats-regime-statt-einer-symptomliste",
      "rubrik": "science",
      "lead": "Ein Preprint sortiert Suizidalität nicht nach Symptomen, sondern nach der Art, wie Betroffene auf Bestrafung reagieren.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26355278v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwei-suizidalitats-regime-statt-einer-symptomliste/"
    },
    {
      "title": "Wenn Hirnstimulation gegen Depression nicht wirkt, liegt es an der Verkabelung",
      "date": "2026-06-13",
      "created": "2026-06-13T23:40:45.544Z",
      "slug": "wenn-hirnstimulation-gegen-depression-nicht-wirkt-liegt-es-an-der-verkabelung",
      "rubrik": "science",
      "lead": "Tiefe Hirnstimulation im subgenualen Cingulum hilft manchen schwer Depressiven und anderen nicht, und ein Preprint legt nahe, dass die individuelle Verschaltung das entscheidet.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26355288v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wenn-hirnstimulation-gegen-depression-nicht-wirkt-liegt-es-an-der-verkabelung/"
    },
    {
      "title": "Angststörungen zeigen sich im Blutfluss der Stirnhirnrinde",
      "date": "2026-06-13",
      "created": "2026-06-13T23:40:26.990Z",
      "slug": "angststorungen-zeigen-sich-im-blutfluss-der-stirnhirnrinde",
      "rubrik": "science",
      "lead": "Ein medRxiv-Preprint kartiert Angsterkrankungen nicht über Symptome, sondern über die Durchblutung kortikaler Areale während einer Sprachaufgabe.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.11.26355427v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/angststorungen-zeigen-sich-im-blutfluss-der-stirnhirnrinde/"
    },
    {
      "title": "Legalisierung ohne Aufklärung",
      "date": "2026-06-12",
      "created": "2026-06-12T23:59:19.143Z",
      "slug": "legalisierung-ohne-aufklarung",
      "rubrik": "science",
      "lead": "Kanada hat Cannabis 2018 legalisiert, aber das Wissen der Bevölkerung über die gesundheitlichen Folgen ist seither nicht gewachsen.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1186/s42238-026-00428-6",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/legalisierung-ohne-aufklarung/"
    },
    {
      "title": "Ligustrazin gegen Alkohol-Hirn",
      "date": "2026-06-12",
      "created": "2026-06-12T23:59:08.941Z",
      "slug": "ligustrazin-gegen-alkohol-hirn",
      "rubrik": "science",
      "lead": "Ein chinesisches Pflanzenalkaloid soll die neurologischen Folgen alkoholischer Lebererkrankung über fünf Signalwege gleichzeitig dämpfen.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1002/jbt.70960",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/ligustrazin-gegen-alkohol-hirn/"
    },
    {
      "title": "Nikotin-Review räumt die Werkstatt auf",
      "date": "2026-06-12",
      "created": "2026-06-12T23:58:55.945Z",
      "slug": "nikotin-review-raumt-die-werkstatt-auf",
      "rubrik": "science",
      "lead": "Ein neues Übersichtspapier sortiert, was Nikotin im Nervensystem tatsächlich anrichtet.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1016/j.cbi.2026.112148",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/nikotin-review-raumt-die-werkstatt-auf/"
    },
    {
      "title": "Wert kommt nicht mehr an",
      "date": "2026-06-11",
      "created": "2026-06-11T23:59:29.748Z",
      "slug": "wert-kommt-nicht-mehr-an",
      "rubrik": "science",
      "lead": "Angst und Depression verzerren Entscheidungen nicht durch übertriebene Vorsicht, sondern durch eine geschwächte Übersetzung von Wert in Evidenz.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.09.731091v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wert-kommt-nicht-mehr-an/"
    },
    {
      "title": "Clozapin frisst Hirnsubstanz dort, wo Serotonin sitzt",
      "date": "2026-06-11",
      "created": "2026-06-11T23:59:10.098Z",
      "slug": "clozapin-frisst-hirnsubstanz-dort-wo-serotonin-sitzt",
      "rubrik": "science",
      "lead": "Ein Preprint kartiert, wo das letzte Mittel gegen therapieresistente Schizophrenie strukturell zugreift, und findet das Muster nicht im Dopamin-, sondern im Serotoninsystem.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.06.26354980v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/clozapin-frisst-hirnsubstanz-dort-wo-serotonin-sitzt/"
    },
    {
      "title": "Trauma, Cannabis und das Methylom des Teenagers",
      "date": "2026-06-11",
      "created": "2026-06-11T23:58:55.157Z",
      "slug": "trauma-cannabis-und-das-methylom-des-teenagers",
      "rubrik": "science",
      "lead": "Eine Preprint-Studie aus der ALSPAC-Kohorte sucht die biologische Spur früher Gewalt im Blut Siebzehnjähriger.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.09.26355257v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/trauma-cannabis-und-das-methylom-des-teenagers/"
    },
    {
      "title": "Bewusstlosigkeit zieht das Gehirn zurück auf seine Anatomie",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:44.495Z",
      "slug": "bewusstlosigkeit-zieht-das-gehirn-zuruck-auf-seine-anatomie",
      "rubrik": "science",
      "lead": "Wenn das Bewusstsein wegbricht, folgt die funktionelle Architektur des Gehirns nicht mehr der Kognition, sondern der Hardware.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.07.730661v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/bewusstlosigkeit-zieht-das-gehirn-zuruck-auf-seine-anatomie/"
    },
    {
      "title": "Entzündung sagt Altersdepression voraus, Aspirin ändert daran nichts",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:27.352Z",
      "slug": "entzundung-sagt-altersdepression-voraus-aspirin-andert-daran-nichts",
      "rubrik": "science",
      "lead": "Ein erhöhter Entzündungsmarker im Blut älterer Menschen erhöht das Risiko späterer depressiver Symptome, doch niedrig dosiertes Aspirin bricht diesen Zusammenhang nicht.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.05.26354416v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/entzundung-sagt-altersdepression-voraus-aspirin-andert-daran-nichts/"
    },
    {
      "title": "Ein MRT, ein Jahr Vorlauf",
      "date": "2026-06-10",
      "created": "2026-06-10T23:53:12.423Z",
      "slug": "ein-mrt-ein-jahr-vorlauf",
      "rubrik": "science",
      "lead": "Adoleszente Depression und Angst lassen sich aus einem einzigen Ruhe-MRT vorhersagen, bevor Symptome sich verfestigen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.08.26355206v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/ein-mrt-ein-jahr-vorlauf/"
    },
    {
      "title": "BDNF zwischen Leber und Hirn",
      "date": "2026-06-09",
      "created": "2026-06-09T23:48:18.199Z",
      "slug": "bdnf-zwischen-leber-und-hirn",
      "rubrik": "science",
      "lead": "Alkoholabhängigkeit wird zunehmend als Stoffwechselkrankheit gelesen, die im Kopf endet.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1134/S000629792660078X",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/bdnf-zwischen-leber-und-hirn/"
    },
    {
      "title": "Was Raucher sehen, wenn sie eine Zigarette sehen",
      "date": "2026-06-09",
      "created": "2026-06-09T23:48:06.380Z",
      "slug": "was-raucher-sehen-wenn-sie-eine-zigarette-sehen",
      "rubrik": "science",
      "lead": "Bei Tabakabhängigkeit verschiebt sich nicht der Geschmack, sondern die Aufmerksamkeit.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1111/adb.70151",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/was-raucher-sehen-wenn-sie-eine-zigarette-sehen/"
    },
    {
      "title": "Pränatale Substanzexposition senkt das Geburtsgewicht",
      "date": "2026-06-09",
      "created": "2026-06-09T23:47:52.664Z",
      "slug": "pranatale-substanzexposition-senkt-das-geburtsgewicht",
      "rubrik": "science",
      "lead": "Eine US-Kohortenstudie verknüpft Drogenkonsum in der Schwangerschaft mit messbar leichteren Neugeborenen.",
      "source_name": "PubMed E-Utilities",
      "source_url": "https://doi.org/10.1542/peds.2025-074604",
      "preprint": false,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/pranatale-substanzexposition-senkt-das-geburtsgewicht/"
    },
    {
      "title": "Hirnstamm in Hochauflösung",
      "date": "2026-06-08",
      "created": "2026-06-08T23:44:02.974Z",
      "slug": "hirnstamm-in-hochauflosung",
      "rubrik": "science",
      "lead": "Ein neuer Atlas kartiert die unterste Etage des Gehirns über drei Lebensalter hinweg, in einer Tiefe, die bisher fehlte.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.03.727794v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hirnstamm-in-hochauflosung/"
    },
    {
      "title": "Zwei Krankheiten, ein mitochondrialer Bruch",
      "date": "2026-06-08",
      "created": "2026-06-08T23:43:16.784Z",
      "slug": "zwei-krankheiten-ein-mitochondrialer-bruch",
      "rubrik": "science",
      "lead": "Leigh-Syndrom und Chorea Huntington haben nichts gemeinsam, außer dem Punkt, an dem die Zelle aufhört zu funktionieren.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.08.730157v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwei-krankheiten-ein-mitochondrialer-bruch/"
    },
    {
      "title": "Polygenes Risiko vererbt sich auch an die Gesunden",
      "date": "2026-06-08",
      "created": "2026-06-08T23:42:54.731Z",
      "slug": "polygenes-risiko-vererbt-sich-auch-an-die-gesunden",
      "rubrik": "science",
      "lead": "Eine kanadische Familienstudie als Preprint findet erhöhte Schizophrenie- und Bipolar-Risikoscores nicht nur bei Erkrankten, sondern auch bei deren symptomfreien erwachsenen Verwandten.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.08.26354912v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/polygenes-risiko-vererbt-sich-auch-an-die-gesunden/"
    },
    {
      "title": "Darmbakterien greifen in den Hormonhaushalt ein",
      "date": "2026-06-08",
      "created": "2026-06-08T07:38:01.534Z",
      "slug": "darmbakterien-greifen-in-den-hormonhaushalt-ein",
      "rubrik": "science",
      "lead": "Die Mikrobiota verstoffwechselt Sexualhormone und steuert darüber die Motorik des Darms.",
      "source_name": "Nature Neuroscience",
      "source_url": "https://www.nature.com/articles/s41593-026-02338-5",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/darmbakterien-greifen-in-den-hormonhaushalt-ein/"
    },
    {
      "title": "Mikroglia entscheiden über Demenz oder Resilienz",
      "date": "2026-06-08",
      "created": "2026-06-08T07:37:46.019Z",
      "slug": "mikroglia-entscheiden-uber-demenz-oder-resilienz",
      "rubrik": "science",
      "lead": "Der Kipppunkt zwischen Amyloid und Tau liegt nicht in den Plaques, sondern in den Immunzellen des Gehirns.",
      "source_name": "Nature Medicine",
      "source_url": "https://www.nature.com/articles/s41591-026-04393-8",
      "preprint": false,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/mikroglia-entscheiden-uber-demenz-oder-resilienz/"
    },
    {
      "title": "Astrozyten aus der Schublade",
      "date": "2026-06-08",
      "created": "2026-06-08T07:37:17.163Z",
      "slug": "astrozyten-aus-der-schublade",
      "rubrik": "science",
      "lead": "Die Sternzellen des Gehirns lassen sich in Tagen statt Monaten herstellen, und das verschiebt den Zugriff auf das Immunsystem im Kopf.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.04.730242v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/astrozyten-aus-der-schublade/"
    },
    {
      "title": "Wie das Gehirn mehr Botenstoffe unterscheidet als Schaltkreise",
      "date": "2026-06-08",
      "created": "2026-06-08T07:36:59.920Z",
      "slug": "wie-das-gehirn-mehr-botenstoffe-unterscheidet-als-schaltkreise",
      "rubrik": "science",
      "lead": "Ein Preprint aus der Neurowissenschaft liefert eine Antwort auf ein altes Bottleneck-Problem der Hirnchemie.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.03.729927v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/wie-das-gehirn-mehr-botenstoffe-unterscheidet-als-schaltkreise/"
    },
    {
      "title": "Hebbs Regel bekommt eine Ableitung",
      "date": "2026-06-08",
      "created": "2026-06-08T07:36:31.730Z",
      "slug": "hebbs-regel-bekommt-eine-ableitung",
      "rubrik": "science",
      "lead": "Im Hippocampus richtet sich die Richtung synaptischer Plastizität nach der zeitlichen Änderung der Aktivität, nicht nach ihrem Niveau.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.05.730489v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/hebbs-regel-bekommt-eine-ableitung/"
    },
    {
      "title": "Darmflora und Innenwelt teilen sich Gene",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:44.453Z",
      "slug": "darmflora-und-innenwelt-teilen-sich-gene",
      "rubrik": "science",
      "lead": "Eine Mendel-Randomisierung verschiebt die Darm-Hirn-Achse von der Korrelation in Richtung gemeinsamer genetischer Architektur, allerdings nur für eine Achse der Psyche.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.05.31.26354553v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/darmflora-und-innenwelt-teilen-sich-gene/"
    },
    {
      "title": "Erstpsychose ohne Hirnalterung",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:31.747Z",
      "slug": "erstpsychose-ohne-hirnalterung",
      "rubrik": "science",
      "lead": "Ein Preprint stellt eine zentrale Annahme der biologischen Psychiatrie infrage.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.05.25.26353865v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/erstpsychose-ohne-hirnalterung/"
    },
    {
      "title": "Psychose, Stimmung, Bildung: ostasiatische Genetik bricht das europäische Muster nicht",
      "date": "2026-06-07",
      "created": "2026-06-07T16:21:15.379Z",
      "slug": "psychose-stimmung-bildung-ostasiatische-genetik-bricht-das-europaische-muster-ni",
      "rubrik": "science",
      "lead": "Ein Preprint findet in ostasiatischen Kohorten dieselbe paradoxe Überlappung zwischen Schizophrenie- und Bildungsgenen, die aus europäischen Daten bekannt ist.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.01.26354666v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/psychose-stimmung-bildung-ostasiatische-genetik-bricht-das-europaische-muster-ni/"
    },
    {
      "title": "Widrigkeit schreibt sich in die Mitochondrien der Immunzellen",
      "date": "2026-06-07",
      "created": "2026-06-07T16:20:59.327Z",
      "slug": "widrigkeit-schreibt-sich-in-die-mitochondrien-der-immunzellen",
      "rubrik": "science",
      "lead": "Ein Preprint aus der MiSBIE-Studie verknüpft Lebensbelastung, depressive Symptome und die Energieproduktion einzelner Immunzelltypen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.02.26354718v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/widrigkeit-schreibt-sich-in-die-mitochondrien-der-immunzellen/"
    },
    {
      "title": "Hirnscans sagen psychotische Erfahrungen bei Jugendlichen voraus",
      "date": "2026-06-07",
      "created": "2026-06-07T16:20:37.089Z",
      "slug": "hirnscans-sagen-psychotische-erfahrungen-bei-jugendlichen-voraus",
      "rubrik": "science",
      "lead": "Ein Preprint koppelt MRT-Daten von Neunjährigen an die Bahn, auf der psychosenahe Erlebnisse über Jahre verlaufen.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.03.26354754v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/hirnscans-sagen-psychotische-erfahrungen-bei-jugendlichen-voraus/"
    },
    {
      "title": "Zwei Depressionen im Hirn",
      "date": "2026-06-07",
      "created": "2026-06-07T14:02:09.547Z",
      "slug": "zwei-depressionen-im-hirn",
      "rubrik": "science",
      "lead": "Ein Preprint findet zwei neuroanatomische Muster bei jungen Depressiven, und nur eines davon trägt eine Entzündungssignatur.",
      "source_name": "medRxiv Psychiatry",
      "source_url": "https://www.medrxiv.org/content/10.64898/2026.06.01.26354320v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 1,
      "href": "/news/science/zwei-depressionen-im-hirn/"
    },
    {
      "title": "Wenn das Belohnungszentrum vor Nähe warnt",
      "date": "2026-06-07",
      "created": "2026-06-07T12:52:57.683Z",
      "slug": "wenn-das-belohnungszentrum-vor-nahe-warnt",
      "rubrik": "science",
      "lead": "Im Mausmodell für Autismus codiert der Nucleus accumbens soziale Begegnung als Bedrohung statt als Belohnung.",
      "source_name": "bioRxiv Neuroscience",
      "source_url": "https://www.biorxiv.org/content/10.64898/2026.06.04.730003v1?rss=1",
      "preprint": true,
      "press_review": false,
      "minutes": 0,
      "href": "/news/science/wenn-das-belohnungszentrum-vor-nahe-warnt/"
    }
  ]
}
;
