// Zweite Seed-Runde: Ergänzt das retroaktive Archiv um weitere Fälle.
// Danach build() für statische Seiten.
import { writeItem, build } from './render-nova.mjs';

const cases = [
  {
    title: 'Ausschreitungen beim Eritrea-Festival in Gießen',
    date: '2023-07-08',
    ort: 'Gießen, Hessen',
    relevance: 8,
    sourceUrl: 'https://www.hessenschau.de/gesellschaft/eritrea-festival-in-giessen-2023-weitere-bewaehrungsstrafen-nach-ausschreitungen-v1,eritrea-festival-urteil-100.html',
    sourceName: 'hessenschau.de',
    lead: 'Bei einem Diaspora-Festival in Gießen eskalierte ein transnationaler politischer Konflikt zu massiver Straßengewalt gegen über tausend eingesetzte Polizeikräfte.',
    body: `Die Ausschreitungen beim Eritrea-Festival in Gießen markieren einen strukturellen Bruch in der Phänomenologie der Versammlungsgewalt: Ein geopolitischer Konflikt des Herkunftslands wird als Stellvertreterkonflikt auf deutschem Boden ausgetragen. Die Stadt hatte das Festival zunächst verboten, wurde jedoch gerichtlich zur Genehmigung gezwungen. Über tausend Polizeibeamte mussten eingesetzt werden, 26 von ihnen wurden durch Steine, Flaschen und Rauchbomben verletzt. 125 Strafanzeigen wurden erstattet. Die strukturelle Anomalie liegt in der Übertragung eines ausländischen Bürgerkriegskonflikts auf den öffentlichen Raum einer hessischen Mittelstadt — ein Szenario, für das die kommunale Gefahrenabwehr weder konzeptionell noch personell aufgestellt ist. Der Fall verdeutlicht ein Dilemma zwischen Versammlungsfreiheit und Sicherheitsarchitektur, das durch herkömmliche Auflagen nicht lösbar ist.`,
  },
  {
    title: 'Straßenschlacht bei eritreischer Veranstaltung in Stuttgart',
    date: '2023-09-16',
    ort: 'Stuttgart-Hallschlag, Baden-Württemberg',
    relevance: 8,
    sourceUrl: 'https://www.stuttgarter-zeitung.de/inhalt.prozess-nach-randale-in-stuttgart-hallschlag-drei-jahre-und-neun-monate-haft-fuer-angriff-auf-polizisten.3e634b4e-5356-492e-8cad-e9e67c323013.html',
    sourceName: 'Stuttgarter Zeitung',
    lead: 'Bei einer Veranstaltung im Stuttgarter Stadtteil Hallschlag wurden 39 Polizeibeamte durch nagelbesetzte Holzlatten, Metallstangen und Wurfgeschosse verletzt.',
    body: `Die Gewalt bei einer eritreischen Diaspora-Veranstaltung in Stuttgart-Hallschlag übertraf die Gießener Ausschreitungen zwei Monate zuvor in Intensität und Bewaffnungsgrad. Über 300 Polizeibeamte wurden eingesetzt, 39 von ihnen verletzt. Die Angreifer verwendeten nagelbesetzte Holzlatten und Metallstangen — improvisierte Waffen, die auf Vorbereitung und Organisationsgrad schließen lassen. Die Gewaltintensität erinnert an Straßenkampf, nicht an eine spontane Eskalation bei einer kulturellen Veranstaltung. Der Fall zeigt, dass die Gießener Eskalation kein Einzelereignis war, sondern ein reproduzierbares Muster: transnationaler Konflikt materialisiert sich als paramilitärisch anmutende Gewalt gegen die deutsche Polizei. Die Verletzungszahl von 39 Beamten in einem einzelnen Einsatz stellt einen extremen Ausreißer in der Polizeidienststatistik dar.`,
  },
  {
    title: 'Gewalt in der Notaufnahme des Sana-Klinikums Berlin',
    date: '2024-01-01',
    ort: 'Berlin-Lichtenberg',
    relevance: 7,
    sourceUrl: 'https://www.berlin.de/gerichte/presse/pressemitteilungen-der-ordentlichen-gerichtsbarkeit/2025/pressemitteilung.1539774.php',
    sourceName: 'Amtsgericht Tiergarten Berlin',
    lead: 'In der Notaufnahme des Sana-Klinikums schlugen zwei Angehörige einen behandelnden Arzt und eine Krankenschwester zusammen — weil ihnen die Wartezeit bei einer Bagatellverletzung zu lang war.',
    body: `In der Silvesternacht attackierten zwei Brüder einen Arzt und eine Krankenschwester in der Notaufnahme des Sana-Klinikums in Berlin-Lichtenberg. Der Arzt erlitt eine blutende Kopfwunde, die Krankenschwester wurde durch einen Faustschlag bewusstlos geschlagen und erlitt eine Gehirnerschütterung. Auslöser war die Wartezeit bei der Behandlung einer Schnittwunde an der Hand — eine Bagatellverletzung. Die strukturelle Anomalie liegt in der Eskalationsdynamik: Nicht eine lebensbedrohliche Situation oder wahrgenommene Fehlbehandlung löste die Gewalt aus, sondern die Wartezeit. Die koordinierte Attacke zweier Familienangehöriger auf Behandelnde beschreibt ein Muster der Anspruchsgewalt, das die Funktion der Notaufnahme als geschützten Behandlungsraum grundlegend infrage stellt.`,
  },
  {
    title: 'Messerangriff in Regionalbahn bei Niederlahnstein',
    date: '2024-04-08',
    ort: 'Niederlahnstein, Rheinland-Pfalz',
    relevance: 7,
    sourceUrl: 'https://56aktuell.de/grosseinsatz-in-lahnstein-messerattacke-in-der-regionalbahn-ein-schwerverletzter/',
    sourceName: '56aktuell.de',
    lead: 'In der Regionalbahn RB10 zwischen Koblenz und Lahnstein wurde ein 20-jähriger Fahrgast mit einem Messer schwer verletzt — der Bahnhof wurde gesperrt, ein Großeinsatz ausgelöst.',
    body: `In einem Regionalzug der Rheingaulinie zwischen Koblenz und Lahnstein wurde ein 20-jähriger Fahrgast durch einen Messerangriff schwer verletzt. Der Zug musste am Bahnhof Niederlahnstein nothalten, der daraufhin gesperrt wurde. Bundespolizei, Landespolizei und Kriminalpolizei rückten zum Großeinsatz an. Die strukturelle Anomalie liegt in der Wiederholung des Musters Brokstedt: ein geschlossener Regionalzug als Tatort, in dem den Fahrgästen keine Fluchtmöglichkeit bleibt. Die Häufung solcher Taten in Nahverkehrszügen verdichtet sich zu einem eigenständigen Phänomen — der Regionalzug als entgrenzter Gewaltraum.`,
  },
  {
    title: 'Dreistündige Massenschlägerei am Tollensesee',
    date: '2024-05-09',
    ort: 'Neubrandenburg, Mecklenburg-Vorpommern',
    relevance: 7,
    sourceUrl: 'https://www.nordkurier.de/regional/neubrandenburg/schlaegerei-mit-verletzten-bei-eroeffnung-von-strandbar-in-neubrandenburg-2514061',
    sourceName: 'Nordkurier',
    lead: 'Bei der Eröffnung einer Strandbar am Tollensesee eskalierte eine Schlägerei mit rund 40 Beteiligten, die sich über drei Stunden hinzog — trotz Polizeipräsenz.',
    body: `Am Himmelfahrtstag eskalierte bei der Eröffnung des Strandbads Broda am Tollensesee eine Schlägerei mit rund 40 Beteiligten. Das Außergewöhnliche war die Dauer: Die Gewalt zog sich über rund drei Stunden hin und ließ sich trotz eingesetzter 60 Polizeibeamter nicht unterbinden. Fünf Personen wurden verletzt, eine davon schwer mit Kopfverletzungen. Bei einem Verdächtigen wurde ein Messer sichergestellt. Rund 2.000 Besucher befanden sich auf dem Gelände, die Gewalt persistierte inmitten einer großen Menschenmenge. Die strukturelle Anomalie ist die Dauer: Konventionelle Schlägereien lösen sich innerhalb von Minuten nach Eintreffen der Polizei auf — hier dauerte die Gewalt trotz massiver Polizeipräsenz stundenlang an.`,
  },
  {
    title: 'Flusssäure-Anschlag an der Wohnungstür in Rosenheim',
    date: '2024-05-13',
    ort: 'Rosenheim, Bayern',
    relevance: 8,
    sourceUrl: 'https://www.polizei.bayern.de/aktuelles/pressemitteilungen/067783/index.html',
    sourceName: 'Bayerische Polizei',
    lead: 'Ein maskierter Angreifer klingelte an einer Wohnung in Rosenheim und schüttete dem Öffnenden Flusssäure ins Gesicht — ein industriell beschaffter Gefahrstoff als Angriffswaffe.',
    body: `In Rosenheim klingelte ein maskierter Angreifer an der Wohnungstür eines 31-Jährigen und schüttete ihm beim Öffnen Flusssäure ins Gesicht. Das Opfer erlitt schwerste Verätzungen und musste notärztlich versorgt werden. Ein Tatverdächtiger wurde später wegen versuchten Mordes festgenommen. Die strukturelle Anomalie liegt im Tatmittel: Flusssäure ist ein industrieller Gefahrstoff, dessen Beschaffung und Einsatz auf erhebliche Vorbereitung und Entschlossenheit schließen lässt. Der Türschwellen-Hinterhalt mit Maskierung folgt einem Muster gezielter Auftragskriminalität oder Vergeltungslogik, das in der deutschen Kriminalstatistik äußerst selten dokumentiert ist. Säureangriffe als Gewaltform sind ein Phänomen, das bisher vorwiegend aus anderen Ländern bekannt war.`,
  },
  {
    title: 'Messerattacke im Regionalzug bei Saarbrücken',
    date: '2024-06-10',
    ort: 'Saarbrücken',
    relevance: 7,
    sourceUrl: 'https://www.presseportal.de/blaulicht/pm/70138/5798275',
    sourceName: 'Presseportal / Bundespolizei Trier',
    lead: 'In einem Regionalzug kurz vor dem Saarbrücker Hauptbahnhof wurde ein 21-jähriger Fahrgast ohne jede Vorinteraktion von einem Unbekannten in den Hals gestochen.',
    body: `In der Regionalbahn RB 12579 kurz vor Erreichen des Saarbrücker Hauptbahnhofs stach ein Unbekannter einem 21-jährigen Fahrgast ohne jede vorherige Interaktion ein Messer in den Hals. Das Opfer musste operiert werden, die Verletzungen waren nicht lebensbedrohlich. Der Angreifer nutzte den Halt des Zuges als Fluchtfenster und entkam zunächst. Die strukturelle Anomalie liegt in der vollständigen Grundlosigkeit: Kein Streit, kein Blickkontakt, keine verbale Eskalation — der Angriff auf den Hals eines wildfremden Mitreisenden erfolgte aus dem Nichts. Die taktische Komponente — Zustechen im Zug, Fliehen beim Halt — deutet auf ein Kalkül hin, das den geschlossenen Raum des Nahverkehrs bewusst als Tatgelegenheit nutzt.`,
  },
  {
    title: 'Messerangriff auf Bundespolizisten am Bahnhof Lauf',
    date: '2024-06-30',
    ort: 'Lauf an der Pegnitz, Bayern',
    relevance: 7,
    sourceUrl: 'https://www.justiz.bayern.de/gerichte-und-behoerden/staatsanwaltschaft/nuernberg-fuerth/presse/2025/1.php',
    sourceName: 'Bayerisches Staatsministerium der Justiz',
    lead: 'Am Bahnhof Lauf an der Pegnitz griff ein 34-Jähriger drei Bundespolizisten mit einem Messer an — der Angreifer war trotz abgelehntem Asylantrag und polizeilicher Vorgeschichte nicht in Gewahrsam.',
    body: `Am Bahnhof Lauf an der Pegnitz attackierte ein 34-Jähriger drei Bundespolizisten mit einem Messer, nachdem er die Beamten zuvor provoziert und beleidigt hatte. Der Einsatz von Pfefferspray zeigte keine Wirkung. Ein Beamter schoss den Angreifer in Notwehr nieder, dieser verstarb. Die strukturelle Anomalie liegt im systemischen Versagen der Aufenthaltsbeendigung: Der Angreifer lebte seit 2015 in einer Asylunterkunft, sein Antrag war abgelehnt, er war polizeilich als gewalttätig bekannt. Trotz Ausreisepflicht und dokumentierter Gewaltbereitschaft existierte kein Mechanismus, der die faktische Durchsetzung des Aufenthaltsendes sicherstellte. Der Fall illustriert die Kluft zwischen rechtlicher Entscheidung und administrativer Umsetzung.`,
  },
  {
    title: 'Angriff auf DRK-Sanitäter bei Patientenversorgung in Neukölln',
    date: '2024-07-02',
    ort: 'Berlin-Neukölln',
    relevance: 7,
    sourceUrl: 'https://www.tagesspiegel.de/berlin/sanitater-musste-ins-krankenhaus-rettungskrafte-bei-einsatz-in-berlin-neukolln-angegriffen-11952593.html',
    sourceName: 'Der Tagesspiegel',
    lead: 'Ein DRK-Sanitäter wurde während der Versorgung einer bewusstlosen Patientin auf offener Straße von Umstehenden attackiert und musste selbst ins Krankenhaus.',
    body: `In der Neuköllner Fuldastraße wurde ein DRK-Sanitäter gegen Mitternacht angegriffen, während er eine am Boden liegende Frau untersuchte. Unbeteiligte Umstehende attackierten den Rettungssanitäter und verletzten ihn am Kopf und am Ohr. Der Sanitäter musste selbst im Krankenhaus behandelt werden und fiel für den Rest der Schicht aus. Die Polizei ermittelte wegen möglicher Hasskriminalität. Die strukturelle Anomalie liegt in der Transformation unbeteiligter Dritter zu Angreifern gegen medizinisches Personal bei sichtbar benigner Notfallversorgung. Rettungskräfte im Einsatz trugen erkennbare Dienstkleidung und versorgten eine hilflose Person — dennoch wurde die Hilfeleistung selbst zum Auslöser der Gewalt.`,
  },
  {
    title: 'Kaskadierende Gewalt im Dortmunder Freibad Volkspark',
    date: '2024-08-06',
    ort: 'Dortmund, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.ruhrnachrichten.de/dortmund/polizeieinsatz-im-freibad-am-bvb-stadion-notruf-wegen-schlaegerei-w919892-2001318169/',
    sourceName: 'Ruhr Nachrichten',
    lead: 'Im Dortmunder Freibad Volkspark löste eine Jugendschlägerei eine Kette von vier getrennten Gewaltakten aus, die sich über den gesamten Abend und mehrere Stadtteile erstreckte.',
    body: `Im Dortmunder Freibad Volkspark entwickelte sich an einem Sommerabend eine Kaskade aus vier verknüpften Gewaltakten: eine Schlägerei zwischen Jugendgruppen mit Pfefferspray, eine sexuelle Nötigung an einer 15-Jährigen, eine Familienauseinandersetzung bei der Festnahme des Verdächtigen und schließlich eine separate Straßenschlägerei mit 15 Beteiligten in der Brückstraße. Die strukturelle Anomalie ist die Kettenreaktion: Jeder Gewaltakt löste den nächsten aus, die Gewalt verlagerte sich über den Abend hinweg vom Freibad in den Stadtraum. Das Muster beschreibt eine Eskalationsdynamik, bei der ein erster Gewaltakt als Katalysator für eine sich selbst verstärkende Gewaltsequenz an verschiedenen Orten wirkt.`,
  },
  {
    title: 'Axt- und Hammerangriff im ICE bei Straßkirchen',
    date: '2024-08-08',
    ort: 'Straßkirchen, Niederbayern',
    relevance: 8,
    sourceUrl: 'https://www.zdfheute.de/panorama/kriminalitaet/angriff-ice-bahn-bayern-verletzte-100.html',
    sourceName: 'ZDF heute',
    lead: 'In einem voll besetzten ICE mit rund 430 Fahrgästen griff ein Reisender mehrere Menschen mit Hammer und Axt an — ein Mitreisender konnte den Angreifer überwältigen.',
    body: `Im ICE von Hamburg-Altona nach Wien attackierte ein Fahrgast zwischen Regensburg und Passau mehrere Mitreisende mit Hammer und Axt. Vier Personen wurden verletzt, bevor ein couragierter Fahrgast den Angreifer überwältigen konnte. Der Zug wurde in Straßkirchen notgestoppt. Die strukturelle Anomalie liegt in der Waffenwahl: Hammer und Axt in einem Hochgeschwindigkeitszug mit 430 eingeschlossenen Passagieren erzeugen ein Bedrohungsszenario, das die bisherige Messer-Phänomenologie im Schienenverkehr qualitativ überschreitet. Der vollständig besetzte ICE als versiegelter Raum ohne Fluchtmöglichkeit bei 200 km/h potenziert die Verwundbarkeit jedes Einzelnen. Die Unterbrechung einer internationalen Fernverkehrsverbindung durch einen einzelnen Angriff offenbart die infrastrukturelle Fragilität des Hochgeschwindigkeitsnetzes.`,
  },
  {
    title: 'Massenschlägerei mit improvisierten Waffen bei Hochzeit in Schleswig',
    date: '2024-08-12',
    ort: 'Schleswig, Schleswig-Holstein',
    relevance: 7,
    sourceUrl: 'https://www.foerde.news/blaulicht/nach-massenschlaegerei-mit-rund-60-beteiligten-personen-im-kattenhunder-weg-polizei-ermittelt.html',
    sourceName: 'foerde.news',
    lead: 'Bei einer Hochzeitsfeier in Schleswig eskalierte eine Schlägerei mit rund 60 Beteiligten, die mit Schaufeln, Fahrradschläuchen und Baseballschlägern aufeinander losgingen.',
    body: `Im Kattenhunder Weg in Schleswig eskalierte eine Hochzeitsfeier zu einer Straßenschlacht mit rund 60 Beteiligten. Die Waffen — Schaufeln, Fahrradschläuche, Baseballschläger — deuten auf eine Konfrontation, die über spontane Eskalation hinausgeht. Vier Personen mussten im Krankenhaus behandelt werden. Die Ermittlungen wurden wegen gefährlicher Körperverletzung aufgenommen. Die strukturelle Anomalie liegt in der Diversität der improvisierten Bewaffnung und der Teilnehmerzahl: Wenn ein erheblicher Teil einer Festgesellschaft zu Kombattanten wird und systematisch nach Waffen greift, beschreibt das ein Gewaltmuster, das den Rahmen einer Schlägerei verlässt und paramilitärische Züge annimmt.`,
  },
  {
    title: 'Hochzeitsfeier endet in Massenschlägerei mit Messereinsatz in Wuppertal',
    date: '2024-08-31',
    ort: 'Wuppertal, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.wuppertaler-rundschau.de/stadtteile/suedstadt/hochzeitsfeier-in-wuppertal-endet-mit-massenschlaegerei_aid-118512017',
    sourceName: 'Wuppertaler Rundschau',
    lead: 'Eine Hochzeitsfeier in Wuppertal-Elberfeld eskalierte zu einer Massenschlägerei mit rund 60 Beteiligten, bei der ein 23-Jähriger Polizisten mit einem Messer bedrohte.',
    body: `In einem Restaurant in der Elberfelder Blankstraße eskalierte eine Hochzeitsfeier zu einer Massenschlägerei mit rund 60 Beteiligten. Ein 23-Jähriger zog ein Messer und bedrohte eingesetzte Polizisten, die ihn mit einem Taser entwaffnen mussten. Fünf Polizeibeamte wurden durch Schläge, Tritte und Bisse verletzt. Frauen und Kinder flohen aus dem Restaurant, während die Gewalt im Innenraum weiter eskalierte. Die strukturelle Anomalie liegt in der direkten bewaffneten Konfrontation mit der Polizei im Kontext einer zivilen Feierlichkeit: Der Übergang von einer Festveranstaltung zu einer Szene, in der ein Taser gegen einen Messerangreifer eingesetzt werden muss, markiert eine Schwellenverletzung, die konventionelle Einsatzszenarien für Ruhestörung übersteigt.`,
  },
  {
    title: 'Säureattacke auf Nachbarn in Stralsund',
    date: '2024-09-12',
    ort: 'Stralsund, Mecklenburg-Vorpommern',
    relevance: 7,
    sourceUrl: 'https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100488522/stralsund-saeure-attacke-opfer-schwebt-in-lebensgefahr.html',
    sourceName: 't-online.de',
    lead: 'In Stralsund attackierte ein 42-Jähriger seinen 34-jährigen Nachbarn nachts mit Säure und verursachte lebensbedrohliche Verätzungen — die Staatsanwaltschaft klagte wegen versuchten Mordes mit Heimtücke an.',
    body: `Gegen zwei Uhr nachts überschüttete ein 42-Jähriger in Stralsund seinen 34-jährigen Nachbarn mit Säure. Das Opfer erlitt großflächige Verätzungen und schwebte in Lebensgefahr, es wurde per Rettungshubschrauber in eine Lübecker Spezialklinik geflogen. Die Staatsanwaltschaft erhob Anklage wegen versuchten Mordes unter dem Qualifikationsmerkmal der Heimtücke. Säure als Tatmittel bei Nachbarschaftskonflikten ist in der deutschen Kriminalphänomenologie ein extremer Ausreißer. Die Wahl eines chemischen Kampfstoffs anstelle konventioneller Gewaltmittel beschreibt eine qualitative Eskalation, die auf ein Maß an Enthemmung und Vorplanung schließen lässt, das die Kategorien eines Nachbarschaftsstreits sprengt.`,
  },
  {
    title: 'Evakuierung des Thüringen-Parks nach Messer- und Pfefferspray-Angriff',
    date: '2024-09-19',
    ort: 'Erfurt, Thüringen',
    relevance: 7,
    sourceUrl: 'https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100493332/thueringen-park-in-erfurt-einkaufszentrum-nach-angriff-evakuiert.html',
    sourceName: 't-online',
    lead: 'Nach einem Messerangriff mit gleichzeitigem Pfeffersprayeinsatz musste das gesamte Einkaufszentrum Thüringen-Park in Erfurt evakuiert und abgesperrt werden.',
    body: `Im Erfurter Einkaufszentrum Thüringen-Park eskalierte ein Streit zu einem Messerangriff, bei dem ein 27-Jähriger verletzt wurde. Gleichzeitig wurde Pfefferspray eingesetzt, das bei unbeteiligten Besuchern Atemwegs- und Augenreizungen verursachte. Das gesamte Einkaufszentrum musste evakuiert und polizeilich abgesperrt werden. Die strukturelle Anomalie liegt im kombinierten Waffeneinsatz in einem geschlossenen Gebäude: Das Pfefferspray erzeugte einen Flächeneffekt, der weit über das eigentliche Tatgeschehen hinausreichte und aus einer gezielten Auseinandersetzung ein Massenstörungsereignis machte. Die Evakuierung eines kompletten Einkaufszentrums wegen einer Einzeltat beschreibt den kaskadierenden Effekt von Gewalt in hochfrequentierten Innenräumen.`,
  },
  {
    title: 'Gruppenangriff auf Klinikpersonal nach Todesfall in Essener Notaufnahme',
    date: '2024-09-20',
    ort: 'Essen-Huttrop, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://www.zdf.de/nachrichten/panorama/kriminalitaet/essen-krankenhaus-besucher-mitarbeiter-angriff-verletzte-100.html',
    sourceName: 'ZDF Nachrichten',
    lead: 'Nach dem Tod einer 87-jährigen Patientin während der Reanimation stürmten mehrere Angehörige den Behandlungsraum des Elisabeth-Krankenhauses und verletzten sechs Mitarbeiter.',
    body: `Im Elisabeth-Krankenhaus in Essen-Huttrop stürmten mehrere Angehörige einer verstorbenen 87-jährigen Patientin den Behandlungsraum, nachdem Reanimationsmaßnahmen erfolglos geblieben waren. Sechs Krankenhausmitarbeiter wurden verletzt, eine 23-jährige Mitarbeiterin schwer. Die strukturelle Anomalie liegt im Auslöser: Nicht wahrgenommene Fehlbehandlung, sondern der Tod selbst — das nicht akzeptierte Ergebnis einer medizinischen Maßnahme — löste die Gewalt aus. Die koordinierte Erstürmung eines Behandlungsraums durch eine Personengruppe sprengt den Rahmen individueller Aggressionsakte und erzwang die Nachrüstung des Krankenhauses mit flughafenähnlichen Zugangskontrollen und permanentem Sicherheitspersonal. Wenn Notaufnahmen sich baulich gegen ihre Besucher sichern müssen, ist eine systemische Schwelle überschritten.`,
  },
  {
    title: 'Messerangriff auf Jugendlichen an Bushaltestelle in Erfurt',
    date: '2025-02-02',
    ort: 'Erfurt-Vieselbach, Thüringen',
    relevance: 7,
    sourceUrl: 'https://www.nius.de/kriminalitaet/news/erfurt-messerattacke-14-jaehriger-16-jaehriger-not-operation-bushaltestelle-vieselbach/1dba3f91-fa84-4af0-a23a-c00e098a892b',
    sourceName: 'NIUS',
    lead: 'An einer Bushaltestelle in Erfurt stach ein 16-Jähriger auf einen 14-Jährigen ein — das Opfer musste mit dem Rettungshubschrauber abtransportiert werden, der Täter wurde freigelassen.',
    body: `An einer Bushaltestelle in der Weimarstraße im Erfurter Stadtteil Vieselbach stach ein 16-Jähriger an einem Sonntagabend auf einen 14-Jährigen ein. Das Opfer erlitt so schwere Verletzungen, dass es notoperiert und mit dem Rettungshubschrauber transportiert werden musste. Der mutmaßliche Täter wurde festgenommen, jedoch anschließend wieder freigelassen. Die strukturelle Anomalie ist zweifach: Das extreme Jugendalter beider Beteiligter — die Grenze zur Schwerstkriminalität verschiebt sich in die Kindheit — und die Freilassung des Täters trotz der Schwere der Verletzungen. Wenn ein Jugendlicher einen Gleichaltrigen an einer Bushaltestelle beinahe tötet und wenig später wieder auf freiem Fuß ist, offenbart das eine Lücke in der jugendstrafrechtlichen Gefahrenabwehr.`,
  },
  {
    title: 'Messerangriff auf DB-Mitarbeiter am Dortmunder Hauptbahnhof',
    date: '2025-03-06',
    ort: 'Dortmund, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://dortmund.polizei.nrw/presse/22-jaehriger-sticht-mit-einem-messer-auf-einen-mitarbeiter-im-hauptbahnhof-dortmund-ein-polizei-nimmt-tatverdaechtigen-fest',
    sourceName: 'Polizei Dortmund',
    lead: 'Ein 22-Jähriger kehrte eine Stunde nach einem Streit um ein Busticket an den Fahrkartenschalter des Dortmunder Hauptbahnhofs zurück und stach einem 56-jährigen DB-Mitarbeiter lebensgefährlich in den Körper.',
    body: `Am Dortmunder Hauptbahnhof stach ein 22-Jähriger einem 56-jährigen Mitarbeiter der Deutschen Bahn am Fahrkartenschalter lebensgefährlich mit einem Messer in den Körper. Der Attacke war ein Streit über die Verlängerung eines Bustickets vorausgegangen — der Angreifer hatte den Schalter verlassen und war eine Stunde später gezielt zurückgekehrt. Die zeitliche Verzögerung zwischen Konflikt und Tat schließt Affekt aus und belegt Vorsatz. Die strukturelle Anomalie liegt in der Rückkehr: Nicht die unmittelbare Eskalation, sondern die geplante Vergeltung gegen einen Dienstleister für eine Bagatellablehnung markiert einen Schwellenbruch. Wenn ein Fahrkartenverkäufer an seinem Arbeitsplatz um sein Leben fürchten muss, weil er ein Ticket nicht verlängert hat, ist die Gewaltbereitschaft an einem kategorialen Wendepunkt angelangt.`,
  },
  {
    title: 'Messerangriff auf Lebensmittelkontrolleure in Gelsenkirchen',
    date: '2025-03-12',
    ort: 'Gelsenkirchen-Horst, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://gelsenkirchen.polizei.nrw/presse/gemeinsame-pressemitteilung-der-staatsanwaltschaft-essen-und-der-polizei-gelsenkirchen-versuchtes-toetungsdelikt-bei-lebensmittelkontrolle-in-horst',
    sourceName: 'Polizei Gelsenkirchen / Staatsanwaltschaft Essen',
    lead: 'Bei einer routinemäßigen Lebensmittelkontrolle in einer Eisdiele stach der Betreiber mit einem Messer auf zwei städtische Kontrolleure ein — einer erlitt lebensgefährliche Verletzungen.',
    body: `Zwei städtische Lebensmittelkontrolleure wurden bei einer Routineinspektion in einer Eisdiele in der Gelsenkirchener Grabbestraße mit einem Messer attackiert. Der 37-jährige Kontrolleur erlitt schwere, der 32-jährige leichtere Verletzungen. Die Staatsanwaltschaft klagte wegen versuchten Totschlags an. Die strukturelle Anomalie liegt in der Opfergruppe: Keine Polizisten, keine Rettungskräfte, sondern Verwaltungsangestellte bei einer alltäglichen behördlichen Routinehandlung wurden Opfer einer potenziell tödlichen Messerattacke. Wenn eine Lebensmittelhygienekontrolle zum Anlass einer versuchten Tötung wird, ist die Grenze zwischen administrativer Reibung und Gewalt gegen Staatsdiener aufgelöst. Der Fall erzwingt die Frage, welche kommunalen Bediensteten künftig nur noch unter Polizeischutz arbeiten können.`,
  },
  {
    title: 'Messerattacke in Berliner Straßenbahn am Alexanderplatz',
    date: '2025-04-10',
    ort: 'Berlin-Mitte',
    relevance: 7,
    sourceUrl: 'https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1550558.php',
    sourceName: 'Polizei Berlin',
    lead: 'In der Straßenbahnlinie M2 stieg ein Mann zu, begann zu schreien und stach beim Halt am Alexanderplatz auf einen 57-jährigen Fahrgast ein, der gerade aussteigen wollte.',
    body: `In der Berliner Straßenbahnlinie M2 stieg ein Unbekannter an der Haltestelle Mollstraße zu und begann lautstark zu schreien. Als ein 57-jähriger Fahrgast am Alexanderplatz aussteigen wollte, stach der Angreifer mit einem Messer auf ihn ein. Das Opfer erlitt Schnittverletzungen am Arm, die es sich bei der Abwehr zugezogen hatte. Der Täter flüchtete in die Menschenmenge. Die strukturelle Anomalie liegt im Tatmuster: Der Angreifer stieg an einer vorherigen Haltestelle zu, wartete ab und schlug beim Ausstiegsversuch des Opfers zu — ein Verweilzeitenmuster innerhalb des Transitfahrzeugs, das auf taktisches Verhalten im öffentlichen Nahverkehr hindeutet. Der Moment des Aussteigens — die Transition zwischen geschlossenem Raum und Plattform — wird zum Angriffsfenster.`,
  },
  {
    title: 'Tödliche Messerattacke an U-Bahnhof Sophie-Charlotte-Platz',
    date: '2025-04-12',
    ort: 'Berlin-Charlottenburg',
    relevance: 8,
    sourceUrl: 'https://www.tagesspiegel.de/berlin/todlicher-messerangriff-in-berliner-u-bahn-shadi-s-hatte-langst-in-haft-sitzen-mussen-13549201.html',
    sourceName: 'Der Tagesspiegel',
    lead: 'Ein 43-Jähriger erstach einen 29-Jährigen am U-Bahnhof Sophie-Charlotte-Platz — obwohl gegen ihn seit Monaten ein Haftbefehl vorlag, den keine Behörde vollstreckt hatte.',
    body: `Am U-Bahnhof Sophie-Charlotte-Platz erstach ein 43-Jähriger einen 29-Jährigen. Der Täter hatte mehrere Vorverurteilungen wegen Körperverletzung, Bedrohung und Widerstands gegen Vollstreckungsbeamte. 2022 hatte er seine Schwester mit einem Messer attackiert und einen Polizisten angegriffen, dafür eine Bewährungsstrafe erhalten. Im Dezember 2024 beantragte die Chemnitzer Staatsanwaltschaft den Bewährungswiderruf und einen Haftbefehl — der Antrag erreichte das Berliner Landgericht jedoch erst am 18. März 2025, weniger als vier Wochen vor der tödlichen Tat. Seit Mai 2024 lag eine polizeiliche Gefährdungseinschätzung mit „konkreten Anhaltspunkten für eine akute Fremdgefährdung" vor. Der Täter hätte zum Tatzeitpunkt in Haft sein müssen. Der Fall offenbart ein systemisches Versagen über Ländergrenzen hinweg: Die Bearbeitungsdauer eines Haftbefehls zwischen zwei Bundesländern kostete ein Menschenleben.`,
  },
  {
    title: 'Messerangriff auf Supermarkt-Kundin nach Hausverbot in Rochlitz',
    date: '2025-04-17',
    ort: 'Rochlitz, Sachsen',
    relevance: 7,
    sourceUrl: 'https://www.tagesspiegel.de/gesellschaft/panorama/vorfall-im-sachsischen-rochlitz-zwei-menschen-bei-messerangriff-vor-supermarkt-schwer-verletzt-13561288.html',
    sourceName: 'Tagesspiegel',
    lead: 'Nach einem Hausverbot kehrte ein 23-Jähriger zum Supermarkt zurück und stach auf eine unbeteiligte Kundin ein — ein 18-jähriger Mitarbeiter, der eingriff, wurde lebensgefährlich verletzt.',
    body: `In Rochlitz kehrte ein 23-Jähriger, dem zuvor ein Hausverbot im Supermarkt erteilt worden war, am Abend zurück und stach auf eine 59-jährige Kundin ein, die gerade den Laden verließ. Ein 18-jähriger Mitarbeiter eines Nachbargeschäfts eilte zur Hilfe und wurde selbst lebensgefährlich mit dem Messer verletzt. Die strukturelle Anomalie liegt in der Zielverschiebung: Nicht das Personal, das das Verbot ausgesprochen hatte, wurde zum Opfer, sondern eine zufällige Kundin — ein Muster verschobener Aggression, bei dem der Frustrations-Auslöser und das Gewalt-Ziel auseinanderfallen. Die Inversion der Helfer-Dynamik — der Rettende wird zum schwerer Verletzten — beschreibt einen wiederkehrenden Mechanismus: Zivilcourage wird zur Selbstgefährdung.`,
  },
  {
    title: 'Femizid trotz Fußfessel in Frankfurt-Bonames',
    date: '2025-07-02',
    ort: 'Frankfurt-Bonames, Hessen',
    relevance: 8,
    sourceUrl: 'https://www.hessenschau.de/panorama/messerangriff-in-frankfurt-mutmasslicher-moerder-trug-bis-vor-kurzem-fussfessel-v2,mann-stirbt-frankfurt-mordverdacht-100.html',
    sourceName: 'hessenschau.de',
    lead: 'Ein 36-Jähriger tötete einen Mann und griff seine Ehefrau mit einem Messer an — neun Tage, nachdem seine GPS-Fußfessel nach Ablauf der gesetzlichen Höchstfrist abgenommen worden war.',
    body: `In Frankfurt-Bonames erstach ein 36-Jähriger einen 46-jährigen Mann und verletzte seine getrennt lebende Ehefrau mit einem Messer. Die Frau hatte bereits im Februar 2025 Anzeige wegen häuslicher Gewalt und Vergewaltigung erstattet. Nach der Verletzung eines Kontaktverbots wurde der Täter kurzzeitig inhaftiert und anschließend mit einer GPS-Fußfessel nach dem „spanischen Modell" überwacht. Die elektronische Aufenthaltsüberwachung war jedoch gesetzlich auf vier Monate befristet und lief am 23. Juni 2025 aus — neun Tage vor der Tat. Da der Überwachte sich während der Tragezeit an die Auflagen gehalten hatte, war eine Verlängerung rechtlich nicht möglich. Der hessische Justizminister forderte daraufhin eine Reform des Gewaltschutzgesetzes. Die strukturelle Anomalie liegt in der Systemlogik selbst: Das Schutzinstrument Fußfessel wird durch sein eigenes Verfallsdatum unwirksam — die Gefährdung richtet sich nicht nach Fristen.`,
  },
  {
    title: 'Messerangriff auf Zivilcourage-Helfer in Dresdner Straßenbahn',
    date: '2025-08-24',
    ort: 'Dresden, Sachsen',
    relevance: 7,
    sourceUrl: 'https://www.zdfheute.de/panorama/messerattacke-dresden-strassenbahn-opfer-jonathan-rudat-spricht-100.html',
    sourceName: 'ZDF heute',
    lead: 'Ein 20-jähriger Fahrgast, der in einer Dresdner Straßenbahn belästigte Frauen verteidigte, wurde von den Belästigern mit einem Messer ins Gesicht gestochen.',
    body: `In der Dresdner Straßenbahnlinie 7 wurde ein 20-jähriger Fahrgast mit einem Messer ins Gesicht gestochen, nachdem er gegen die Belästigung weiblicher Mitfahrerinnen interveniert hatte. Ein Verdächtiger wurde festgenommen, am selben Tag wieder freigelassen und erst nach erneuter Videoauswertung erneut verhaftet. Die strukturelle Anomalie liegt in der doppelten Bestrafung von Zivilcourage: Der Intervenierende wurde zum schwerer Verletzten, und das Justizsystem entließ den Tatverdächtigen zunächst trotz eines Messerangriffs mit Gesichtsverletzung. Der Festnahme-Freilassung-Wiederfestnahme-Zyklus und die anfängliche Fehlidentifikation des Täters verdeutlichen die ermittlungstechnischen Komplikationen bei Gewalttaten im engen Raum einer Straßenbahn. Der Abschreckungseffekt auf ziviles Eingreifen im Nahverkehr ist die unsichtbare Folgetat.`,
  },
  {
    title: 'Fahrzeug-Angriff auf Kirmes-Besucher in Niederdorla',
    date: '2025-09-21',
    ort: 'Niederdorla, Thüringen',
    relevance: 7,
    sourceUrl: 'https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100923892/niederdorla-in-thueringen-mann-faehrt-mit-pick-up-truck-in-kirmes-verletzte.html',
    sourceName: 't-online.de',
    lead: 'Ein 41-Jähriger fuhr mit einem Pick-up-Truck in eine Menschenmenge auf einer Kirmes in Niederdorla und verletzte fünf Besucher — zuvor war er bereits wegen Raserei aufgefallen.',
    body: `In Niederdorla steuerte ein 41-Jähriger einen Pick-up-Truck in eine Besuchergruppe auf der örtlichen Kirmes und verletzte fünf Menschen. Zuvor war er bereits durch rücksichtsloses Fahren durch den Ort aufgefallen und bei der Polizei gemeldet worden. Als Beamte ihn stoppen wollten, flüchtete er mit dem Fahrzeug und steuerte anschließend gezielt auf das Festgelände zu. Die Besucher konnten dem Fahrzeug teilweise ausweichen. Die strukturelle Anomalie liegt in der Übertragung des terroristischen Fahrzeugangriff-Musters auf ein dörfliches Volksfest: Ein Szenario, das mit dem Terrorismus urbaner Weihnachtsmärkte assoziiert wird, materialisiert sich auf einer thüringischen Dorf-Kirmes. Die Sequenz Polizeiflucht — gezieltes Ansteuern einer Menschenmenge zeigt, dass der Fahrer das Festgelände bewusst als Ziel wählte.`,
  },
  {
    title: 'Silvester-Eskalation gegen Einsatzkräfte in mehreren Großstädten',
    date: '2025-12-31',
    ort: 'Frankfurt, Berlin, Duisburg, Leipzig',
    relevance: 8,
    sourceUrl: 'https://frankfurt.t-online.de/region/frankfurt-am-main/id_101064410/frankfurt-sanitaeter-in-silvesternacht-angegriffen-und-verletzt.html',
    sourceName: 't-online / Tagesspiegel / komba NRW',
    lead: 'In der Silvesternacht 2025/26 erreichten die Angriffe auf Rettungskräfte eine neue Qualität: In Frankfurt wurde ein Rettungswagen beschossen und instrumentalisiert, in Berlin ersetzte ein Wasserwerfer die handlungsunfähige Feuerwehr.',
    body: `Die Silvesternacht 2025/26 markierte eine qualitative Eskalationsstufe bei Angriffen auf Einsatzkräfte. In Frankfurt wurde ein Rettungswagen auf einer Einsatzfahrt von einer großen Gruppe attackiert, mit Pyrotechnik beschossen und blockiert; ein Sanitäter wurde getreten. Anschließend riss dieselbe Gruppe die Behandlungstür auf und deponierte eine bewusstlose Frau im Fahrzeug — die simultane Attacke auf und Instrumentalisierung desselben Rettungsmittels. In einem zweiten Frankfurter Vorfall blockierte eine Straßensperre einen Rettungswagen auf dem Weg zur Klinik; die Polizei musste einen Räumpanzer einsetzen. In Berlin-Moabit wuchsen Angriffe auf eine Polizeistreife zu einer Konfrontation mit 500 Personen an; die Pyrotechnik-Intensität machte einen Feuerwehreinsatz unmöglich — ein Wasserwerfer musste die Löscharbeit der Feuerwehr übernehmen. In Duisburg-Hamborn wurde ein Feuerwehrmann gezielt mit einem Feuerwerkskörper auf Kopfhöhe beschossen. In Leipzig-Connewitz errichteten Gruppen brennende Barrikaden und attackierten systematisch Feuerwehr und Polizei. Wenn ein Wasserwerfer die Feuerwehr ersetzen muss und ein Räumpanzer den Rettungsdienst befreien, ist die Grenze zwischen Silvesterkrawall und urbanem Ausnahmezustand überschritten.`,
  },
  {
    title: 'Tödlicher Angriff auf Zugbegleiter bei Fahrkartenkontrolle',
    date: '2026-02-03',
    ort: 'Landstuhl / Homburg, Rheinland-Pfalz',
    relevance: 9,
    sourceUrl: 'https://homburg1.de/eskalation-bei-fahrkartenkontrolle-zugbegleiter-in-lebensgefahr-237815/',
    sourceName: 'Homburg1',
    lead: 'Ein Zugbegleiter wurde bei einer Fahrkartenkontrolle in einem Regionalexpress so schwer geschlagen, dass er zwei Tage später an einer Hirnblutung verstarb.',
    body: `Im Regionalexpress zwischen Landstuhl und Homburg schlug ein Fahrgast ohne gültiges Ticket einen Zugbegleiter bei der routinemäßigen Fahrkartenkontrolle so schwer, dass dieser am Tatort reanimiert werden musste. Zwei Tage später verstarb der Zugbegleiter an einer Hirnblutung. Die Tötung eines uniformierten Bahnangestellten bei der Ausübung einer alltäglichen Dienstpflicht — dem Kontrollieren einer Fahrkarte — stellt einen strukturellen Schwellenbruch dar. Das Tatmittel waren Fäuste, kein Messer: Die Hemmschwelle, einen Menschen mit bloßen Händen im Kontext einer Fahrpreisauseinandersetzung zu töten, beschreibt ein Enthemmungsniveau, das die bisherige Gewaltphänomenologie im Schienenverkehr in eine neue Kategorie hebt. Wenn die Kontrolle einer Fahrkarte tödlich endet, ist die physische Sicherheit von Bahnpersonal nicht mehr durch die soziale Norm des zivilen Umgangs gewährleistet.`,
  },
  {
    title: 'Mehrfach-Messerangriff im Schienenersatzverkehr in Wuppertal',
    date: '2026-02-14',
    ort: 'Wuppertal, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.wz.de/nrw/wuppertal/wuppertal-messerstecher-verletzt-mehrere-fahrgaeste-im-schienenersatzverkehr_aid-143882291',
    sourceName: 'Westdeutsche Zeitung',
    lead: 'In einem Schienenersatzverkehr-Bus am Wuppertaler Robert-Daum-Platz wurden drei Fahrgäste niedergestochen — die provisorische Transportform bot noch weniger Schutz als reguläre Züge.',
    body: `Am Robert-Daum-Platz in Wuppertal-Elberfeld wurden drei Fahrgäste in einem Bus des Schienenersatzverkehrs (SEV) mit einem Messer angegriffen. Mindestens zwei von ihnen erlitten schwere Verletzungen und mussten stationär behandelt werden. Der Vorfall ereignete sich an einem Karnevalssamstag gegen 23 Uhr. Die strukturelle Anomalie liegt in der Tatörtlichkeit: Ein SEV-Bus — eine temporäre Ersatzmodalität mit noch geringerer Sicherheitsinfrastruktur als ein regulärer Zug — bietet den Fahrgästen in einem vollbesetzten Bus keinerlei Ausweichmöglichkeit. Der Karnevalskontext erhöhte die Passagierdichte und senkte die Aufmerksamkeitsschwelle. Drei Opfer in einem einzelnen Bus-Angriff beschreiben ein Massenanfall-Muster in einer Transportform, die als bloßes Provisorium gar nicht als Gefährdungsraum konzipiert ist.`,
  },
  {
    title: 'Sprengsätze im ICE bei Siegburg',
    date: '2026-04-02',
    ort: 'Siegburg, Nordrhein-Westfalen',
    relevance: 9,
    sourceUrl: 'https://aachen.t-online.de/region/aachen/id_101198490/ice-von-aachen-nach-frankfurt-mann-zuendet-sprengstoff-zwoelf-verletzte.html',
    sourceName: 't-online Aachen',
    lead: 'Ein 20-Jähriger zündete im ICE 19 von Aachen nach Frankfurt zwei Sprengsätze und verletzte zwölf Fahrgäste — der Staatsschutz übernahm die Ermittlungen.',
    body: `Im ICE 19 von Aachen nach Frankfurt zündete ein 20-Jähriger gegen 21 Uhr zwei Sprengsätze und verletzte zwölf Fahrgäste. Der Zug wurde nahe Siegburg notgestoppt. Der Staatsschutz übernahm die Ermittlungen, ein politisches Motiv wurde nicht ausgeschlossen. Die strukturelle Anomalie ist die qualitative Eskalation des Angriffsmittels: Von Messern und Äxten zu improvisierten Sprengkörpern im Hochgeschwindigkeitszug. Der Einsatz zweier separater Sprengsätze deutet auf geplante Redundanz hin — ein einzelnes Versagen des Zünders sollte die Tat nicht verhindern. Die Jurisdiktion des Staatsschutzes signalisiert, dass die Behörden selbst den Vorfall jenseits konventioneller Gewaltkriminalität verorten. Wenn die Schienengewalt vom Messer zum Sprengstoff fortschreitet, ist eine kategoriale Grenze überschritten, die den ICE als vulnerablen geschlossenen Raum in die Nähe eines Flugzeugs rückt.`,
  },
];

let written = 0;
for (const c of cases) {
  writeItem({
    title: c.title,
    lead: c.lead,
    body: c.body,
    sourceUrl: c.sourceUrl,
    sourceName: c.sourceName,
    relevance: c.relevance,
    date: c.date,
    ort: c.ort,
  });
  written++;
}

const result = build();
console.log(`Nova-Seed-2 abgeschlossen: ${written} neue Einträge geschrieben, ${result.count} Detailseiten insgesamt generiert.`);
