// Einmaliges Seed-Skript: Schreibt das retroaktive Archiv (Phase 1)
// der Kriminologischen Nova. Danach build() für statische Seiten.
import { writeItem, build } from './render-nova.mjs';

const cases = [
  {
    title: 'Messerangriff im Regionalzug bei Brokstedt',
    date: '2023-01-25',
    ort: 'Brokstedt, Schleswig-Holstein',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Messerattacke_in_Brokstedt_am_25._Januar_2023',
    sourceName: 'Wikipedia',
    lead: 'In einem Regionalzug zwischen Kiel und Hamburg wurden zwei Fahrgäste getötet und fünf weitere verletzt — der Täter war sechs Tage zuvor aus der Untersuchungshaft entlassen worden.',
    body: `Der Messerangriff im Regionalzug RE70 nahe Brokstedt offenbart ein systemisches Versagen in der behördenübergreifenden Kommunikation. Zwei junge Fahrgäste im Alter von 17 und 19 Jahren wurden getötet, fünf weitere zum Teil schwer verletzt. Der Angreifer war sechs Tage vor der Tat aus der Untersuchungshaft der JVA Billwerder entlassen worden, weil die Haftdauer die vom Amtsgericht verhängte Strafe zu übersteigen drohte. Gegen ihn liefen zwischen 2015 und 2021 insgesamt 24 Ermittlungs- und Strafverfahren, darunter vier rechtskräftige Verurteilungen wegen schwerer Körperverletzung. Die Ausländerbehörde in Schleswig-Holstein wurde über die Haftentlassung in Hamburg nicht informiert — ein Kommunikationsbruch zwischen zwei Bundesländern. Der Fall verdeutlicht eine strukturelle Schwachstelle im föderalen System: Informationen über gewaltbereite, polizeibekannte Personen werden zwischen Justizvollzug, Staatsanwaltschaft und Verwaltungsbehörden nicht systematisch ausgetauscht. Die geschlossene Umgebung eines fahrenden Regionalzugs verschärfte die Situation, da den Fahrgästen keine Fluchtmöglichkeit blieb.`,
  },
  {
    title: 'Massenschießerei in Hamburger Königreichssaal',
    date: '2023-03-09',
    ort: 'Hamburg-Alsterdorf',
    relevance: 10,
    sourceUrl: 'https://de.wikipedia.org/wiki/Amoktat_in_Hamburg-Alsterdorf_2023',
    sourceName: 'Wikipedia',
    lead: 'Bei einem Angriff auf eine Gemeindeversammlung der Zeugen Jehovas wurden sieben Menschen erschossen und neun schwer verletzt — der Schütze besaß eine legale Waffenerlaubnis.',
    body: `Der Angriff auf den Königreichssaal der Zeugen Jehovas in Hamburg-Alsterdorf während eines Abendgottesdienstes stellt einen in Deutschland äußerst seltenen Angriff auf eine religiöse Minderheit dar. Sechs Gemeindemitglieder und ein ungeborenes Kind starben, neun weitere Personen erlitten schwere Verletzungen. Der Schütze tötete sich anschließend selbst. Die strukturelle Anomalie liegt im Versagen der Waffenbehörden: Trotz vorliegender Hinweise auf die mangelnde Eignung des Täters zum Waffenbesitz wurde die Erlaubnis nicht widerrufen. Sämtliche Verfahren gegen die zuständigen Beamten wurden eingestellt. Der Fall offenbart eine systemische Lücke in der Kontrolle legalen Waffenbesitzes in Deutschland — die behördliche Überprüfung der persönlichen Eignung funktioniert nicht als wirksame Barriere gegen den Missbrauch legal erworbener Schusswaffen. Die Tat zog eine bundesweite Debatte über die Reform des Waffenrechts nach sich.`,
  },
  {
    title: 'Tötungsdelikt in fränkischem Kinderheim',
    date: '2023-04-03',
    ort: 'Wunsiedel, Bayern',
    relevance: 8,
    sourceUrl: 'https://www.frankenpost.de/inhalt.wunsiedel-mord-an-maedchen-40-koepfige-soko-ermittelt.25af368f-79c4-4439-a675-0bbf6c266d6e.html',
    sourceName: 'Frankenpost',
    lead: 'Ein zehnjähriges Mädchen wurde in einem Kinderheim getötet — die Ermittlungen ergaben ein Versagen der Schutzeinrichtung bei der Verhinderung eines externen Eindringens.',
    body: `In einem Kinderheim in Wunsiedel wurde ein zehnjähriges Mädchen tot aufgefunden. Die Ermittlungen ergaben, dass ein 26-jähriger Außenstehender durch ein Fenster in die Einrichtung eingedrungen war und das Kind sexuell missbraucht hatte. Ein ebenfalls in der Einrichtung lebender elfjähriger Junge tötete das Mädchen. Die strukturelle Anomalie dieses Falls ist mehrschichtig: Eine Kinderschutzeinrichtung versagte bei ihrer grundlegendsten Aufgabe — dem physischen Schutz der ihr anvertrauten Kinder vor externem Zugriff. Der elfjährige Täter lag unterhalb der Strafmündigkeitsgrenze von 14 Jahren, was eine strafrechtliche Verfolgung unmöglich machte. Der Fall offenbart ein systemisches Defizit in der baulichen und organisatorischen Sicherheit stationärer Jugendhilfeeinrichtungen.`,
  },
  {
    title: 'Massenschlägerei im Mannheimer Herzogenriedbad',
    date: '2023-06-18',
    ort: 'Mannheim, Baden-Württemberg',
    relevance: 7,
    sourceUrl: 'https://www.rnf.de/mannheim-verletzte-bei-schlaegerei-von-rund-40-personen-im-herzogenriedbad-mann-mit-messer-verletzt-353899/',
    sourceName: 'RNF',
    lead: 'Eine Auseinandersetzung zwischen Kindern eskalierte innerhalb von Minuten zu einer Massenschlägerei mit über 40 Beteiligten und Messereinsatz in einem öffentlichen Freibad.',
    body: `Im Mannheimer Herzogenriedbad eskalierte ein Konflikt zwischen Kindern binnen Minuten zu einer Massenschlägerei mit über 40 Beteiligten. Auslöser war das Untertauchen eines zwölfjährigen Jungen. Als dessen Geschwister die Verursacher stellten, griffen sukzessive Familienmitglieder und Bekannte beider Seiten ein. Die Kaskadeneskalation — vom Kinderstreit zur bewaffneten Konfrontation — stellt ein in Freizeiteinrichtungen strukturell neuartiges Muster dar. Der Einsatz eines Messers in einer Schwimmbadumgebung ist phänomenologisch hochgradig atypisch. Nicht Polizei, sondern Badpersonal beendete die Auseinandersetzung. Der Fall markiert den Beginn einer Serie von Freibad-Gewalteskalationen, die in den Folgejahren in mehreren deutschen Städten dokumentiert wurden und zu weitreichenden Sicherheitsmaßnahmen führten.`,
  },
  {
    title: 'Freispruch trotz Geständnis vor US-Militärgericht in Wittlich',
    date: '2023-08-01',
    ort: 'Wittlich, Rheinland-Pfalz',
    relevance: 8,
    sourceUrl: 'https://www.lto.de/recht/hintergruende/h/freispruch-trotz-gestaendnis-wittlich-us-militaergericht-justice',
    sourceName: 'Legal Tribune Online',
    lead: 'Nach einer tödlichen Messerstecherei auf einer Kirmes wurde der geständige Täter von einem US-Militärgericht freigesprochen — wegen eines Übersetzungsfehlers in der Anklageschrift.',
    body: `Während der Säubrennerkirmes in Wittlich wurde ein 28-jähriger Deutscher erstochen. Der Täter, ein auf der Air Base Spangdahlem stationierter Soldat, legte ein Geständnis ab und wurde am Folgetag festgenommen. Im September 2024 sprach ein US-Militärgericht auf der Air Base den Angeklagten frei. Das Geständnis wurde nicht als Beweis zugelassen, weil die Anklagepunkte im Benachrichtigungsformular nicht ins Englische übersetzt worden waren — ein Verfahrensfehler, den deutsche Ermittler mitverschuldet hatten. Die Jury bestand aus Soldaten desselben Stützpunkts. Die strukturelle Anomalie liegt in der Paralleljustiz auf deutschem Boden: Die deutsche Justiz hatte keinen Einfluss auf den Prozessverlauf, konnte den Freispruch nicht anfechten und besaß keine Handhabe zur eigenständigen Strafverfolgung. Der Fall demonstriert eine grundlegende Schwachstelle im NATO-Truppenstatut, das den Entsendestaat mit der Gerichtsbarkeit über seine Soldaten betraut.`,
  },
  {
    title: 'Doppelmord am Oberhausener Hauptbahnhof durch Minderjährige',
    date: '2024-02-10',
    ort: 'Oberhausen, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://www.sportschau.de/regional/wdr/wdr-messerattacke-in-oberhausen-zweiter-ukrainischer-basketballer-gestorben-102.html',
    sourceName: 'Sportschau / WDR',
    lead: 'Zwei Basketballspieler wurden am Oberhausener Hauptbahnhof von einer Gruppe Minderjähriger mit Messerstichen getötet — die Täter waren zwischen 14 und 16 Jahre alt.',
    body: `Am Oberhausener Hauptbahnhof eskalierte gegen 20:15 Uhr ein Konflikt zwischen zwei Gruppen, nachdem diese gemeinsam einen Bus verlassen hatten. Zwei Basketballspieler im Alter von 25 und 26 Jahren wurden durch Messerstiche in Bauch und Rücken getötet. Vier Tatverdächtige im Alter von 14 bis 16 Jahren wurden wegen gemeinschaftlichen Mordes verurteilt. Die strukturelle Anomalie liegt im extrem jungen Alter der Täter für ein letales Gruppendelikt mit Messern — Doppelmord durch Minderjährige an einem öffentlichen Verkehrsknotenpunkt. Die Opfer befanden sich auf dem Heimweg von einem Sporttraining. Der Fall verdeutlicht die wachsende Problematik schwerer Messergewalt unter Jugendlichen an Transitorten und die Grenzen des Jugendstrafrechts bei Tötungsdelikten dieser Schwere.`,
  },
  {
    title: 'Schulattacke am Wilhelm-Dörpfeld-Gymnasium in Wuppertal',
    date: '2024-02-22',
    ort: 'Wuppertal, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://www.euronews.com/2024/02/22/four-injured-in-school-stabbing-in-western-germany',
    sourceName: 'Euronews',
    lead: 'Ein 17-jähriger Schüler verletzte vier Mitschüler mit einem Klappmesser im Oberstufenraum — ein Lehrer konnte den Angreifer zum Ablegen der Waffe bewegen.',
    body: `Am Wilhelm-Dörpfeld-Gymnasium in Wuppertal griff ein 17-jähriger Schüler gegen 9:50 Uhr vier Mitschüler im Alter von 16 und 17 Jahren mit einem Klappmesser an. Die Opfer erlitten Stich- und Schnittverletzungen an Hals und Kopf und wurden stationär behandelt. Ein Lehrer überzeugte den Angreifer, die Waffe niederzulegen. Der Vorfall löste einen SEK-Einsatz aus. Messerangriffe innerhalb deutscher Schulen stellen ein historisch seltenes Tatmuster dar — das deutsche Bildungssystem kennt weder Zugangskontrollen noch Waffenscreenings. Der Angriff im informellen Aufenthaltsraum der Oberstufe verdeutlicht die strukturelle Schutzlosigkeit deutscher Bildungseinrichtungen gegenüber Waffenträgern. Die Tat löste eine bundesweite Debatte über Waffenverbote in Schulen aus.`,
  },
  {
    title: 'Tötung eines Forensik-Arztes in Wasserburg am Inn',
    date: '2024-04-08',
    ort: 'Wasserburg am Inn, Bayern',
    relevance: 8,
    sourceUrl: 'https://www.polizei.bayern.de/aktuelles/pressemitteilungen/065292/index.html',
    sourceName: 'Bayerische Polizei',
    lead: 'Ein ehemaliger Patient erstach einen Oberarzt der forensischen Psychiatrie auf dem Klinikgelände — der Arzt hatte in einem Strafverfahren ein Gutachten gegen ihn erstellt.',
    body: `Auf dem Parkplatz der Inn-Salzach-Klinik in Wasserburg am Inn wurde ein 64-jähriger Oberarzt der forensischen Psychiatrie mit einem Küchenmesser getötet. Der Angreifer war ein ehemaliger Patient, der angab, der Arzt habe in einem psychiatrischen Gutachten falsche Angaben gemacht. Die Polizei klassifizierte die Tat als gezielten Angriff. Die strukturelle Anomalie liegt in der Doppelrolle des Opfers: Als behandelnder Arzt und zugleich forensischer Gutachter im Strafverfahren wurde er zum spezifischen Ziel. Der Fall offenbart die systemische Vulnerabilität von Klinikern, die sowohl therapeutische als auch justizielle Funktionen ausüben — eine Personalunion, die in der forensischen Psychiatrie strukturell angelegt ist. Die Tat ereignete sich auf dem Klinikgelände, dem Arbeitsort des Opfers, und verdeutlicht die unzureichende Absicherung forensisch-psychiatrischer Einrichtungen.`,
  },
  {
    title: 'Terroranschlag auf Kundgebung am Mannheimer Marktplatz',
    date: '2024-05-31',
    ort: 'Mannheim, Baden-Württemberg',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Messerangriff_in_Mannheim_am_31._Mai_2024',
    sourceName: 'Wikipedia',
    lead: 'Bei einem islamistisch motivierten Messerangriff auf eine politische Kundgebung wurde ein Polizeibeamter getötet und fünf Personen schwer verletzt — gegen den Täter bestand seit 2019 ein offener Haftbefehl.',
    body: `Der Messerangriff auf eine Veranstaltung des Bürgervereins Pax Europa auf dem Mannheimer Marktplatz vereint zwei strukturelle Anomalien: den gezielten Angriff auf eine politische Veranstaltung im öffentlichen Raum und die Tötung eines intervenierenden Polizeibeamten. Fünf weitere Personen wurden schwer verletzt. Die Bundesanwaltschaft übernahm die Ermittlungen und qualifizierte die Tat als islamistisch motivierten Terroranschlag. Gegen den Täter bestand seit 2019 ein offener Haftbefehl wegen Widerstands gegen Vollstreckungsbeamte, Beleidigung und vorsätzlicher Körperverletzung sowie ein Einreiseverbot für den Schengen-Raum. Trotz dieser Maßnahmen lebte er seit 2014 unbehelligt in Deutschland. Das Oberlandesgericht Stuttgart verurteilte ihn im September 2025 zu lebenslanger Freiheitsstrafe mit Feststellung der besonderen Schwere der Schuld. Der Fall verdeutlicht ein doppeltes Systemversagen: die Nichtdurchsetzung bestehender Haftbefehle und die strukturelle Schutzlosigkeit politischer Veranstaltungen im öffentlichen Raum.`,
  },
  {
    title: 'Angriffsserie während der EM-Übertragung in Wolmirstedt',
    date: '2024-06-14',
    ort: 'Wolmirstedt, Sachsen-Anhalt',
    relevance: 8,
    sourceUrl: 'https://www.zdf.de/nachrichten/panorama/em-party-tote-polizei-100.html',
    sourceName: 'ZDF',
    lead: 'Während des EM-Eröffnungsspiels tötete ein Angreifer zunächst einen Mann in einem Wohnhaus und griff dann eine private Gartenparty an — die Polizei erschoss den Täter.',
    body: `In Wolmirstedt kam es während des EM-Eröffnungsspiels Deutschland gegen Schottland zu einer sequenziellen Angriffsserie an zwei Tatorten. Der Täter tötete zunächst einen 23-Jährigen in einem nahegelegenen Wohngebäude und drang anschließend in den Garten eines Einfamilienhauses ein, wo eine private Fußball-Übertragungsparty stattfand. Eine 50-jährige Frau und ein 75-jähriger Mann erlitten schwere Verletzungen. Polizeibeamte erschossen den Angreifer, als dieser auf sie zulief. Die strukturelle Anomalie liegt im Tatmuster: Die Verknüpfung einer Wohnungstat mit dem Angriff auf eine private Festgesellschaft während eines Großereignisses stellt ein neuartiges Phänomen dar. Die Vorhersehbarkeit privater Zusammenkünfte während medialer Großereignisse schafft eine Verwundbarkeit, die durch konventionelle Sicherheitskonzepte nicht adressierbar ist.`,
  },
  {
    title: 'Gruppengewalt gegen Jugendliche im Berliner Sommerbad',
    date: '2024-07-06',
    ort: 'Berlin-Neukölln',
    relevance: 7,
    sourceUrl: 'https://www.tagesspiegel.de/berlin/gruppe-schlagt-auf-zwei-bruder-ein-freibad-in-berlin-neukolln-nach-randale-vorzeitig-geschlossen-12060092.html',
    sourceName: 'Der Tagesspiegel',
    lead: 'Rund 20 Jugendliche griffen zwei Brüder im Sommerbad Gropiusstadt an — die erste erzwungene Frühschließung eines Berliner Freibads in der Saison 2024.',
    body: `Im Sommerbad Gropiusstadt in Berlin-Neukölln attackierten etwa 20 Jugendliche zwei Brüder im Alter von 14 und 15 Jahren mit Faustschlägen ins Gesicht. Die Badeeinrichtung wurde erstmals in der Saison 2024 vorzeitig geschlossen. Sowohl Opfer als auch Angreifer flohen vor Eintreffen der Polizei. Die strukturelle Anomalie besteht im asymmetrischen Zahlenverhältnis von etwa zehn zu eins gegen Minderjährige in einer beaufsichtigten öffentlichen Freizeiteinrichtung. Der Vorfall fügt sich in ein wiederkehrendes saisonales Muster ein: Seit 2019 dokumentieren Berliner Bäder regelmäßig Gewalteskalationen, die zu institutionellen Reaktionen wie Sicherheitspersonal, Ausweiskontrollen und vorgezogenen Schließungen geführt haben. Die progressive Versicherheitlichung öffentlicher Freizeitinfrastruktur markiert eine strukturelle Verschiebung im Umgang mit Jugendgewalt.`,
  },
  {
    title: 'Femizid in Berlin-Friedrichsfelde trotz behördlicher Hilfesuche',
    date: '2024-08-01',
    ort: 'Berlin-Friedrichsfelde',
    relevance: 7,
    sourceUrl: 'https://www.onebillionrising.de/femizid-opfer-meldungen-2024/',
    sourceName: 'One Billion Rising Deutschland',
    lead: 'Eine 28-jährige Frau wurde von ihrem ehemaligen Partner vor ihrer Wohnung getötet — sie hatte zuvor Schutz bei den Behörden gesucht.',
    body: `In Berlin-Friedrichsfelde wurde eine 28-jährige Frau mit einem Messer vor ihrer Wohnung von ihrem ehemaligen Partner getötet. Das Opfer hatte zuvor bei den Behörden um Schutz nachgesucht. Der Fall wurde zu einem prominenten Beispiel in der bundesweiten Femizid-Debatte. Die strukturelle Anomalie liegt nicht im Einzelfall, sondern im dokumentierten Systemversagen: Die bestehenden Schutzinstrumente — Gewaltschutzgesetz, Kontaktverbote, Gefährdungsansprache — griffen nicht. Die Polizeiliche Kriminalstatistik 2024 verzeichnete 308 getötete Frauen und Mädchen in Deutschland. Der Fall verdeutlicht die strukturelle Lücke zwischen der Hilfesuche durch Betroffene und einer wirksamen behördlichen Intervention — ein Muster, das die Kriminologie als institutionelles Schutzdefizit bei Hochrisikofällen häuslicher Gewalt beschreibt.`,
  },
  {
    title: 'Serielle Fahrzeugangriffe auf Frauen in Essen und Köln',
    date: '2024-08-05',
    ort: 'Essen und Köln, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://taxi-times.com/taxifahrer-faehrt-passantinnen-in-essen-und-koeln-an-das-geschah-wirklich/',
    sourceName: 'Taxi Times',
    lead: 'Ein Taxifahrer fuhr am selben Abend in zwei Städten gezielt weibliche Fußgängerinnen an — in Essen erlitt eine Frau lebensbedrohliche Verletzungen, in Köln wurden vier weitere Frauen verletzt.',
    body: `Am Abend des 5. August 2024 steuerte ein Taxifahrer in Essen sein Fahrzeug gezielt auf eine Fußgängerin und verursachte lebensbedrohliche Verletzungen. Anschließend fuhr er nach Köln und überfuhr in der Altstadt vier weitere Frauen, zwei davon schwer. Der Fahrer wendete, um einzelne Opfer ein zweites Mal zu überfahren. Die strukturelle Anomalie liegt in der Verwendung eines Vertrauensfahrzeugs — eines lizenzierten Taxis — als Waffe gegen ausschließlich weibliche Opfer, und in der stadienübergreifenden Tatbegehung. Der Fall ist in der jüngeren deutschen Kriminalgeschichte ohne Parallele: ein geschlechtsspezifisch motivierter Serienangriff mit einem Kfz über zwei Großstädte hinweg. Die Tat wirft Fragen zur Prüfung der persönlichen Eignung im Personenbeförderungsgewerbe auf.`,
  },
  {
    title: 'Terroranschlag auf dem Solinger Stadtfest',
    date: '2024-08-23',
    ort: 'Solingen, Nordrhein-Westfalen',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Messeranschlag_in_Solingen',
    sourceName: 'Wikipedia',
    lead: 'Beim Stadtfest zum 650-jährigen Jubiläum Solingens wurden drei Menschen durch Messerstiche getötet und acht verletzt — der IS reklamierte die Tat, der Täter hätte nach Dublin-Verordnung überstellt werden müssen.',
    body: `Der Messeranschlag auf dem Solinger Stadtfest „Festival der Vielfalt" am Abend des 23. August 2024 tötete drei Menschen und verletzte acht weitere, vier davon lebensbedrohlich. Der Islamische Staat bekannte sich am Folgetag. Die strukturelle Anomalie erstreckt sich auf zwei Ebenen: Erstens wurde ein kommunales Kulturfest — ein in der Bedrohungsanalyse bis dahin nicht als Hochrisikoziel bewertetes Soft Target — zum Anschlagsziel. Zweitens offenbarte der Fall ein systemisches Versagen im Dublin-Verfahren: Der Täter hätte nach der Dublin-III-Verordnung nach Bulgarien überstellt werden müssen. Die Überstellung scheiterte, weil er bei der geplanten Abholung nicht angetroffen wurde. Die Behörden versäumten anschließend, die Sechs-Monats-Frist für eine erneute Überstellung zu verlängern, sodass Deutschland automatisch zuständig wurde. Der Fall führte zu einem parlamentarischen Untersuchungsausschuss, dem Rücktritt einer Landesministerin und bundesweiten Verschärfungen im Asyl- und Waffenrecht.`,
  },
  {
    title: 'Messerangriff mit Selbstjustiz-Verfolgung in Duisburg',
    date: '2024-10-24',
    ort: 'Duisburg, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.presseportal.de/blaulicht/pm/50510/5897629',
    sourceName: 'Presseportal / Polizei Duisburg',
    lead: 'Nach einer Messerattacke auf offener Straße verfolgten Angehörige des Opfers den fliehenden Täter im Auto und griffen das Fahrzeug mit Holzlatten an.',
    body: `In Duisburg stach ein 19-Jähriger einem 25-Jährigen auf offener Straße in den Rücken und flüchtete mit einem Pkw. Verwandte des Opfers erkannten den Flüchtenden im Straßenverkehr, verfolgten sein Fahrzeug, stellten es und schlugen mit Holzlatten auf den Wagen ein. Die Polizei intervenierte und nahm den Angreifer fest. Die strukturelle Anomalie liegt in der sofortigen Selbstjustiz-Eskalation: Vom Messerangriff über die Kfz-Verfolgungsjagd bis zur gruppenbasierten Vergeltung im öffentlichen Verkehr entstand eine Dynamik, die über konventionelle Gewaltkriminalität hinausgeht. Das Muster — Tat, Erkennung, Verfolgung, Gegengewalt — beschreibt ein Phänomen des Zusammenbruchs des staatlichen Gewaltmonopols in der Wahrnehmung der Beteiligten.`,
  },
  {
    title: 'Bewaffnete Massenschlägerei in Mockrehna',
    date: '2024-10-25',
    ort: 'Mockrehna, Nordsachsen',
    relevance: 7,
    sourceUrl: 'https://ms-aktuell.de/welt/massenschlaegerei-mockrehna-polizeieinsatz-verletzte/',
    sourceName: 'MS Aktuell',
    lead: 'Rund 40 Personen prügelten mit Schaufeln, Baseballschlägern und Stöcken aufeinander ein — die Kleinstadt benötigte Polizeiverstärkung aus drei Jurisdiktionen.',
    body: `Auf der Reichsstraße in Mockrehna eskalierte eine Konfrontation zwischen zwei Gruppen von jeweils etwa 20 Personen an einem Freitagabend. Die Beteiligten setzten Schaufeln, Baseballschläger und Stöcke als Waffen ein. Sieben Personen wurden verletzt, vier davon stationär behandelt. Die Polizei musste Verstärkung aus umliegenden Landkreisen, der Bundespolizei und aus Dresden anfordern. Die strukturelle Anomalie besteht in der Vorausrüstung mit improvisierten Waffen, die auf eine Verabredung zur Gewalt hindeutet. Mockrehna hat weniger als 5.000 Einwohner — die extreme Disproportion zwischen Ortsgröße und Gewaltausmaß überforderte die lokalen Sicherheitsstrukturen und erforderte eine behördenübergreifende, landesweite Polizeioperation.`,
  },
  {
    title: 'Fahrzeuganschlag auf den Magdeburger Weihnachtsmarkt',
    date: '2024-12-20',
    ort: 'Magdeburg, Sachsen-Anhalt',
    relevance: 10,
    sourceUrl: 'https://de.wikipedia.org/wiki/Anschlag_auf_den_Magdeburger_Weihnachtsmarkt',
    sourceName: 'Wikipedia',
    lead: 'Ein Pkw durchbrach die Sicherheitsabsperrung des Weihnachtsmarkts auf dem Alten Markt und tötete sechs Menschen — über 300 wurden verletzt, die höchste Opferzahl eines Einzelanschlags in Deutschland seit 2016.',
    body: `Am Abend des 20. Dezember 2024 wurde ein Fahrzeug mit bis zu 48 km/h durch eine Lücke im Sicherheitsperimeter des Magdeburger Weihnachtsmarkts auf dem Alten Markt gesteuert. Sechs Menschen wurden getötet, über 300 verletzt. Der Fahrer wurde unmittelbar festgenommen. Die strukturelle Anomalie offenbart sich im spezifischen Versagen des physischen Schutzkonzepts: Der Angreifer nutzte eine Rettungszufahrt, die durch eine Kette zwischen zwei Betonblöcken und ein als mobile Sperre vorgesehenes Polizeifahrzeug gesichert werden sollte. Die Kette war nicht gespannt, das Polizeifahrzeug stand 30 Meter von seiner zugewiesenen Position entfernt. Ein parlamentarischer Untersuchungsausschuss dokumentierte multiple Versäumnisse bei Polizei, Veranstalter und Stadtverwaltung. Trotz der bundesweiten Einführung von Schutzkonzepten nach dem Breitscheidplatz-Anschlag 2016 erwies sich die Umsetzung als lückenhaft. Der Fall stellt die höchste Opferzahl eines Einzelanschlags in Deutschland seit acht Jahren dar.`,
  },
  {
    title: 'Silvester-Angriffe auf Rettungskräfte in Berlin und Leipzig',
    date: '2024-12-31',
    ort: 'Berlin und Leipzig',
    relevance: 8,
    sourceUrl: 'https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1517844.php',
    sourceName: 'Polizei Berlin',
    lead: 'In der Silvesternacht 2024/2025 wurden in Berlin 430 Personen festgenommen und 37 Polizeibeamte verletzt — in Leipzig mussten Feuerwehr und Polizei vor massivem Pyrotechnik-Beschuss taktisch zurückweichen.',
    body: `Die Silvesternacht 2024/2025 markiert einen erneuten Eskalationspunkt gezielter Gewalt gegen Einsatzkräfte. In Berlin wurden 430 Personen festgenommen, 37 Polizeibeamte verletzt — 14 durch Pyrotechnik — und rund 670 Ermittlungsverfahren eingeleitet. In Leipzig-Grünau waren die Angriffe auf Feuerwehrleute mit Feuerwerkskörpern so massiv, dass Feuerwehr und Polizeiunterstützungskräfte taktisch zurückweichen mussten. In Leipzig-Connewitz wurden Barrikaden errichtet und ein Wasserwerfer eingesetzt. Die strukturelle Anomalie liegt in der systemischen, mehrstädtischen, zeitlich synchronisierten Gewalt gegen uniformierte Rettungskräfte. Die Verwendung von Feuerwerk als improvisierte Waffe gegen Einsatzkräfte bei lebensrettenden Tätigkeiten stellt ein jährlich wiederkehrendes Muster dar, das in dieser Nacht eine besondere Intensität erreichte. Der erzwungene taktische Rückzug kombinierter Feuerwehr-Polizei-Einheiten ist strukturell extrem.`,
  },
  {
    title: 'Messerangriff auf Kindergartengruppe im Aschaffenburger Schöntal-Park',
    date: '2025-01-22',
    ort: 'Aschaffenburg, Bayern',
    relevance: 9,
    sourceUrl: 'https://www.zdf.de/nachrichten/panorama/kriminalitaet/aschaffenburg-messerangriff-chronologie-behoerden-100.html',
    sourceName: 'ZDF',
    lead: 'Im Park Schöntal wurden ein Kleinkind und ein eingreifender Passant getötet sowie drei weitere Personen schwer verletzt — der polizeibekannte Täter befand sich trotz dokumentierter Gewaltbereitschaft ohne Aufsicht.',
    body: `Im Aschaffenburger Park Schöntal griff ein Mann mit einem 32-Zentimeter-Küchenmesser eine Kindergartengruppe an, die sich mit einem Transportwagen auf einem Spaziergang befand. Ein zweijähriger Junge und ein 41-jähriger Mann, der schützend eingriff, wurden getötet. Ein weiteres Kleinkind und ein 73-jähriger Mann erlitten schwere Verletzungen. Der Täter war polizeibekannt wegen mehrerer Gewalttaten seit 2023 und stand seit Dezember 2024 unter Betreuung aufgrund einer diagnostizierten paranoid-schizophrenen Erkrankung. Sein Asylantrag war abgelehnt, eine Abschiebung bereits 2023 gescheitert, und er hatte schriftlich erklärt, freiwillig ausreisen zu wollen. Die strukturelle Anomalie liegt im kumulativen Behördenversagen: Trotz dokumentierter Gewaltbereitschaft, psychiatrischer Diagnose und abgelehntem Asylantrag wurde weder ein Haftbefehl noch eine vorläufige psychiatrische Unterbringung angeordnet. Das Gericht verfügte die dauerhafte Unterbringung in der Psychiatrie. Der Fall löste eine bundesweite Debatte über systemische Lücken bei der Unterbringung bekanntermaßen gefährlicher psychisch kranker Personen aus.`,
  },
  {
    title: 'Messerattacke am Leipziger Hauptbahnhof',
    date: '2025-01-30',
    ort: 'Leipzig, Sachsen',
    relevance: 7,
    sourceUrl: 'https://www.presseportal.de/blaulicht/pm/74165/5979744',
    sourceName: 'Presseportal / Bundespolizei',
    lead: 'Am Leipziger Hauptbahnhof — 2025 der Bahnhof mit den meisten Gewaltdelikten in Deutschland — wurde ein Mann niedergestochen.',
    body: `Am Leipziger Hauptbahnhof wurde ein Mann durch Messerstiche verletzt. Der Tatverdächtige konnte durch Auswertung von Videoüberwachungsaufnahmen identifiziert und später bei einer Routinekontrolle in Chemnitz festgenommen werden. Der Einzelfall gewinnt seine strukturelle Bedeutung durch den Kontext: Der Leipziger Hauptbahnhof verzeichnete 2025 mit 859 Gewaltdelikten die höchste Zahl aller deutschen Bahnhöfe. Die Apprehension in einer anderen Stadt über jurisdiktionsübergreifende Polizeiarbeit ist kennzeichnend für die Mobilität von Tatverdächtigen im Transitumfeld. Der Fall illustriert die systemische Herausforderung der Sicherheit an hochfrequentierten Verkehrsknotenpunkten, an denen sich Opfer- und Tätermobilität, Anonymität und unzureichende Zugangskontrollen überlagern.`,
  },
  {
    title: 'Fahrzeugangriff auf Gewerkschaftsdemonstration in München',
    date: '2025-02-13',
    ort: 'München, Bayern',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Anschlag_in_M%C3%BCnchen_2025',
    sourceName: 'Wikipedia',
    lead: 'Ein Pkw wurde in einen ver.di-Demonstrationszug in der Seidlstraße gesteuert — eine Mutter und ihr zweijähriges Kind starben, 44 Personen wurden verletzt.',
    body: `Am 13. Februar 2025 um 10:31 Uhr steuerte der Fahrer eines Mini Cooper gezielt in einen Demonstrationszug der Gewerkschaft ver.di auf der Seidlstraße in München. 44 Personen wurden verletzt, eine Mutter und ihr zweijähriges Kind erlagen zwei Tage später ihren Verletzungen. Der Fahrer wurde unmittelbar festgenommen. Die Bundesanwaltschaft klassifizierte das Motiv als islamistisch. Die strukturelle Anomalie liegt im neuartigen Zieltyp: Ein sich bewegender Demonstrationszug — eine dynamische, lineare Formation auf einer Straße — ist im Gegensatz zu statischen Versammlungen oder Fußgängerzonen nicht durch Fahrzeugbarrieren schützbar. Demonstrationen genießen in Deutschland keine physische Infrastrukturprotektion. Die Tat offenbart eine grundlegende Verwundbarkeit des Versammlungsrechts: Die Freiheit zur politischen Demonstration setzt die physische Schutzlosigkeit der Teilnehmenden voraus. Der Prozess begann im Januar 2026 vor dem OLG München.`,
  },
  {
    title: 'Messerangriff auf Grundschulkinder in Duisburg-Marxloh',
    date: '2025-02-28',
    ort: 'Duisburg-Marxloh, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://www.ruhrnachrichten.de/regionales/messerangriff-in-duisburg-zwei-kinder-schwer-verletzt-21-jaehriger-festgenommen-w849734-2001123189/',
    sourceName: 'Ruhr Nachrichten',
    lead: 'Ein 21-Jähriger griff zwei Grundschulkinder im Alter von neun und zehn Jahren mit einem Messer an — sein eigener Vater entwaffnete und überwältigte ihn.',
    body: `In Duisburg-Marxloh attackierte ein 21-Jähriger zwei Grundschulkinder im Alter von neun und zehn Jahren mit einem Messer und verletzte beide schwer. Der Angreifer wurde von seinem eigenen Vater, einem 69-Jährigen, gestoppt und entwaffnet, der seinen Sohn bis zum Eintreffen der Polizei festhielt. Gegen den Täter erging Haftbefehl wegen zweifachen versuchten Mordes. Die strukturelle Anomalie liegt im gezielten Angriff auf Grundschulkinder im öffentlichen Raum — Kinder im Alter von neun und zehn Jahren, die sich außerhalb schulischer Infrastruktur befanden und keinerlei Abwehr- oder Fluchtmöglichkeit besaßen. Die familieninterne Überwältigung des Täters durch den eigenen Vater ist phänomenologisch ungewöhnlich und wirft Fragen zur Kenntnis über die Gefährlichkeit innerhalb des familiären Umfelds auf.`,
  },
  {
    title: 'Fahrzeugangriff auf Fastnachtsmarkt in Mannheim',
    date: '2025-03-03',
    ort: 'Mannheim, Baden-Württemberg',
    relevance: 8,
    sourceUrl: 'https://de.wikipedia.org/wiki/Amokfahrt_in_Mannheim_2025',
    sourceName: 'Wikipedia',
    lead: 'Ein Pkw wurde während des Fastnachtsmarkts in die Fußgängerzone der Planken gesteuert — zwei Menschen starben, elf wurden verletzt.',
    body: `Am 3. März 2025 gegen 12:15 Uhr wurde ein Ford Fiesta vom Friedrichsring in die Fußgängerzone der Planken in Mannheim gesteuert, wo der Fastnachtsmarkt mit Ständen zwischen Wasserturm und Paradeplatz stattfand. Zwei Menschen wurden getötet, elf verletzt. Der Fahrer wurde am Tatort festgenommen. Die strukturelle Anomalie liegt in der Zielkategorie: Ein saisonaler Jahrmarkt in einer Fußgängerzone — eine temporäre Festveranstaltung, die im Vergleich zu Weihnachtsmärkten über eine weniger formalisierte Fahrzeugbarrieren-Infrastruktur verfügt. Die Tat führte zur sofortigen Absage von Fastnachtsumzügen in Heidelberg, Brühl und Schwetzingen. Der Täter wurde im Dezember 2025 zu lebenslanger Freiheitsstrafe verurteilt, mit Einweisung in die Psychiatrie. Der Fall demonstriert, dass die nach 2016 entwickelten Schutzkonzepte für Weihnachtsmärkte nicht systematisch auf andere saisonale Veranstaltungen übertragen wurden.`,
  },
  {
    title: 'Messerattacke auf Bahnsteig des Frankfurter Hauptbahnhofs',
    date: '2025-03-15',
    ort: 'Frankfurt am Main, Hessen',
    relevance: 7,
    sourceUrl: 'https://www.hessenschau.de/panorama/messerangriff-am-gleis-im-frankfurter-hauptbahnhof-v1,kurz-angriff-324.html',
    sourceName: 'hessenschau',
    lead: 'Auf dem Bahnsteig 104 des Frankfurter Hauptbahnhofs stach ein 19-Jähriger auf einen 25-Jährigen ein — einer von mehreren Messervorfällen am selben Bahnhof im Jahr 2025.',
    body: `Am Frankfurter Hauptbahnhof stach ein 19-Jähriger mit einem sieben Zentimeter langen Messer auf Bahnsteig 104 auf einen 25-Jährigen ein. Die Tat war einer von mindestens drei dokumentierten Messervorfällen am selben Bahnhof im Jahr 2025. Die Häufung führte zu einem formalen Sicherheitsabkommen zwischen Stadt, Deutscher Bahn und Polizei mit verstärkten Razzien, Patrouillen und Überwachung. Die strukturelle Anomalie liegt in der Cluster-Bildung: Die Konzentration von Messergewalt an einem einzelnen Verkehrsknoten erzwingt eine institutionelle Reaktion, die über konventionelle Polizeiarbeit hinausgeht. Die Einbeziehung des Bahnbetreibers in ein Sicherheitsabkommen markiert eine Verschiebung der Verantwortungsstrukturen — weg von der ausschließlich polizeilichen Zuständigkeit hin zu einer Mehrakteurs-Sicherheitsarchitektur.`,
  },
  {
    title: 'Islamistischer Anschlag mit verkleideter Stockwaffe in Bielefeld',
    date: '2025-05-18',
    ort: 'Bielefeld, Nordrhein-Westfalen',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Messerangriff_in_Bielefeld_2025',
    sourceName: 'Wikipedia',
    lead: 'Ein Angreifer tarnte sich als Gehbehinderter, nutzte einen zu einer Stichwaffe umgebauten Gehstock und attackierte in den Morgenstunden fünf Personen vor einer Gaststätte.',
    body: `In den frühen Morgenstunden des 18. Mai 2025 gegen 4:20 Uhr mischte sich ein Mann unter die Gäste einer Gaststätte in der Bielefelder Innenstadt. Er stützte sich auf einen Gehstock und simulierte eine Behinderung, um sich den Opfern zu nähern. Der Stock war zu einer verdeckten Klingenwaffe umgebaut worden — einem sogenannten Stockdegen. Unter dem Rufen religiöser Parolen griff er fünf Personen an und verletzte mehrere von ihnen schwer. Der Angreifer stand in Verbindung mit dem IS. Die strukturelle Anomalie liegt in der Verwendung einer getarnten Waffe und der taktischen Täuschung durch vorgetäuschte Behinderung — ein in der deutschen Kriminalgeschichte beispielloses Vorgehen. Die Tat ereignete sich in einem Nachtleben-Kontext in den Morgenstunden, einer Tageszeit und einem Setting, die in der Bedrohungsanalyse als wenig exponiert gelten. Der Fall demonstriert eine Innovationsdynamik in der terroristischen Tatbegehung.`,
  },
  {
    title: 'Elfjährige Schülerin ersticht Mitschüler in Remscheid',
    date: '2025-05-22',
    ort: 'Remscheid, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.tagesspiegel.de/gesellschaft/panorama/nach-messerangriff-auf-13-jahrigen-polizei-in-remscheid-ubergibt-11-jahrigen-wieder-den-eltern-13740730.html',
    sourceName: 'Tagesspiegel',
    lead: 'Ein elfjähriges Kind verletzte einen 13-jährigen Mitschüler mit einem Küchenmesser — das Kind liegt unterhalb der Strafmündigkeitsgrenze.',
    body: `In der Remscheider Innenstadt stach ein elfjähriges Kind gegen 14:50 Uhr einen 13-jährigen Mitschüler mit einem von zu Hause mitgebrachten Küchenmesser ins Bein. Die Kinder hatten sich nach vorherigen Streitigkeiten verabredet. Das Opfer wurde mit nicht-lebensbedrohlichen Verletzungen stationär behandelt. Der Angreifer wurde am selben Abend in die Obhut der Eltern übergeben, da er mit elf Jahren unter der Strafmündigkeitsgrenze von 14 Jahren in Deutschland liegt. Die strukturelle Anomalie besteht im extremen Alter des Täters und in der Tatsache, dass an demselben Tag in Berlin ein weiterer Messerangriff zwischen Schülern dokumentiert wurde. Dieses zeitliche Zusammentreffen zweier jugendlicher Messerangriffe am selben Tag deutet auf ein Eskalationsmuster in der Peer-Gewalt unter Minderjährigen hin, das die Grenzen des deutschen Strafrechts offenlegt.`,
  },
  {
    title: 'Massenangriff am Hamburger Hauptbahnhof',
    date: '2025-05-23',
    ort: 'Hamburg',
    relevance: 9,
    sourceUrl: 'https://de.wikipedia.org/wiki/Messerangriff_am_Hamburger_Hauptbahnhof_2025',
    sourceName: 'Wikipedia',
    lead: 'Am Hamburger Hauptbahnhof wurden 15 Reisende niedergestochen — der Täter war einen Tag zuvor aus einer psychiatrischen Einrichtung entlassen worden.',
    body: `Am 23. Mai 2025 wurden am Hamburger Hauptbahnhof 15 Reisende durch Messerstiche verletzt, drei davon lebensgefährlich und sechs weitere schwer. Zwei couragierte Passanten überwältigten den Angreifer und hielten ihn bis zum Eintreffen der Polizei fest. Der Täter war einen Tag vor der Tat aus einer psychiatrischen Einrichtung entlassen worden. Er litt an einer diagnostizierten paranoid-schizophrenen Erkrankung und war zwischen 2022 und 2025 insgesamt 32 Mal psychiatrisch stationär aufgenommen worden. Bereits im Februar 2025 hatte er am Hamburger Flughafen eine Gewalttat begangen. Die strukturelle Anomalie liegt im Versagen der psychiatrischen Entlass-Nachsorge: Wiederholte kurzzeitige Hospitalisierungen ohne nachhaltige Unterbringung oder Überwachung nach Entlassung schufen ein Drehtür-Syndrom. Die Transitinfrastruktur eines Hauptbahnhofs bot keinerlei Barriere gegen den Angriff. Das Gericht verfügte im Januar 2026 die dauerhafte psychiatrische Unterbringung mit Verurteilung wegen versuchten Totschlags in 15 Fällen.`,
  },
  {
    title: 'Massenconfrontation mit Waffenarsenal in Dortmund-Nordstadt',
    date: '2025-05-26',
    ort: 'Dortmund-Nordstadt, Nordrhein-Westfalen',
    relevance: 8,
    sourceUrl: 'https://rundblick-unna.de/2026/05/27/gewalteskalation-in-do-nord-mit-messern-machete-axt-schusswaffe-sieben-beteiligte-mehrere-hundert-gaffer/',
    sourceName: 'Rundblick Unna',
    lead: 'Ein Streit zwischen zwei kleinen Gruppen eskalierte auf der Schleswiger Straße zu einer Massenkonfrontation mit 250 bis 300 Beteiligten — mit Messern, Machete, Axt und Schusswaffe.',
    body: `Auf der Schleswiger Straße in Dortmund-Nordstadt eskalierte ein Streit zwischen zwei kleinen Gruppen zu einer Massenkonfrontation mit 250 bis 300 Beteiligten. Die Teilnehmer setzten Messer, eine Machete, eine Axt und eine Schusswaffe ein. Die Polizei stellte mit einem Großaufgebot die Ordnung wieder her. Die strukturelle Anomalie liegt in der extremen Kaskadendynamik: Ein interpersoneller Konflikt zwischen Wenigen zog innerhalb von Minuten Hunderte Zuschauer und Beteiligte an, die eine bürgerkriegsähnliche Situation erzeugten. Die Vielfalt der gleichzeitig eingesetzten Waffentypen — vom Messer bis zur Schusswaffe — ist phänomenologisch hochgradig ungewöhnlich. Als institutionelle Reaktion richtete die Polizei ein dediziertes „Gewaltkommissariat" ein, um solche Eskalationsmuster zentral zu erfassen — eine behördliche Innovation, die eine neue Bedrohungskategorie widerspiegelt.`,
  },
  {
    title: 'Soziale-Medien-getriggerte Messerattacke am Frankfurter Hauptbahnhof',
    date: '2025-06-15',
    ort: 'Frankfurt am Main, Hessen',
    relevance: 7,
    sourceUrl: 'https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100748324/frankfurt-hauptbahnhof-messer-attacke-18-jaehriger-schwer-verletzt.html',
    sourceName: 't-online',
    lead: 'Auf dem Vorplatz des Frankfurter Hauptbahnhofs wurde ein 18-Jähriger von einer Gruppe niedergestochen — Auslöser war offenbar ein TikTok-Video.',
    body: `Auf dem Vorplatz des Frankfurter Hauptbahnhofs griffen mehrere Männer einen 18-Jährigen an und verletzten ihn schwer durch Messerstiche. Der Jugendliche wurde stationär behandelt. Die polizeilichen Ermittlungen ergaben, dass ein TikTok-Video offenbar den Auslöser für die Auseinandersetzung darstellte. Die strukturelle Anomalie liegt in einem neuartigen Digital-zu-Physisch-Eskalationsmuster: Soziale Medien fungierten als Katalysator für reale Gewalt an einem öffentlichen Verkehrsknotenpunkt. Dieses Phänomen — die Translation von Online-Konflikten in physische Gewalttaten an identifizierbaren öffentlichen Orten — beschreibt eine kriminologisch neue Dimension der Tatanbahnung, in der die digitale Sphäre die Rolle des klassischen Tatvorlaufs übernimmt.`,
  },
  {
    title: 'Sanitäter im Rettungswagen angegriffen in Karlsruhe',
    date: '2025-06-28',
    ort: 'Karlsruhe, Baden-Württemberg',
    relevance: 7,
    sourceUrl: 'https://www.ka-news.de/karlsruhe/polizeibericht-angriff-im-rettungswagen-verletzt-sanitaeter-und-polizist-in-karlsruhe-114589670',
    sourceName: 'ka-news.de',
    lead: 'Ein Patient attackierte während des Transports einen Sanitäter im Inneren des Rettungswagens und verletzte auch einen intervenierenden Polizeibeamten.',
    body: `In Karlsruhe griff ein 58-jähriger Patient kurz vor Erreichen der zentralen Notaufnahme den behandelnden Sanitäter im Inneren des Rettungswagens an und verursachte mehrere Verletzungen. Zusätzlich zerstörte er die Seitenscheibe des Fahrzeugs. Als Polizeibeamte eingriffen, leistete er gewaltsamen Widerstand und verletzte einen Beamten. Er wurde anschließend in eine psychiatrische Einrichtung überwiesen. Die strukturelle Anomalie liegt in der Angriffssituation: Das Innere eines fahrenden Rettungswagens bietet Sanitätern keine Fluchtmöglichkeit und begrenzt die Fähigkeit zur Fixierung gewalttätiger Patienten. Rettungsfahrzeuge sind konstruktionsbedingt für die medizinische Versorgung ausgelegt, nicht für Sicherheit — eine systemische Verwundbarkeit, die Rettungskräfte in einem geschlossenen Raum ohne Rückzugsmöglichkeit exponiert.`,
  },
  {
    title: 'Massenschlägerei bei Kampfsportveranstaltung in Ense',
    date: '2025-08-10',
    ort: 'Ense, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.presseportal.de/blaulicht/pm/65855/6093599',
    sourceName: 'Presseportal / Kreispolizeibehörde Soest',
    lead: 'Bei einer Kampfsportveranstaltung in einer Industriehalle eskalierte ein Fanstreit zu einer Massenschlägerei mit etwa 100 Beteiligten.',
    body: `Bei einer Kampfsportveranstaltung in einer Industriegebiets-Eventhalle in Ense eskalierte ein Streit zwischen Fangruppen zweier Wettkämpfer zu einer Massenschlägerei mit rund 100 Beteiligten. Die Polizei wurde zum Veranstaltungsort gerufen und leitete Ermittlungsverfahren ein. Die strukturelle Anomalie liegt in der Skalierung: Etwa 100 Beteiligte bei einer Zuschauer-Schlägerei überschreiten das für Sportveranstaltungen übliche Maß erheblich. Die Gewalt ging von organisierten Zuschauer-Fraktionen bei einer sanktionierten Kampfsportveranstaltung aus — ein Versagen der Veranstaltungssicherheit bei der Zuschauertrennung. Die Durchführung in einer Industriehalle statt in einer formellen Arena dürfte zu einer reduzierten Crowd-Control-Infrastruktur beigetragen haben.`,
  },
  {
    title: 'Messerattacke an Leipziger Zentralhaltestelle',
    date: '2025-09-01',
    ort: 'Leipzig, Sachsen',
    relevance: 7,
    sourceUrl: 'https://www.blaulicht-ticker.de/leipzig/messerangriff-an-zentralhaltestelle-in-leipzig-am-samstagmorgen-3050290',
    sourceName: 'Blaulicht-Ticker',
    lead: 'An der Zentralhaltestelle direkt vor dem Leipziger Hauptbahnhof wurde ein 40-Jähriger am Samstagmorgen niedergestochen.',
    body: `An der Zentralhaltestelle unmittelbar vor dem Leipziger Hauptbahnhof wurde ein 40-jähriger Mann an einem Samstagmorgen durch Messerstiche verletzt. Die Bundespolizei nahm den Tatverdächtigen in Tatortnähe fest. Der Einzelfall erhält seine strukturelle Bedeutung durch den Kontext: Der Leipziger Hauptbahnhof verzeichnete 2025 mit 859 Gewaltdelikten die höchste Gewaltbelastung aller deutschen Bahnhöfe — ein Anstieg von 609 Fällen im Vorjahr. Die Verlagerung der Tat an die vorgelagerte Straßenbahnhaltestelle zeigt, dass die Gewaltkriminalität nicht auf das Bahnhofsgebäude beschränkt bleibt, sondern in den umgebenden öffentlichen Raum ausstrahlt. Das Muster wiederholter Messervorfälle am selben Verkehrsknoten beschreibt eine lokale Verdichtung, die mit konventionellen Streifenkonzepten nicht aufgefangen werden kann.`,
  },
  {
    title: 'Arzt in Darmstädter Klinikum bewusstlos geschlagen',
    date: '2025-12-14',
    ort: 'Darmstadt, Hessen',
    relevance: 7,
    sourceUrl: 'https://www.hessenschau.de/panorama/mit-kopfverletzungen-auf-intensivstation-mann-attackiert-arzt-im-klinikum-darmstadt-v1,arzt-zusammengeschlagen-100.html',
    sourceName: 'hessenschau',
    lead: 'Ein 55-Jähriger schlug einen diensthabenden Arzt im Klinikum Darmstadt mit Schlägen gegen den Kopf bewusstlos — weil sein Begleiter nicht als Notfall eingestuft wurde.',
    body: `Im Klinikum Darmstadt schlug ein 55-jähriger Mann einen diensthabenden Arzt mit Schlägen gegen den Kopf bewusstlos. Auslöser war die Triage-Entscheidung, seinen Begleiter nicht als Notfall zu behandeln, sondern an einen Facharzt zu überweisen. Der Arzt erlitt Kopfverletzungen und musste intensivmedizinisch behandelt werden. Der Angreifer wurde festgenommen und kam wegen schwerer Körperverletzung in Untersuchungshaft. Die strukturelle Anomalie liegt in der Gewalt gegen medizinisches Personal aufgrund von Triage-Entscheidungen: Ärzte, die als Gatekeeper über den Zugang zur Notfallversorgung entscheiden, werden zum Ziel frustrierter Angehöriger. Das Klinikum überprüfte daraufhin sämtliche Sicherheitsmaßnahmen. Der Fall illustriert die zunehmende Vulnerabilität medizinischer Einrichtungen, in denen klinische Entscheidungen als Ablehnungserfahrung interpretiert werden und Gewalt auslösen.`,
  },
  {
    title: 'Amokfahrt in der Leipziger Grimmaischen Straße',
    date: '2026-05-04',
    ort: 'Leipzig, Sachsen',
    relevance: 8,
    sourceUrl: 'https://de.wikipedia.org/wiki/Amokfahrt_von_Leipzig',
    sourceName: 'Wikipedia',
    lead: 'Ein SUV durchfuhr 450 Meter der Leipziger Fußgängerzone mit geschätzten 70-80 km/h — erst vorhandene Poller in einer Seitenstraße stoppten das Fahrzeug.',
    body: `Am 4. Mai 2026 gegen 16:45 Uhr fuhr ein weißer VW Taigo SUV vom Augustusplatz über die Goethestraße in die Fußgängerzone der Grimmaischen Straße ein und legte mit geschätzten 70 bis 80 km/h etwa 450 Meter zurück — am Markt vorbei und durch die Thomasgasse, bevor eine Pollerreihe das Fahrzeug stoppte. Zwei Menschen wurden getötet und sechs verletzt, zwei davon schwer. Der Fahrer war bis Ende April 2026 freiwillig in psychiatrischer Behandlung gewesen. Ein politisches oder religiöses Motiv wurde nicht festgestellt. Die strukturelle Anomalie offenbart sich in der Infrastruktur: Die Fußgängerzone einer Großstadt verfügte an ihren Einfahrtspunkten über keine Fahrzeugbarrieren. Erst 450 Meter nach dem Einfahrtspunkt stoppten tiefer in der Zone liegende Poller die Fahrt — ein langer, ungeschützter Korridor. Die Stadt installierte zwei Tage später mobile Fahrzeugsperren am Einfahrtspunkt und kündigte eine umfassende Überarbeitung ihres innerstädtischen Sicherheitskonzepts an.`,
  },
  {
    title: 'Freibad-Räumung nach Eskalation in Bochum-Werne',
    date: '2026-06-24',
    ort: 'Bochum-Werne, Nordrhein-Westfalen',
    relevance: 7,
    sourceUrl: 'https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_101312784/freibad-pruegelei-in-bochum-sorgt-fuer-raeumung-grosser-polizei-einsatz.html',
    sourceName: 't-online',
    lead: 'Ein Streit zwischen zwei Badegästen führte zur Räumung von 4.000 Besuchern unter Polizeischutz — am Folgetag wurden in allen Bochumer Bädern Ausweiskontrollen eingeführt.',
    body: `In einem Freibad in Bochum-Werne eskalierte ein Streit zwischen zwei Badegästen. Eine größere Menschenansammlung bildete sich, und parallel entstand ein zweiter separater Konflikt in der Nähe. Der Badbetreiber ordnete die vollständige Räumung aller rund 4.000 Gäste unter Polizeischutz an. Am Folgetag wurden in allen Bochumer Bädern obligatorische Ausweiskontrollen ab 14 Jahren sowie verstärktes Sicherheitspersonal und Taschenkontrollen eingeführt. Die strukturelle Anomalie liegt weniger im Ausgangskonflikt als in der institutionellen Reaktion: Ein relativ geringfügiger Streit löste die Evakuierung von 4.000 Personen aus — eine Reaktionsschwelle, die durch die akkumulierte Muster-Angst aus den Freibad-Gewaltvorfällen der Vorjahre erklärt wird. Die sofortige Einführung von Ausweispflicht und Taschenkontrollen markiert eine rapide Versicherheitlichung ziviler Freizeitinfrastruktur.`,
  },
];

let written = 0;
for (const c of cases) {
  writeItem({
    title: c.title,
    lead: c.lead,
    body: c.body,
    sourceUrl: c.sourceUrl,
    sourceName: c.sourceName,
    relevance: c.relevance,
    date: c.date,
    ort: c.ort,
  });
  written++;
}

const result = build();
console.log(`Nova-Seed abgeschlossen: ${written} Einträge geschrieben, ${result.count} Detailseiten generiert.`);
