window.NOVA_DATA =
{
  "generated": "2026-07-02T00:56:48.359Z",
  "items": [
    {
      "title": "Einzeltäter verletzt dreizehn Polizisten in Berlin-Prenzlauer Berg",
      "date": "2026-06-30",
      "created": "2026-07-01T22:35:00.000Z",
      "slug": "einzeltater-verletzt-dreizehn-polizisten-in-berlin-prenzlauer-berg",
      "lead": "Ein Einzeltäter in Badehose verletzte bei einer Auseinandersetzung in Prenzlauer Berg dreizehn Polizisten und wurde in eine psychiatrische Einrichtung eingewiesen, womit der Fall die Schnittstelle zwischen Gefahrenabwehr und strafrechtlicher Folgenlosigkeit bei psychisch bedingter Gewalt exponiert.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/taser-angedroht-mann-randaliert-in-prenzlauer-berg-13-polizisten-verletzt-15778943.html",
      "ort": "Berlin-Prenzlauer Berg",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/einzeltater-verletzt-dreizehn-polizisten-in-berlin-prenzlauer-berg/"
    },
    {
      "title": "Freibad-Räumung nach Eskalation in Bochum-Werne",
      "date": "2026-06-24",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "freibad-raumung-nach-eskalation-in-bochum-werne",
      "lead": "Die Evakuierung von 4.000 Badegästen nach einem Streit zwischen zwei Personen dokumentiert die akkumulierte institutionelle Angst vor der Wiederholung vergangener Freibad-Eskalationen, deren Reaktionsschwelle den Einzelvorfall längst übersteigt.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_101312784/freibad-pruegelei-in-bochum-sorgt-fuer-raeumung-grosser-polizei-einsatz.html",
      "ort": "Bochum-Werne, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/freibad-raumung-nach-eskalation-in-bochum-werne/"
    },
    {
      "title": "Amokfahrt in der Leipziger Grimmaischen Straße",
      "date": "2026-05-04",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "amokfahrt-in-der-leipziger-grimmaischen-strasse",
      "lead": "Die ungehinderte Durchfahrt über 450 Meter Fußgängerzone bis zum ersten Poller offenbart die Diskrepanz zwischen dem Sicherheitsversprechen autofreier Zonen und ihrer tatsächlichen physischen Schutzinfrastruktur.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_von_Leipzig",
      "ort": "Leipzig, Sachsen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/amokfahrt-in-der-leipziger-grimmaischen-strasse/"
    },
    {
      "title": "Sprengsätze im ICE bei Siegburg",
      "date": "2026-04-02",
      "created": "2026-07-01T21:39:05.032Z",
      "slug": "sprengsatze-im-ice-bei-siegburg",
      "lead": "Der Einsatz zweier improvisierter Sprengsätze im ICE markiert die Eskalation der Schienengewalt vom Nahkampfmittel zum Flächenwirkungsmittel im geschlossenen Hochgeschwindigkeitsraum.",
      "source_name": "t-online Aachen",
      "source_url": "https://aachen.t-online.de/region/aachen/id_101198490/ice-von-aachen-nach-frankfurt-mann-zuendet-sprengstoff-zwoelf-verletzte.html",
      "ort": "Siegburg, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/sprengsatze-im-ice-bei-siegburg/"
    },
    {
      "title": "Mehrfach-Messerangriff im Schienenersatzverkehr in Wuppertal",
      "date": "2026-02-14",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "mehrfach-messerangriff-im-schienenersatzverkehr-in-wuppertal",
      "lead": "Der Mehrfach-Messerangriff in einem provisorischen Schienenersatzverkehr-Bus offenbart die besondere Vulnerabilität temporärer Transportinfrastruktur, die als Gefährdungsraum weder konzipiert noch gesichert ist.",
      "source_name": "Westdeutsche Zeitung",
      "source_url": "https://www.wz.de/nrw/wuppertal/wuppertal-messerstecher-verletzt-mehrere-fahrgaeste-im-schienenersatzverkehr_aid-143882291",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/mehrfach-messerangriff-im-schienenersatzverkehr-in-wuppertal/"
    },
    {
      "title": "Tödlicher Angriff auf Zugbegleiter bei Fahrkartenkontrolle",
      "date": "2026-02-03",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "todlicher-angriff-auf-zugbegleiter-bei-fahrkartenkontrolle",
      "lead": "Die Tötung eines Zugbegleiters durch Faustschläge bei einer routinemäßigen Fahrkartenkontrolle verschiebt die Gewaltschwelle im Schienenverkehr von der Verletzung zur Tötung im banalsten denkbaren Anlasskontext.",
      "source_name": "Homburg1",
      "source_url": "https://homburg1.de/eskalation-bei-fahrkartenkontrolle-zugbegleiter-in-lebensgefahr-237815/",
      "ort": "Landstuhl / Homburg, Rheinland-Pfalz",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/todlicher-angriff-auf-zugbegleiter-bei-fahrkartenkontrolle/"
    },
    {
      "title": "Silvester-Eskalation gegen Einsatzkräfte in mehreren Großstädten",
      "date": "2025-12-31",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "silvester-eskalation-gegen-einsatzkrafte-in-mehreren-grossstadten",
      "lead": "Die gleichzeitige Attacke auf Rettungsmittel und deren erzwungene Nutzung durch dieselbe Gruppe beschreibt eine Eskalationsstufe, in der Rettungsinfrastruktur simultan bekämpft und instrumentalisiert wird.",
      "source_name": "t-online / Tagesspiegel / komba NRW",
      "source_url": "https://frankfurt.t-online.de/region/frankfurt-am-main/id_101064410/frankfurt-sanitaeter-in-silvesternacht-angegriffen-und-verletzt.html",
      "ort": "Frankfurt, Berlin, Duisburg, Leipzig",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/silvester-eskalation-gegen-einsatzkrafte-in-mehreren-grossstadten/"
    },
    {
      "title": "Arzt in Darmstädter Klinikum bewusstlos geschlagen",
      "date": "2025-12-14",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "arzt-in-darmstadter-klinikum-bewusstlos-geschlagen",
      "lead": "Die Eskalation einer korrekt ausgeführten Triage-Entscheidung zur Schwerstgewalt gegen den behandelnden Arzt markiert den Punkt, an dem medizinische Gatekeeping-Funktionen selbst zur Angriffsursache werden.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/mit-kopfverletzungen-auf-intensivstation-mann-attackiert-arzt-im-klinikum-darmstadt-v1,arzt-zusammengeschlagen-100.html",
      "ort": "Darmstadt, Hessen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/arzt-in-darmstadter-klinikum-bewusstlos-geschlagen/"
    },
    {
      "title": "Machetenangriff auf Kioskbetreiber durch Dreizehnjährige in Dortmund",
      "date": "2025-11-29",
      "created": "2026-07-01T23:00:00.000Z",
      "slug": "machetenangriff-auf-kioskbetreiber-durch-dreizehnjaehrige-in-dortmund",
      "lead": "Zwei Dreizehnjährige überfielen einen Kioskbetreiber mit Machete, Pfefferspray und Schusswaffe, trennten ihm den Daumen ab und blieben strafrechtlich folgenlos, weil das Waffenarsenal das Strafmündigkeitsalter nicht verschiebt.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_101025958/dortmund-13-jaehrige-hat-wohl-kioskbetreiber-mit-machete-daumen-abgehackt-.html",
      "ort": "Dortmund-Nordstadt, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/machetenangriff-auf-kioskbetreiber-durch-dreizehnjaehrige-in-dortmund/"
    },
    {
      "title": "Freispruch im Eiskeller-Fall nach fatalen Ermittlungsfehlern in Aschau",
      "date": "2025-11-25",
      "created": "2026-07-02T01:30:00.000Z",
      "slug": "freispruch-im-eiskeller-fall-nach-fatalen-ermittlungsfehlern-in-aschau",
      "lead": "Der zweite Freispruch im Aschauer Eiskeller-Verfahren, bei dem die Staatsanwaltschaft selbst die Freisprechung beantragte, weil die Ermittlungsarbeit 'zahlreiche fatale Fehler' aufwies, dokumentiert den seltenen Fall einer Justiz, die ihr eigenes Versagen einräumt, nachdem ein Angeklagter zwei Jahre unschuldig in Haft saß.",
      "source_name": "Legal Tribune Online",
      "source_url": "https://www.lto.de/recht/nachrichten/n/402js4027622jug-lg-traunstein-eiskeller-mord-hanna",
      "ort": "Aschau im Chiemgau, Bayern",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/freispruch-im-eiskeller-fall-nach-fatalen-ermittlungsfehlern-in-aschau/"
    },
    {
      "title": "Dreizehnjähriger schlägt Rentner auf Essener Spielplatz tot",
      "date": "2025-11-03",
      "created": "2026-07-01T22:42:00.000Z",
      "slug": "dreizehnjahriger-schlagt-rentner-auf-essener-spielplatz-tot",
      "lead": "Die tödliche Gewalt eines Dreizehnjährigen gegen einen 80-jährigen Rentner auf einem Spielplatz, gefolgt von der Übergabe des Täters an die Eltern als maximaler staatlicher Reaktion, legt die absolute Grenze des Strafrechts bei Tötungsdelikten durch strafunmündige Kinder frei.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/polizei-ermittelt-81-jaehriger-stirbt-nach-mutmasslichem-angriff-durch-jugendliche-auf-spielplatz-15110459.html",
      "ort": "Essen, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/dreizehnjahriger-schlagt-rentner-auf-essener-spielplatz-tot/"
    },
    {
      "title": "Systematische Gefangenenmisshandlung im Frankfurter Polizeirevier",
      "date": "2025-10-10",
      "created": "2026-07-02T01:30:00.000Z",
      "slug": "systematische-gefangenenmisshandlung-im-frankfurter-polizeirevier",
      "lead": "Im selben Frankfurter Polizeirevier, das zuvor durch eine jahrelang betriebene rechtsextreme Chatgruppe auffiel, werden nun 20 Beamte wegen systematischer Misshandlung von mindestens sechs Festgenommenen ermittelt, wobei die institutionelle Wiederholung die Frage aufwirft, warum der erste Skandal keine strukturellen Reformen auslöste.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/ermittlungen-gegen-17-polizisten-in-frankfurt-wegen-polizeigewalt-v11,durchsuchung-polizisten-100.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/systematische-gefangenenmisshandlung-im-frankfurter-polizeirevier/"
    },
    {
      "title": "Fahrzeug-Angriff auf Kirmes-Besucher in Niederdorla",
      "date": "2025-09-21",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "fahrzeug-angriff-auf-kirmes-besucher-in-niederdorla",
      "lead": "Die Übertragung des terroristisch codierten Fahrzeugangriff-Musters auf ein ungesichertes Dorffest offenbart die räumliche Entgrenzung einer Tatform, die bislang urbane Hochsicherheitsereignisse definierte.",
      "source_name": "t-online.de",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100923892/niederdorla-in-thueringen-mann-faehrt-mit-pick-up-truck-in-kirmes-verletzte.html",
      "ort": "Niederdorla, Thüringen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/fahrzeug-angriff-auf-kirmes-besucher-in-niederdorla/"
    },
    {
      "title": "Messerattacke an Leipziger Zentralhaltestelle",
      "date": "2025-09-01",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "messerattacke-an-leipziger-zentralhaltestelle",
      "lead": "Die Verlagerung der Messergewalt vom Leipziger Hauptbahnhof — 2025 mit 859 Gewaltdelikten der belastetste Bahnhof Deutschlands — an die vorgelagerte Straßenbahnhaltestelle zeigt die räumliche Ausstrahlung eines Gewalthotspots über Gebäudegrenzen hinaus.",
      "source_name": "Blaulicht-Ticker",
      "source_url": "https://www.blaulicht-ticker.de/leipzig/messerangriff-an-zentralhaltestelle-in-leipzig-am-samstagmorgen-3050290",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerattacke-an-leipziger-zentralhaltestelle/"
    },
    {
      "title": "Messerangriff auf Zivilcourage-Helfer in Dresdner Straßenbahn",
      "date": "2025-08-24",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "messerangriff-auf-zivilcourage-helfer-in-dresdner-strassenbahn",
      "lead": "Der Messerangriff auf einen 20-Jährigen, der belästigte Frauen in einer Straßenbahn verteidigte, und die sofortige Freilassung des Tatverdächtigen dokumentieren eine doppelte Sanktionierung der Zivilcourage — durch die Tat und durch die institutionelle Reaktion.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdfheute.de/panorama/messerattacke-dresden-strassenbahn-opfer-jonathan-rudat-spricht-100.html",
      "ort": "Dresden, Sachsen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-zivilcourage-helfer-in-dresdner-strassenbahn/"
    },
    {
      "title": "Massenschlägerei bei Kampfsportveranstaltung in Ense",
      "date": "2025-08-10",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "massenschlagerei-bei-kampfsportveranstaltung-in-ense",
      "lead": "Eine Kampfsportveranstaltung in einer Industriehalle ohne formale Crowd-Control-Infrastruktur ließ die sanktionierte Gewalt im Ring in eine unkontrollierte Massenschlägerei mit rund 100 Beteiligten auf den Rängen kippen.",
      "source_name": "Presseportal / Kreispolizeibehörde Soest",
      "source_url": "https://www.presseportal.de/blaulicht/pm/65855/6093599",
      "ort": "Ense, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenschlagerei-bei-kampfsportveranstaltung-in-ense/"
    },
    {
      "title": "Femizid trotz Fußfessel in Frankfurt-Bonames",
      "date": "2025-07-02",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "femizid-trotz-fussfessel-in-frankfurt-bonames",
      "lead": "Die GPS-Fußfessel lief neun Tage vor dem Tötungsdelikt durch Erreichen der gesetzlichen Höchstfrist aus — das Schutzinstrument wurde durch sein eigenes Verfallsdatum wirkungslos, während die Gefährdung fortbestand.",
      "source_name": "hessenschau.de",
      "source_url": "https://www.hessenschau.de/panorama/messerangriff-in-frankfurt-mutmasslicher-moerder-trug-bis-vor-kurzem-fussfessel-v2,mann-stirbt-frankfurt-mordverdacht-100.html",
      "ort": "Frankfurt-Bonames, Hessen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/femizid-trotz-fussfessel-in-frankfurt-bonames/"
    },
    {
      "title": "Sanitäter im Rettungswagen angegriffen in Karlsruhe",
      "date": "2025-06-28",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "sanitater-im-rettungswagen-angegriffen-in-karlsruhe",
      "lead": "Das Innere eines fahrenden Rettungswagens exponiert Sanitäter in einem Raum, der konstruktionsbedingt für Versorgung, nicht für Sicherheit ausgelegt ist — eine systemische Verwundbarkeit ohne Flucht- oder Fixierungsoption.",
      "source_name": "ka-news.de",
      "source_url": "https://www.ka-news.de/karlsruhe/polizeibericht-angriff-im-rettungswagen-verletzt-sanitaeter-und-polizist-in-karlsruhe-114589670",
      "ort": "Karlsruhe, Baden-Württemberg",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/sanitater-im-rettungswagen-angegriffen-in-karlsruhe/"
    },
    {
      "title": "Soziale-Medien-getriggerte Messerattacke am Frankfurter Hauptbahnhof",
      "date": "2025-06-15",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof",
      "lead": "Die Übernahme des klassischen Tatvorlaufs durch ein TikTok-Video beschreibt ein Eskalationsmuster, bei dem die Gewalt sich ohne physische Vorgeschichte an einem öffentlichen Verkehrsknotenpunkt materialisiert.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100748324/frankfurt-hauptbahnhof-messer-attacke-18-jaehriger-schwer-verletzt.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof/"
    },
    {
      "title": "Bewährungsstrafen für Gruppenvergewaltigung durch Verständigungsdeal in Fulda",
      "date": "2025-06-15",
      "created": "2026-07-02T01:30:00.000Z",
      "slug": "bewaehrungsstrafen-fuer-gruppenvergewaltigung-durch-verstaendigungsdeal-in-fulda",
      "lead": "Vier Täter wurden sechs Jahre nach der mehrfachen Vergewaltigung einer bewusstlosen Frau durch einen Verständigungsdeal zu Bewährungsstrafen verurteilt, wobei der Deal den Geständnissen einen Strafrahmen gegenüberstellte, der das Tatunrecht auf das Niveau eines schweren Diebstahls reduzierte.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/frau-mehrfach-vergewaltigt-vier-maenner-zu-bewaehrungsstrafe-verurteilt-v1,urteil-vergewaltigungen-100.html",
      "ort": "Fulda, Hessen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/bewaehrungsstrafen-fuer-gruppenvergewaltigung-durch-verstaendigungsdeal-in-fulda/"
    },
    {
      "title": "Massenconfrontation mit Waffenarsenal in Dortmund-Nordstadt",
      "date": "2025-05-26",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt",
      "lead": "Die Kaskade vom interpersonellen Streit zweier Gruppen zur Massenkonfrontation mit 250 bis 300 Beteiligten und einem Waffenarsenal vom Messer bis zur Schusswaffe beschreibt eine Eskalationsgeschwindigkeit, die konventionelle Einsatzkonzepte strukturell unterläuft.",
      "source_name": "Rundblick Unna",
      "source_url": "https://rundblick-unna.de/2026/05/27/gewalteskalation-in-do-nord-mit-messern-machete-axt-schusswaffe-sieben-beteiligte-mehrere-hundert-gaffer/",
      "ort": "Dortmund-Nordstadt, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt/"
    },
    {
      "title": "Massenangriff am Hamburger Hauptbahnhof",
      "date": "2025-05-23",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenangriff-am-hamburger-hauptbahnhof",
      "lead": "32 stationäre psychiatrische Aufnahmen in drei Jahren ohne dauerhafte Unterbringung verwandelten die Akutversorgung in ein Drehtür-System, dessen Entlasslogik die Gewalteskalation am Hauptbahnhof zur dokumentierten Konsequenz machte.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_am_Hamburger_Hauptbahnhof_2025",
      "ort": "Hamburg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenangriff-am-hamburger-hauptbahnhof/"
    },
    {
      "title": "Elfjährige Schülerin ersticht Mitschüler in Remscheid",
      "date": "2025-05-22",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "elfjahrige-schulerin-ersticht-mitschuler-in-remscheid",
      "lead": "Das extreme Alter des Angreifers — elf Jahre, drei Jahre unterhalb der Strafmündigkeitsgrenze — exponiert eine systemische Lücke, die das deutsche Strafrecht für Gewaltdelikte durch Kinder ohne strafrechtliche Konsequenz lässt.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/nach-messerangriff-auf-13-jahrigen-polizei-in-remscheid-ubergibt-11-jahrigen-wieder-den-eltern-13740730.html",
      "ort": "Remscheid, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/elfjahrige-schulerin-ersticht-mitschuler-in-remscheid/"
    },
    {
      "title": "Islamistischer Anschlag mit verkleideter Stockwaffe in Bielefeld",
      "date": "2025-05-18",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld",
      "lead": "Die Kombination aus getarnter Waffe und simulierter Gehbehinderung als Annäherungstaktik markiert einen Innovationssprung in der islamistischen Tatbegehung, der in der deutschen Kriminalgeschichte ohne Vorbild ist.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Bielefeld_2025",
      "ort": "Bielefeld, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld/"
    },
    {
      "title": "Messerangriff auf Supermarkt-Kundin nach Hausverbot in Rochlitz",
      "date": "2025-04-17",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "messerangriff-auf-supermarkt-kundin-nach-hausverbot-in-rochlitz",
      "lead": "Die Zielverschiebung — nicht das Personal, das das Hausverbot erteilte, wird attackiert, sondern eine unbeteiligte Kundin — dokumentiert ein Muster verschobener Aggression, bei dem Frustrations-Auslöser und Gewalt-Ziel auseinanderfallen.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/vorfall-im-sachsischen-rochlitz-zwei-menschen-bei-messerangriff-vor-supermarkt-schwer-verletzt-13561288.html",
      "ort": "Rochlitz, Sachsen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-supermarkt-kundin-nach-hausverbot-in-rochlitz/"
    },
    {
      "title": "Tödliche Messerattacke an U-Bahnhof Sophie-Charlotte-Platz",
      "date": "2025-04-12",
      "created": "2026-07-01T21:39:05.025Z",
      "slug": "todliche-messerattacke-an-u-bahnhof-sophie-charlotte-platz",
      "lead": "Ein nicht vollstreckter Haftbefehl, der über drei Monate zwischen zwei Bundesländern unterwegs war, verwandelt ein administratives Versäumnis in die Ermöglichungsstruktur eines Tötungsdelikts.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/todlicher-messerangriff-in-berliner-u-bahn-shadi-s-hatte-langst-in-haft-sitzen-mussen-13549201.html",
      "ort": "Berlin-Charlottenburg",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/todliche-messerattacke-an-u-bahnhof-sophie-charlotte-platz/"
    },
    {
      "title": "Messerattacke in Berliner Straßenbahn am Alexanderplatz",
      "date": "2025-04-10",
      "created": "2026-07-01T21:39:05.022Z",
      "slug": "messerattacke-in-berliner-strassenbahn-am-alexanderplatz",
      "lead": "Das Verweilzeitenmuster des Angreifers — Zustieg an einer vorherigen Haltestelle, Verzögerung, Angriff im Moment des Ausstiegs — verwandelt die Transitsequenz des öffentlichen Nahverkehrs in eine taktische Angriffsstruktur.",
      "source_name": "Polizei Berlin",
      "source_url": "https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1550558.php",
      "ort": "Berlin-Mitte",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerattacke-in-berliner-strassenbahn-am-alexanderplatz/"
    },
    {
      "title": "Messerattacke auf Bahnsteig des Frankfurter Hauptbahnhofs",
      "date": "2025-03-15",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs",
      "lead": "Die Konzentration mehrerer Messervorfälle am selben Verkehrsknoten innerhalb eines Jahres erzwingt eine institutionelle Reaktion, die konventionelle Polizeiarbeit übersteigt und eine Mehrakteurs-Sicherheitsarchitektur begründet.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/messerangriff-am-gleis-im-frankfurter-hauptbahnhof-v1,kurz-angriff-324.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs/"
    },
    {
      "title": "Messerangriff auf Lebensmittelkontrolleure in Gelsenkirchen",
      "date": "2025-03-12",
      "created": "2026-07-01T21:39:05.022Z",
      "slug": "messerangriff-auf-lebensmittelkontrolleure-in-gelsenkirchen",
      "lead": "Die Opferkategorie — kommunale Verwaltungsangestellte bei einer administrativen Routinehandlung — verschiebt die Messergewalt in den Bereich systemischer Aggression gegen niedrigstufige staatliche Kontrollfunktionen.",
      "source_name": "Polizei Gelsenkirchen / Staatsanwaltschaft Essen",
      "source_url": "https://gelsenkirchen.polizei.nrw/presse/gemeinsame-pressemitteilung-der-staatsanwaltschaft-essen-und-der-polizei-gelsenkirchen-versuchtes-toetungsdelikt-bei-lebensmittelkontrolle-in-horst",
      "ort": "Gelsenkirchen-Horst, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-lebensmittelkontrolleure-in-gelsenkirchen/"
    },
    {
      "title": "Messerangriff auf DB-Mitarbeiter am Dortmunder Hauptbahnhof",
      "date": "2025-03-06",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "messerangriff-auf-db-mitarbeiter-am-dortmunder-hauptbahnhof",
      "lead": "Die einstündige Verzögerung zwischen Bagatellkonflikt und gezielter Rückkehr transformiert eine Serviceschalter-Interaktion in ein Vergeltungsdelikt mit dokumentiertem Vorsatz.",
      "source_name": "Polizei Dortmund",
      "source_url": "https://dortmund.polizei.nrw/presse/22-jaehriger-sticht-mit-einem-messer-auf-einen-mitarbeiter-im-hauptbahnhof-dortmund-ein-polizei-nimmt-tatverdaechtigen-fest",
      "ort": "Dortmund, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-db-mitarbeiter-am-dortmunder-hauptbahnhof/"
    },
    {
      "title": "Fahrzeugangriff auf Fastnachtsmarkt in Mannheim",
      "date": "2025-03-03",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim",
      "lead": "Der Anschlag demonstriert, dass die nach 2016 entwickelten Schutzkonzepte für Weihnachtsmärkte nicht auf andere saisonale Großveranstaltungen übertragen wurden — die Fastnacht fiel durch das Raster einer Sicherheitsarchitektur, die nur den Anlass des letzten Anschlags schützt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_in_Mannheim_2025",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim/"
    },
    {
      "title": "Messerangriff auf Grundschulkinder in Duisburg-Marxloh",
      "date": "2025-02-28",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-grundschulkinder-in-duisburg-marxloh",
      "lead": "Die familieninterne Überwältigung des Angreifers durch seinen eigenen Vater wirft die Frage auf, welches Wissen über die Gefährlichkeit innerhalb des familiären Umfelds existierte — und warum es nicht vor der Tat zu einer Intervention führte.",
      "source_name": "Ruhr Nachrichten",
      "source_url": "https://www.ruhrnachrichten.de/regionales/messerangriff-in-duisburg-zwei-kinder-schwer-verletzt-21-jaehriger-festgenommen-w849734-2001123189/",
      "ort": "Duisburg-Marxloh, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-grundschulkinder-in-duisburg-marxloh/"
    },
    {
      "title": "Fahrzeugangriff auf Gewerkschaftsdemonstration in München",
      "date": "2025-02-13",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen",
      "lead": "Der Angriff auf einen sich bewegenden Demonstrationszug offenbart eine prinzipielle Schutzlücke — dynamische Versammlungen auf Straßen lassen sich nicht durch Fahrzeugbarrieren sichern, was das Versammlungsrecht in seiner physischen Dimension ungeschützt lässt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_in_M%C3%BCnchen_2025",
      "ort": "München, Bayern",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen/"
    },
    {
      "title": "Messerangriff auf Jugendlichen an Bushaltestelle in Erfurt",
      "date": "2025-02-02",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "messerangriff-auf-jugendlichen-an-bushaltestelle-in-erfurt",
      "lead": "Die Tat markiert die Verschiebung lebensbedrohlicher Messergewalt in ein Alter, in dem das Strafrecht kaum Instrumente zur Gefahrenabwehr bereithält — und die Freilassung des Tatverdächtigen trotz beinahe tödlicher Verletzungen dokumentiert die Grenzen des Jugendstrafrechts.",
      "source_name": "NIUS",
      "source_url": "https://www.nius.de/kriminalitaet/news/erfurt-messerattacke-14-jaehriger-16-jaehriger-not-operation-bushaltestelle-vieselbach/1dba3f91-fa84-4af0-a23a-c00e098a892b",
      "ort": "Erfurt-Vieselbach, Thüringen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-jugendlichen-an-bushaltestelle-in-erfurt/"
    },
    {
      "title": "Messerattacke am Leipziger Hauptbahnhof",
      "date": "2025-01-30",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-am-leipziger-hauptbahnhof",
      "lead": "Nicht die Einzeltat, sondern ihr Ort definiert die Anomalie — der Leipziger Hauptbahnhof, 2025 der gewaltbelastetste Bahnhof Deutschlands, in dem Messergewalt zur statistischen Erwartbarkeit geworden ist.",
      "source_name": "Presseportal / Bundespolizei",
      "source_url": "https://www.presseportal.de/blaulicht/pm/74165/5979744",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerattacke-am-leipziger-hauptbahnhof/"
    },
    {
      "title": "Messerangriff auf Kindergartengruppe im Aschaffenburger Schöntal-Park",
      "date": "2025-01-22",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park",
      "lead": "Trotz abgelehntem Asylantrag, gescheiterter Abschiebung, dokumentierter Gewaltbereitschaft und psychiatrischer Diagnose fiel der Angreifer durch sämtliche institutionellen Sicherungsnetze — der Fall dokumentiert kumulatives Behördenversagen über mindestens drei Zuständigkeitsbereiche.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/aschaffenburg-messerangriff-chronologie-behoerden-100.html",
      "ort": "Aschaffenburg, Bayern",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park/"
    },
    {
      "title": "Silvester-Angriffe auf Rettungskräfte in Berlin und Leipzig",
      "date": "2024-12-31",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig",
      "lead": "Die koordinierte Gewalt gegen Rettungskräfte in der Silvesternacht erzwingt den taktischen Rückzug kombinierter Feuerwehr-Polizei-Einheiten — ein struktureller Bruch im staatlichen Gewaltmonopol, der durch seine jährliche Wiederkehr zur erwartbaren Anomalie geworden ist.",
      "source_name": "Polizei Berlin",
      "source_url": "https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1517844.php",
      "ort": "Berlin und Leipzig",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig/"
    },
    {
      "title": "Fahrzeuganschlag auf den Magdeburger Weihnachtsmarkt",
      "date": "2024-12-20",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt",
      "lead": "Der Anschlag offenbart das Paradox einer Sicherheitsarchitektur, die auf dem Papier vollständig existierte und an zwei banalen Implementierungsfehlern — einer nicht gespannten Kette und einem falsch positionierten Polizeifahrzeug — in der physischen Realität scheiterte.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_auf_den_Magdeburger_Weihnachtsmarkt",
      "ort": "Magdeburg, Sachsen-Anhalt",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt/"
    },
    {
      "title": "Bewaffnete Massenschlägerei in Mockrehna",
      "date": "2024-10-25",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "bewaffnete-massenschlagerei-in-mockrehna",
      "lead": "Die Vorausrüstung zweier Gruppen mit improvisierten Waffen in einer Gemeinde mit weniger als 5.000 Einwohnern erzeugt eine Gewaltkonzentration, die lokale Sicherheitsstrukturen überfordert und eine behördenübergreifende Polizeioperation erzwingt.",
      "source_name": "MS Aktuell",
      "source_url": "https://ms-aktuell.de/welt/massenschlaegerei-mockrehna-polizeieinsatz-verletzte/",
      "ort": "Mockrehna, Nordsachsen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/bewaffnete-massenschlagerei-in-mockrehna/"
    },
    {
      "title": "Systematische Gefangenenmisshandlung in der JVA Augsburg-Gablingen",
      "date": "2024-10-24",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "systematische-gefangenenmisshandlung-in-der-jva-augsburg-gablingen",
      "lead": "Die stellvertretende Leiterin der JVA Augsburg-Gablingen etablierte über 22 Monate ein systematisches Misshandlungsregime mit 131 dokumentierten Fällen von rechtswidriger Isolierung, Körperverletzung und Nötigung durch die Sicherungsabteilung, wobei die Razzia am 24. Oktober 2024 den seltenen Fall einer Institution offenlegte, die selbst zum Tatort organisierter staatlicher Gewalt wurde.",
      "source_name": "Bayerisches Staatsministerium der Justiz",
      "source_url": "https://www.justiz.bayern.de/presse-und-medien/pressemitteilungen/archiv/2024/156.php",
      "ort": "Augsburg-Gablingen, Bayern",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/systematische-gefangenenmisshandlung-in-der-jva-augsburg-gablingen/"
    },
    {
      "title": "Messerangriff mit Selbstjustiz-Verfolgung in Duisburg",
      "date": "2024-10-24",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "messerangriff-mit-selbstjustiz-verfolgung-in-duisburg",
      "lead": "Die unmittelbare Abfolge von Messerangriff, Kfz-Verfolgungsjagd und gruppenbasierter Vergeltung mit Holzlatten verdichtet ein komplettes Selbstjustizszenario in wenige Minuten Echtzeit.",
      "source_name": "Presseportal / Polizei Duisburg",
      "source_url": "https://www.presseportal.de/blaulicht/pm/50510/5897629",
      "ort": "Duisburg, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-mit-selbstjustiz-verfolgung-in-duisburg/"
    },
    {
      "title": "Gruppenangriff auf Klinikpersonal nach Todesfall in Essener Notaufnahme",
      "date": "2024-09-20",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "gruppenangriff-auf-klinikpersonal-nach-todesfall-in-essener-notaufnahme",
      "lead": "Die koordinierte Erstürmung eines Behandlungsraums durch Angehörige, ausgelöst nicht durch wahrgenommene Fehlbehandlung, sondern durch den Tod selbst, erzwingt die bauliche Aufrüstung einer Notaufnahme gegen ihre eigenen Besucher.",
      "source_name": "ZDF Nachrichten",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/essen-krankenhaus-besucher-mitarbeiter-angriff-verletzte-100.html",
      "ort": "Essen-Huttrop, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/gruppenangriff-auf-klinikpersonal-nach-todesfall-in-essener-notaufnahme/"
    },
    {
      "title": "Evakuierung des Thüringen-Parks nach Messer- und Pfefferspray-Angriff",
      "date": "2024-09-19",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "evakuierung-des-thuringen-parks-nach-messer-und-pfefferspray-angriff",
      "lead": "Der kombinierte Einsatz von Messer und Pfefferspray in einem geschlossenen Einkaufszentrum erzeugt aus einer gezielten Einzeltat ein Flächenereignis, das die Evakuierung des gesamten Gebäudekomplexes erzwingt.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100493332/thueringen-park-in-erfurt-einkaufszentrum-nach-angriff-evakuiert.html",
      "ort": "Erfurt, Thüringen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/evakuierung-des-thuringen-parks-nach-messer-und-pfefferspray-angriff/"
    },
    {
      "title": "Säureattacke auf Nachbarn in Stralsund",
      "date": "2024-09-12",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "saureattacke-auf-nachbarn-in-stralsund",
      "lead": "Säure als Tatmittel in einem Nachbarschaftskonflikt markiert eine qualitative Eskalation, die konventionelle Gewaltkategorien verlässt und in die Logik chemischer Kampfstoffe eintritt.",
      "source_name": "t-online.de",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100488522/stralsund-saeure-attacke-opfer-schwebt-in-lebensgefahr.html",
      "ort": "Stralsund, Mecklenburg-Vorpommern",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/saureattacke-auf-nachbarn-in-stralsund/"
    },
    {
      "title": "Hochzeitsfeier endet in Massenschlägerei mit Messereinsatz in Wuppertal",
      "date": "2024-08-31",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "hochzeitsfeier-endet-in-massenschlagerei-mit-messereinsatz-in-wuppertal",
      "lead": "Der Übergang von einer Hochzeitsfeier zu einer bewaffneten Konfrontation mit der Polizei, die den Einsatz eines Tasers gegen einen Messerangreifer erzwingt, sprengt jedes konventionelle Einsatzszenario für Ruhestörungen.",
      "source_name": "Wuppertaler Rundschau",
      "source_url": "https://www.wuppertaler-rundschau.de/stadtteile/suedstadt/hochzeitsfeier-in-wuppertal-endet-mit-massenschlaegerei_aid-118512017",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/hochzeitsfeier-endet-in-massenschlagerei-mit-messereinsatz-in-wuppertal/"
    },
    {
      "title": "Terroranschlag auf dem Solinger Stadtfest",
      "date": "2024-08-23",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-dem-solinger-stadtfest",
      "lead": "Ein kommunales Stadtfest als islamistisches Anschlagsziel offenbart eine doppelte Systemlücke — in der Bedrohungsanalyse für Soft Targets und im Dublin-Überstellungsverfahren, dessen bürokratisches Versagen die Tat erst ermöglichte.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messeranschlag_in_Solingen",
      "ort": "Solingen, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-dem-solinger-stadtfest/"
    },
    {
      "title": "Geiselnahme und Massenausbruch aus der Forensik Straubing",
      "date": "2024-08-17",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "geiselnahme-und-massenausbruch-aus-der-forensik-straubing",
      "lead": "Vier Straftäter überwältigten und misshandelten einen Mitarbeiter des geschlossenen Bezirkskrankenhauses Straubing, bedrohten ihn mit einer Scherbe am Hals und flohen aus der forensischen Psychiatrie, wobei zwei erst Wochen später in Österreich und der Türkei gefasst wurden und der Fall die grundlegende Sicherheitsarchitektur forensischer Kliniken in Frage stellte.",
      "source_name": "inFranken",
      "source_url": "https://www.infranken.de/bayern/anklage-geiselnahme-bezirkskrankenhaus-flucht-psychatrie-straubing-sicherheitskonzepte-therapie-straftaeter-art-5910006",
      "ort": "Straubing, Bayern",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/geiselnahme-und-massenausbruch-aus-der-forensik-straubing/"
    },
    {
      "title": "Massenschlägerei mit improvisierten Waffen bei Hochzeit in Schleswig",
      "date": "2024-08-12",
      "created": "2026-07-01T21:39:05.019Z",
      "slug": "massenschlagerei-mit-improvisierten-waffen-bei-hochzeit-in-schleswig",
      "lead": "Die Bandbreite der improvisierten Bewaffnung — Schaufeln, Fahrradschläuche, Baseballschläger — bei einer Hochzeitsfeier mit 60 Kombattanten verschiebt das Tatmuster von spontaner Eskalation zu koordinierter Gruppenkonfrontation.",
      "source_name": "foerde.news",
      "source_url": "https://www.foerde.news/blaulicht/nach-massenschlaegerei-mit-rund-60-beteiligten-personen-im-kattenhunder-weg-polizei-ermittelt.html",
      "ort": "Schleswig, Schleswig-Holstein",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenschlagerei-mit-improvisierten-waffen-bei-hochzeit-in-schleswig/"
    },
    {
      "title": "Axt- und Hammerangriff im ICE bei Straßkirchen",
      "date": "2024-08-08",
      "created": "2026-07-01T21:39:05.019Z",
      "slug": "axt-und-hammerangriff-im-ice-bei-strasskirchen",
      "lead": "Der Einsatz von Hammer und Axt in einem voll besetzten Hochgeschwindigkeitszug mit 430 eingeschlossenen Fahrgästen überschreitet die bisherige Messer-Phänomenologie der Schienengewalt qualitativ und exponiert die infrastrukturelle Verwundbarkeit des Fernverkehrs.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdfheute.de/panorama/kriminalitaet/angriff-ice-bahn-bayern-verletzte-100.html",
      "ort": "Straßkirchen, Niederbayern",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/axt-und-hammerangriff-im-ice-bei-strasskirchen/"
    },
    {
      "title": "Kaskadierende Gewalt im Dortmunder Freibad Volkspark",
      "date": "2024-08-06",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "kaskadierende-gewalt-im-dortmunder-freibad-volkspark",
      "lead": "Vier räumlich und deliktisch getrennte Gewaltakte — Schlägerei, sexuelle Nötigung, Familiengewalt, Straßenschlacht — verketten sich über einen Sommerabend hinweg zu einer sich selbst verstärkenden Eskalationskaskade vom Freibad in den Stadtraum.",
      "source_name": "Ruhr Nachrichten",
      "source_url": "https://www.ruhrnachrichten.de/dortmund/polizeieinsatz-im-freibad-am-bvb-stadion-notruf-wegen-schlaegerei-w919892-2001318169/",
      "ort": "Dortmund, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/kaskadierende-gewalt-im-dortmunder-freibad-volkspark/"
    },
    {
      "title": "Serielle Fahrzeugangriffe auf Frauen in Essen und Köln",
      "date": "2024-08-05",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln",
      "lead": "Ein lizenziertes Taxi als Tatwaffe gegen ausschließlich weibliche Opfer in zwei Großstädten am selben Abend erzeugt ein Tatmuster, das in der deutschen Kriminalgeschichte ohne dokumentierte Parallele ist.",
      "source_name": "Taxi Times",
      "source_url": "https://taxi-times.com/taxifahrer-faehrt-passantinnen-in-essen-und-koeln-an-das-geschah-wirklich/",
      "ort": "Essen und Köln, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln/"
    },
    {
      "title": "Femizid in Berlin-Friedrichsfelde trotz behördlicher Hilfesuche",
      "date": "2024-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche",
      "lead": "Die Tötung einer 28-jährigen Frau, die zuvor behördlichen Schutz gesucht hatte, dokumentiert das strukturelle Versagen der institutionellen Schutzinstrumente bei Hochrisikofällen häuslicher Gewalt.",
      "source_name": "One Billion Rising Deutschland",
      "source_url": "https://www.onebillionrising.de/femizid-opfer-meldungen-2024/",
      "ort": "Berlin-Friedrichsfelde",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche/"
    },
    {
      "title": "Gruppengewalt gegen Jugendliche im Berliner Sommerbad",
      "date": "2024-07-06",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "gruppengewalt-gegen-jugendliche-im-berliner-sommerbad",
      "lead": "Ein asymmetrisches Zahlenverhältnis von zwanzig gegen zwei Minderjährige in einer beaufsichtigten öffentlichen Freizeiteinrichtung dokumentiert die saisonale Wiederkehr einer Gewaltform, die zur progressiven Versicherheitlichung kommunaler Infrastruktur führt.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/gruppe-schlagt-auf-zwei-bruder-ein-freibad-in-berlin-neukolln-nach-randale-vorzeitig-geschlossen-12060092.html",
      "ort": "Berlin-Neukölln",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/gruppengewalt-gegen-jugendliche-im-berliner-sommerbad/"
    },
    {
      "title": "Angriff auf DRK-Sanitäter bei Patientenversorgung in Neukölln",
      "date": "2024-07-02",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "angriff-auf-drk-sanitater-bei-patientenversorgung-in-neukolln",
      "lead": "Unbeteiligte Umstehende transformierten sich bei sichtbar benigner Notfallversorgung zu Angreifern gegen einen erkennbar gekennzeichneten Rettungssanitäter — die Hilfeleistung selbst wurde zum Auslöser der Gewalt.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/sanitater-musste-ins-krankenhaus-rettungskrafte-bei-einsatz-in-berlin-neukolln-angegriffen-11952593.html",
      "ort": "Berlin-Neukölln",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/angriff-auf-drk-sanitater-bei-patientenversorgung-in-neukolln/"
    },
    {
      "title": "Messerangriff auf Bundespolizisten am Bahnhof Lauf",
      "date": "2024-06-30",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "messerangriff-auf-bundespolizisten-am-bahnhof-lauf",
      "lead": "Der Angriff auf drei Bundespolizisten durch einen ausreisepflichtigen, polizeilich als gewalttätig bekannten Mann dokumentiert die operative Kluft zwischen rechtskräftiger Asylantragsablehnung und faktischer Aufenthaltsbeendigung.",
      "source_name": "Bayerisches Staatsministerium der Justiz",
      "source_url": "https://www.justiz.bayern.de/gerichte-und-behoerden/staatsanwaltschaft/nuernberg-fuerth/presse/2025/1.php",
      "ort": "Lauf an der Pegnitz, Bayern",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-bundespolizisten-am-bahnhof-lauf/"
    },
    {
      "title": "Angriffsserie während der EM-Übertragung in Wolmirstedt",
      "date": "2024-06-14",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt",
      "lead": "Die Verknüpfung zweier Tatorte — Wohngebäude und private Gartenparty — zu einer sequenziellen Gewalthandlung während eines medialen Großereignisses erzeugt ein Tatmuster, das konventionelle Sicherheitsarchitekturen kategorial unterläuft.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/em-party-tote-polizei-100.html",
      "ort": "Wolmirstedt, Sachsen-Anhalt",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt/"
    },
    {
      "title": "Messerattacke im Regionalzug bei Saarbrücken",
      "date": "2024-06-10",
      "created": "2026-07-01T21:39:05.017Z",
      "slug": "messerattacke-im-regionalzug-bei-saarbrucken",
      "lead": "Die vollständige Grundlosigkeit eines Messerangriffs im Regionalzug — kein Streit, kein Blickkontakt, kein erkennbares Motiv — verbindet sich mit einer kalkulierten Flucht beim nächsten Halt zu einem Tatmuster, das konventionelle Gewaltlogiken unterläuft.",
      "source_name": "Presseportal / Bundespolizei Trier",
      "source_url": "https://www.presseportal.de/blaulicht/pm/70138/5798275",
      "ort": "Saarbrücken",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerattacke-im-regionalzug-bei-saarbrucken/"
    },
    {
      "title": "Terroranschlag auf Kundgebung am Mannheimer Marktplatz",
      "date": "2024-05-31",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-kundgebung-am-mannheimer-marktplatz",
      "lead": "Die doppelte Strukturanomalie aus einem fünf Jahre lang nicht vollstreckten Haftbefehl und einer ungeschützten politischen Kundgebung im öffentlichen Raum ermöglicht einen islamistisch motivierten Terroranschlag, der institutionell vermeidbar gewesen wäre.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Mannheim_am_31._Mai_2024",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-kundgebung-am-mannheimer-marktplatz/"
    },
    {
      "title": "Flusssäure-Anschlag an der Wohnungstür in Rosenheim",
      "date": "2024-05-13",
      "created": "2026-07-01T21:39:05.017Z",
      "slug": "flusssaure-anschlag-an-der-wohnungstur-in-rosenheim",
      "lead": "Ein maskierter Angreifer setzt Flusssäure als Waffe ein — ein industrieller Gefahrstoff, dessen Beschaffung und zielgerichtete Verwendung an einer Wohnungstür ein in der deutschen Kriminalstatistik nahezu präzedenzloses Tatmuster ergibt.",
      "source_name": "Bayerische Polizei",
      "source_url": "https://www.polizei.bayern.de/aktuelles/pressemitteilungen/067783/index.html",
      "ort": "Rosenheim, Bayern",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/flusssaure-anschlag-an-der-wohnungstur-in-rosenheim/"
    },
    {
      "title": "Dreistündige Massenschlägerei am Tollensesee",
      "date": "2024-05-09",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "dreistundige-massenschlagerei-am-tollensesee",
      "lead": "Eine Massenschlägerei mit rund 40 Beteiligten dauert trotz Einsatzes von 60 Polizeibeamten drei Stunden an und offenbart das Versagen konventioneller Deeskalation, wenn Gruppengewalt eine kritische Dauer überschreitet.",
      "source_name": "Nordkurier",
      "source_url": "https://www.nordkurier.de/regional/neubrandenburg/schlaegerei-mit-verletzten-bei-eroeffnung-von-strandbar-in-neubrandenburg-2514061",
      "ort": "Neubrandenburg, Mecklenburg-Vorpommern",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/dreistundige-massenschlagerei-am-tollensesee/"
    },
    {
      "title": "Tötung eines Forensik-Arztes in Wasserburg am Inn",
      "date": "2024-04-08",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totung-eines-forensik-arztes-in-wasserburg-am-inn",
      "lead": "Die Tötung eines forensischen Psychiaters durch einen ehemaligen Patienten auf dem Klinikgelände offenbart die systemische Verwundbarkeit einer Berufsgruppe, die Therapie und Justizgutachten in Personalunion vereint.",
      "source_name": "Bayerische Polizei",
      "source_url": "https://www.polizei.bayern.de/aktuelles/pressemitteilungen/065292/index.html",
      "ort": "Wasserburg am Inn, Bayern",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/totung-eines-forensik-arztes-in-wasserburg-am-inn/"
    },
    {
      "title": "Messerangriff in Regionalbahn bei Niederlahnstein",
      "date": "2024-04-08",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "messerangriff-in-regionalbahn-bei-niederlahnstein",
      "lead": "Ein Messerangriff in einem fahrenden Regionalzug bei Niederlahnstein reproduziert das Brokstedt-Muster und verdichtet die Serie von Gewalttaten im Nahverkehr zu einem eigenständigen kriminologischen Phänomen.",
      "source_name": "56aktuell.de",
      "source_url": "https://56aktuell.de/grosseinsatz-in-lahnstein-messerattacke-in-der-regionalbahn-ein-schwerverletzter/",
      "ort": "Niederlahnstein, Rheinland-Pfalz",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-in-regionalbahn-bei-niederlahnstein/"
    },
    {
      "title": "Schulattacke am Wilhelm-Dörpfeld-Gymnasium in Wuppertal",
      "date": "2024-02-22",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal",
      "lead": "Ein Messerangriff im Oberstufenraum eines Gymnasiums trifft auf ein Schulsystem, das weder Zugangskontrollen noch Sicherheitsschleusen kennt und diese Schutzlosigkeit bislang als Ausdruck offener Schulkultur versteht.",
      "source_name": "Euronews",
      "source_url": "https://www.euronews.com/2024/02/22/four-injured-in-school-stabbing-in-western-germany",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal/"
    },
    {
      "title": "Doppelmord am Oberhausener Hauptbahnhof durch Minderjährige",
      "date": "2024-02-10",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige",
      "lead": "Ein letales Gruppendelikt mit Messern, verübt durch vier 14- bis 16-Jährige, unterläuft die Altersstruktur konventioneller Tötungsdelikte und stellt das Jugendstrafrecht vor seine härteste Bewährungsprobe.",
      "source_name": "Sportschau / WDR",
      "source_url": "https://www.sportschau.de/regional/wdr/wdr-messerattacke-in-oberhausen-zweiter-ukrainischer-basketballer-gestorben-102.html",
      "ort": "Oberhausen, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige/"
    },
    {
      "title": "Gewalt in der Notaufnahme des Sana-Klinikums Berlin",
      "date": "2024-01-01",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "gewalt-in-der-notaufnahme-des-sana-klinikums-berlin",
      "lead": "Zwei Brüder attackierten in der Notaufnahme einen Arzt und eine Krankenschwester, weil die Wartezeit bei einer Schnittwunde zu lang erschien — ein Fall von Anspruchsgewalt, der die Funktion der Notaufnahme als geschützten Behandlungsraum strukturell infrage stellt.",
      "source_name": "Amtsgericht Tiergarten Berlin",
      "source_url": "https://www.berlin.de/gerichte/presse/pressemitteilungen-der-ordentlichen-gerichtsbarkeit/2025/pressemitteilung.1539774.php",
      "ort": "Berlin-Lichtenberg",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/gewalt-in-der-notaufnahme-des-sana-klinikums-berlin/"
    },
    {
      "title": "Koordinierte Anschlagsserie auf Synagogen in Nordrhein-Westfalen",
      "date": "2023-11-17",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "koordinierte-anschlagsserie-auf-synagogen-in-nordrhein-westfalen",
      "lead": "In einer einzigen Nacht wurden Synagogen und jüdische Einrichtungen in Essen, Bochum und Dortmund durch Schüsse und Brandanschläge attackiert, wobei die koordinierte Mehrstadt-Serie mit Hinweisen auf eine mögliche ausländische staatliche Steuerung eine neue Eskalationsstufe antisemitischer Gewalt in Deutschland nach dem 7. Oktober 2023 markierte.",
      "source_name": "Jüdische Allgemeine",
      "source_url": "https://www.juedische-allgemeine.de/juedische-welt/brandanschlag-synagoge-dortmund/",
      "ort": "Essen, Bochum, Dortmund, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/koordinierte-anschlagsserie-auf-synagogen-in-nordrhein-westfalen/"
    },
    {
      "title": "Tötung eines Obdachlosen am Luisenplatz in Darmstadt",
      "date": "2023-11-15",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "toetung-eines-obdachlosen-am-luisenplatz-in-darmstadt",
      "lead": "Ein 15-Jähriger trat einen erst seit 14 Tagen obdachlosen Mann an einer Bushaltestelle am Darmstädter Luisenplatz über vier Minuten lang 87 Mal gegen Kopf und Oberkörper, wobei das Gericht von »absolutem Vernichtungswillen« sprach und die Tat ein doppeltes Systemversagen offenlegte: den fehlenden Schutz Obdachloser an öffentlichen Schlafplätzen und die unzureichende Abfederung bei Wohnungsverlust.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/jugendlicher-mit-absolutem-vernichtungswillen-v8,prozess-obdachloser-darmstadt-100.html",
      "ort": "Darmstadt, Hessen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/toetung-eines-obdachlosen-am-luisenplatz-in-darmstadt/"
    },
    {
      "title": "Amoklauf mit Familienerbwaffe an der Waldbachschule in Offenburg",
      "date": "2023-11-09",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "amoklauf-mit-familienerbwaffe-an-der-waldbachschule-in-offenburg",
      "lead": "Ein 15-Jähriger betrat die Offenburger Waldbachschule über einen unbewachten Hintereingang mit einer geladenen Beretta, zusätzlicher Munition, einem Brandsatz, einem selbst erstellten Gebäudeplan und einer Namensliste, erschoss einen Mitschüler und offenbarte damit ein Bündel struktureller Versäumnisse von der Waffenaufbewahrung bis zur Gebäudesicherung.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/toter-nach-schiesserei-an-schule-in-offenburg-tatwaffe-war-moglicherweise-ein-erbstuck-10761646.html",
      "ort": "Offenburg, Baden-Württemberg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/amoklauf-mit-familienerbwaffe-an-der-waldbachschule-in-offenburg/"
    },
    {
      "title": "Straßenschlacht bei eritreischer Veranstaltung in Stuttgart",
      "date": "2023-09-16",
      "created": "2026-07-01T21:39:05.015Z",
      "slug": "strassenschlacht-bei-eritreischer-veranstaltung-in-stuttgart",
      "lead": "Zwei Monate nach Gießen reproduzierte sich das Muster transnationaler Stellvertretergewalt in Stuttgart mit gesteigerter Intensität — 39 verletzte Polizeibeamte und der Einsatz vorbereiteter Waffen markieren den Übergang von spontaner Versammlungsgewalt zu organisierter Konfrontation.",
      "source_name": "Stuttgarter Zeitung",
      "source_url": "https://www.stuttgarter-zeitung.de/inhalt.prozess-nach-randale-in-stuttgart-hallschlag-drei-jahre-und-neun-monate-haft-fuer-angriff-auf-polizisten.3e634b4e-5356-492e-8cad-e9e67c323013.html",
      "ort": "Stuttgart-Hallschlag, Baden-Württemberg",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/strassenschlacht-bei-eritreischer-veranstaltung-in-stuttgart/"
    },
    {
      "title": "Tötung eines Sechsjährigen auf dem Sportplatz in Pragsdorf",
      "date": "2023-09-14",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "toetung-eines-sechsjaehrigen-auf-dem-sportplatz-in-pragsdorf",
      "lead": "Ein 14-Jähriger, der zuvor bereits durch wiederholte Aggression gegen Kinder im Ort aufgefallen war, tötete einen Sechsjährigen auf einem Sportplatz mit Faustschlägen und Messerstichen, wobei die Tat das Versagen kommunaler Frühwarnsysteme bei jugendlicher Gewalteskalation dokumentierte.",
      "source_name": "Nordkurier",
      "source_url": "https://www.nordkurier.de/regional/neubrandenburg/joel-6-in-pragsdorf-erstochen-prozess-gegen-14-jaehrigen-beginnt-2261942",
      "ort": "Pragsdorf, Mecklenburg-Vorpommern",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/toetung-eines-sechsjaehrigen-auf-dem-sportplatz-in-pragsdorf/"
    },
    {
      "title": "Kopfschuss auf Schulhof mit Nachbarwaffe in Lohr am Main",
      "date": "2023-09-08",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "kopfschuss-auf-schulhof-mit-nachbarwaffe-in-lohr-am-main",
      "lead": "Ein 15-Jähriger erschoss seinen 14-jährigen Mitschüler auf dem Schulhof in Lohr am Main von hinten mit einem Kopfschuss aus einer 9-mm-Pistole, die legal einem Nachbarn gehörte, wobei der Fall die fatale Lücke zwischen Waffenaufbewahrungsvorschriften und deren Kontrolle sichtbar machte.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/bayern-lohr-mord-kopfschuss-schulhof-jugendstrafe-100.html",
      "ort": "Lohr am Main, Bayern",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/kopfschuss-auf-schulhof-mit-nachbarwaffe-in-lohr-am-main/"
    },
    {
      "title": "Freispruch trotz Geständnis vor US-Militärgericht in Wittlich",
      "date": "2023-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich",
      "lead": "Ein US-Militärgericht sprach einen geständigen Soldaten frei, weil die Anklagepunkte nicht ins Englische übersetzt worden waren — der Fall offenbart die operative Bruchstelle des NATO-Truppenstatuts, die bei Straftaten alliierter Soldaten auf deutschem Boden den wirksamen Rechtsschutz der Opfer aushebelt.",
      "source_name": "Legal Tribune Online",
      "source_url": "https://www.lto.de/recht/hintergruende/h/freispruch-trotz-gestaendnis-wittlich-us-militaergericht-justice",
      "ort": "Wittlich, Rheinland-Pfalz",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich/"
    },
    {
      "title": "Ausschreitungen beim Eritrea-Festival in Gießen",
      "date": "2023-07-08",
      "created": "2026-07-01T21:39:04.999Z",
      "slug": "ausschreitungen-beim-eritrea-festival-in-giessen",
      "lead": "Ein transnationaler politischer Konflikt materialisierte sich als Straßengewalt in einer hessischen Mittelstadt — die kommunale Gefahrenabwehr war für ein Szenario, das sich weder verbieten noch beherrschen ließ, weder konzeptionell noch personell ausgelegt.",
      "source_name": "hessenschau.de",
      "source_url": "https://www.hessenschau.de/gesellschaft/eritrea-festival-in-giessen-2023-weitere-bewaehrungsstrafen-nach-ausschreitungen-v1,eritrea-festival-urteil-100.html",
      "ort": "Gießen, Hessen",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/ausschreitungen-beim-eritrea-festival-in-giessen/"
    },
    {
      "title": "Massenschlägerei im Mannheimer Herzogenriedbad",
      "date": "2023-06-18",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "massenschlagerei-im-mannheimer-herzogenriedbad",
      "lead": "Ein Kinderstreit im Schwimmbecken eskalierte über drei Stufen zur bewaffneten Massenschlägerei mit über 40 Beteiligten — die Kaskadendynamik vom Familienkonflikt zur Messerkonfrontation markiert ein strukturell neuartiges Muster in offenen Freizeiteinrichtungen.",
      "source_name": "RNF",
      "source_url": "https://www.rnf.de/mannheim-verletzte-bei-schlaegerei-von-rund-40-personen-im-herzogenriedbad-mann-mit-messer-verletzt-353899/",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 7,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenschlagerei-im-mannheimer-herzogenriedbad/"
    },
    {
      "title": "Handgranatenwurf auf Trauerfeier in Altbach",
      "date": "2023-06-09",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "handgranatenwurf-auf-trauerfeier-in-altbach",
      "lead": "Der gezielte Wurf einer militärischen Handgranate auf eine Trauergemeinde in Altbach, bei dem 15 Personen durch Stahlkugeln verletzt wurden, markierte die Eskalation des Stuttgarter Bandenkriegs von Schusswaffen zu Kriegswaffen und stellte die bisherige kriminologische Kategorisierung organisierter Gewalt in Deutschland in Frage.",
      "source_name": "Stuttgarter Nachrichten",
      "source_url": "https://www.stuttgarter-nachrichten.de/inhalt/nach-handgranatenwurf-bei-beerdigung-in-altbach-anklage-gegen-tatverdaechtigen.baf2e3ac-ff70-484e-a4a8-5daa44fd6e03.html",
      "ort": "Altbach, Baden-Württemberg",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/handgranatenwurf-auf-trauerfeier-in-altbach/"
    },
    {
      "title": "Benzin-Brandanschlag auf neun Einsatzkräfte bei Wohnungskontrolle in Ratingen",
      "date": "2023-05-11",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "benzin-brandanschlag-auf-neun-einsatzkraefte-bei-wohnungskontrolle-in-ratingen",
      "lead": "Ein 57-Jähriger schleuderte neun Einsatzkräften von Polizei, Feuerwehr und DRK bei einer routinemäßigen Wohnungskontrolle eine große Menge Benzin entgegen und entzündete sie, wobei drei Retter lebensgefährliche Verbrennungen erlitten und die Tat eine strukturelle Schutzlücke bei sogenannten Welfare-Checks offenlegte.",
      "source_name": "Feuerwehr Magazin",
      "source_url": "https://www.feuerwehrmagazin.de/nachrichten/news/explosion-ratingen-zwei-einsatzkraefte-aus-koma-geholt-121988",
      "ort": "Ratingen, Nordrhein-Westfalen",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/benzin-brandanschlag-auf-neun-einsatzkraefte-bei-wohnungskontrolle-in-ratingen/"
    },
    {
      "title": "Messerangriff auf Grundschulkinder auf Neuköllner Schulhof",
      "date": "2023-05-03",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "messerangriff-auf-grundschulkinder-auf-neukoellner-schulhof",
      "lead": "Ein seit mindestens zehn Jahren unbehandelt an paranoider Schizophrenie leidender Mann griff auf dem Schulhof einer Neuköllner Grundschule zwei Mädchen im Alter von sieben und acht Jahren mit einem Küchenmesser an und verletzte beide lebensgefährlich, wobei die Tat das Totalversagen der ambulanten psychiatrischen Versorgung als Sicherheitsrisiko sichtbar machte.",
      "source_name": "Landgericht Berlin",
      "source_url": "https://www.berlin.de/gerichte/presse/pressemitteilungen-der-ordentlichen-gerichtsbarkeit/2024/pressemitteilung.1407008.php",
      "ort": "Berlin-Neukölln",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-auf-grundschulkinder-auf-neukoellner-schulhof/"
    },
    {
      "title": "Tötungsdelikt in fränkischem Kinderheim",
      "date": "2023-04-03",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totungsdelikt-in-frankischem-kinderheim",
      "lead": "Eine Kinderschutzeinrichtung wurde zum Tatort eines Tötungsdelikts durch einen strafunmündigen Elfjährigen, nachdem ein Erwachsener unbemerkt durch ein Fenster eingedrungen war — das doppelte Versagen der Institution dokumentiert eine Schutzarchitektur, die auf keiner Ebene funktionierte.",
      "source_name": "Frankenpost",
      "source_url": "https://www.frankenpost.de/inhalt.wunsiedel-mord-an-maedchen-40-koepfige-soko-ermittelt.25af368f-79c4-4439-a675-0bbf6c266d6e.html",
      "ort": "Wunsiedel, Bayern",
      "relevance": 8,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/totungsdelikt-in-frankischem-kinderheim/"
    },
    {
      "title": "Tötung einer Zwölfjährigen durch strafunmündige Kinder in Freudenberg",
      "date": "2023-03-11",
      "created": "2026-07-02T02:00:00.000Z",
      "slug": "toetung-einer-zwoelfjaehrigen-durch-strafunmuendige-kinder-in-freudenberg",
      "lead": "Zwei Mädchen im Alter von 12 und 13 Jahren töteten eine Gleichaltrige mit 74 Messerstichen in einem geplanten Angriff, den das deutsche Strafrechtssystem mangels Strafmündigkeit unter 14 Jahren weder ahnden noch institutionell beantworten konnte.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdfheute.de/panorama/kriminalitaet/luise-freudenberg-toetung-maedchen-100.html",
      "ort": "Freudenberg, Nordrhein-Westfalen",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/toetung-einer-zwoelfjaehrigen-durch-strafunmuendige-kinder-in-freudenberg/"
    },
    {
      "title": "Massenschießerei in Hamburger Königreichssaal",
      "date": "2023-03-09",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "massenschiesserei-in-hamburger-konigreichssaal",
      "lead": "Das Waffenrecht stellte die Tatwaffe bereit — trotz dokumentierter Hinweise auf die mangelnde Eignung des Schützen zum Waffenbesitz blieb die Erlaubnis bestehen, und sämtliche Dienstaufsichtsverfahren gegen die zuständigen Beamten wurden eingestellt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amoktat_in_Hamburg-Alsterdorf_2023",
      "ort": "Hamburg-Alsterdorf",
      "relevance": 10,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/massenschiesserei-in-hamburger-konigreichssaal/"
    },
    {
      "title": "Messerangriff im Regionalzug bei Brokstedt",
      "date": "2023-01-25",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "messerangriff-im-regionalzug-bei-brokstedt",
      "lead": "24 Ermittlungsverfahren, vier Verurteilungen wegen schwerer Körperverletzung und ein Kommunikationsbruch zwischen zwei Bundesländern erzeugten den sechstägigen Korridor zwischen Haftentlassung und tödlichem Messerangriff in einem geschlossenen Zugraum.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerattacke_in_Brokstedt_am_25._Januar_2023",
      "ort": "Brokstedt, Schleswig-Holstein",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/messerangriff-im-regionalzug-bei-brokstedt/"
    },
    {
      "title": "Tötung einer Lehrerin am Berufskolleg in Ibbenbüren",
      "date": "2023-01-10",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "toetung-einer-lehrerin-am-berufskolleg-in-ibbenbueren",
      "lead": "Ein 17-jähriger Schüler erstach seine 55-jährige Klassenlehrerin am Tag eines disziplinarischen Schulverweises, wobei die Tat eine strukturelle Lücke offenlegte: Zwischen der Verhängung schulischer Disziplinarmaßnahmen und dem potenziellen Eskalationsrisiko bei vulnerablen Schülern existierte kein Sicherheitsprotokoll.",
      "source_name": "News4Teachers",
      "source_url": "https://www.news4teachers.de/2023/01/lehrerin-erstochen-richter-schickt-17-jaehrigen-schueler-wegen-des-verdachts-auf-totschlag-in-untersuchungshaft/",
      "ort": "Ibbenbüren, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/toetung-einer-lehrerin-am-berufskolleg-in-ibbenbueren/"
    },
    {
      "title": "Silvester-Hinterhalte auf Einsatzkräfte in Berlin",
      "date": "2022-12-31",
      "created": "2026-07-02T01:30:00.000Z",
      "slug": "silvester-hinterhalte-auf-einsatzkraefte-in-berlin",
      "lead": "Die taktische Struktur der Silvester-Angriffe 2022/23 in Berlin, bei denen Feuerwehrfahrzeuge durch brennende Barrikaden angelockt und von maskierten Gruppen systematisch geplündert und beschossen wurden, markiert den Übergang von spontaner Silvester-Aggression zu operativ geplanter Sabotage der Rettungsinfrastruktur.",
      "source_name": "t-online",
      "source_url": "https://berlin.t-online.de/region/berlin/id_100104656/schwere-eskalation-an-silvester-25-maenner-locken-feuerwehr-in-hinterhalt.html",
      "ort": "Berlin-Neukölln",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/silvester-hinterhalte-auf-einsatzkraefte-in-berlin/"
    },
    {
      "title": "Tödlicher Polizeieinsatz gegen suizidalen Sechzehnjährigen in Dortmund",
      "date": "2022-08-08",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "toedlicher-polizeieinsatz-gegen-suizidalen-sechzehnjaehrigen-in-dortmund",
      "lead": "Zwölf Polizeibeamte erschossen einen 16-Jährigen in einer psychischen Krise mit sechs Schüssen aus Maschinenpistolen, nachdem ein Taser-Einsatz wirkungslos geblieben war, wobei der Fall die strukturelle Abwesenheit spezialisierter Kriseninterventionsteams für psychisch erkrankte Personen im deutschen Polizeisystem offenlegte.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/dortmund-polizei-schuesse-jugendlicher-100.html",
      "ort": "Dortmund, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/toedlicher-polizeieinsatz-gegen-suizidalen-sechzehnjaehrigen-in-dortmund/"
    },
    {
      "title": "Amokfahrt auf dem Kurfürstendamm in Berlin",
      "date": "2022-06-08",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "amokfahrt-auf-dem-kurfuerstendamm-in-berlin",
      "lead": "Ein 29-Jähriger steuerte seinen Kleinwagen am Berliner Kurfürstendamm mit hoher Geschwindigkeit in eine Gruppe von Schülern und Passanten, tötete eine Lehrerin und verletzte über 30 Menschen, wobei die Tat die prinzipielle Unabwehrbarkeit von Fahrzeugangriffen in nicht durch Poller geschützten Fußgängerbereichen demonstrierte.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/tote-und-verletzte-am-ku-damm-in-berlin-auto-faehrt-in-menschengruppe-8321694.html",
      "ort": "Berlin-Charlottenburg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/amokfahrt-auf-dem-kurfuerstendamm-in-berlin/"
    },
    {
      "title": "Doppeltötung zweier Polizeibeamter bei nächtlicher Kontrolle in Kusel",
      "date": "2022-01-31",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "doppeltoetung-zweier-polizeibeamter-bei-naechtlicher-kontrolle-in-kusel",
      "lead": "Ein Wilderer erschoss in der Nacht auf einer abgelegenen Kreisstraße im Landkreis Kusel zwei Polizeibeamte durch gezielte Kopfschüsse, um Wildereidelikte zu verbergen, wobei die Tat die systemischen Defizite bei nächtlichen Einzelkontrollen in ländlichen Gebieten und die fehlende Einsatzabsicherung für Zwei-Personen-Streifen offenlegte.",
      "source_name": "Bundesgerichtshof",
      "source_url": "https://www.bundesgerichtshof.de/SharedDocs/Pressemitteilungen/DE/2023/2023122.html",
      "ort": "Kusel, Rheinland-Pfalz",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/doppeltoetung-zweier-polizeibeamter-bei-naechtlicher-kontrolle-in-kusel/"
    },
    {
      "title": "Amoklauf im Hörsaal der Universität Heidelberg",
      "date": "2022-01-24",
      "created": "2026-07-02T02:30:00.000Z",
      "slug": "amoklauf-im-hoersaal-der-universitaet-heidelberg",
      "lead": "Ein 18-jähriger Student eröffnete mit zwei legal erworbenen Waffen das Feuer in einem Hörsaal der Universität Heidelberg, tötete eine Studentin und verletzte drei weitere Personen, wobei der legale Erwerb zweier Schusswaffen durch einen psychisch auffälligen jungen Mann ohne vorherige behördliche Intervention die Kontrollmechanismen des Waffenrechts in Frage stellte.",
      "source_name": "SWR",
      "source_url": "https://www.swr.de/swraktuell/baden-wuerttemberg/mannheim/amoklauf-uni-heidelberg-100.html",
      "ort": "Heidelberg, Baden-Württemberg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/amoklauf-im-hoersaal-der-universitaet-heidelberg/"
    },
    {
      "title": "Erschießung eines Tankstellenkassierers wegen Maskenpflicht in Idar-Oberstein",
      "date": "2021-09-18",
      "created": "2026-07-01T22:30:00.000Z",
      "slug": "erschiessung-eines-tankstellenkassierers-wegen-maskenpflicht-in-idar-oberstein",
      "lead": "Die gezielte Tötung eines 20-jährigen Kassierers, weil er auf die gesetzliche Maskenpflicht hinwies, markiert den einzigen dokumentierten Fall in Deutschland, in dem die Durchsetzung einer Pandemieverordnung zum Tatmotiv eines Tötungsdelikts wurde.",
      "source_name": "Rhein-Zeitung",
      "source_url": "https://www.rhein-zeitung.de/lokales/nahe-zeitung/tankstellenmord-von-idar-oberstein-urteil-ist-nun-rechtskraeftig_arid-2491579.html",
      "ort": "Idar-Oberstein, Rheinland-Pfalz",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/erschiessung-eines-tankstellenkassierers-wegen-maskenpflicht-in-idar-oberstein/"
    },
    {
      "title": "Gruppenvergewaltigung im Hamburger Stadtpark",
      "date": "2020-09-19",
      "created": "2026-07-01T22:40:00.000Z",
      "slug": "gruppenvergewaltigung-im-hamburger-stadtpark",
      "lead": "Die Gruppenvergewaltigung einer 15-Jährigen durch neun jugendliche Täter, die das Geschehen filmten und die Aufnahmen anschließend löschten, exponiert den Systemkonflikt zwischen der Schwere sexualisierter Gruppengewalt und der erzieherischen Logik des Jugendstrafrechts.",
      "source_name": "Bundesgerichtshof",
      "source_url": "https://www.bundesgerichtshof.de/SharedDocs/Pressemitteilungen/DE/2025/2025093.html",
      "ort": "Hamburg",
      "relevance": 9,
      "minutes": 2,
      "href": "/neue-dimension-gewalt/gruppenvergewaltigung-im-hamburger-stadtpark/"
    }
  ]
}
;
