window.NOVA_DATA =
{
  "generated": "2026-07-01T22:59:14.448Z",
  "items": [
    {
      "title": "Freibad-Räumung nach Eskalation in Bochum-Werne",
      "date": "2026-06-24",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "freibad-raumung-nach-eskalation-in-bochum-werne",
      "lead": "Ein Streit zwischen zwei Badegästen führte zur Räumung von 4.000 Besuchern unter Polizeischutz — am Folgetag wurden in allen Bochumer Bädern Ausweiskontrollen eingeführt.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_101312784/freibad-pruegelei-in-bochum-sorgt-fuer-raeumung-grosser-polizei-einsatz.html",
      "ort": "Bochum-Werne, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/freibad-raumung-nach-eskalation-in-bochum-werne/"
    },
    {
      "title": "Amokfahrt in der Leipziger Grimmaischen Straße",
      "date": "2026-05-04",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "amokfahrt-in-der-leipziger-grimmaischen-strasse",
      "lead": "Ein SUV durchfuhr 450 Meter der Leipziger Fußgängerzone mit geschätzten 70-80 km/h — erst vorhandene Poller in einer Seitenstraße stoppten das Fahrzeug.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_von_Leipzig",
      "ort": "Leipzig, Sachsen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/amokfahrt-in-der-leipziger-grimmaischen-strasse/"
    },
    {
      "title": "Sprengsätze im ICE bei Siegburg",
      "date": "2026-04-02",
      "created": "2026-07-01T21:39:05.032Z",
      "slug": "sprengsatze-im-ice-bei-siegburg",
      "lead": "Ein 20-Jähriger zündete im ICE 19 von Aachen nach Frankfurt zwei Sprengsätze und verletzte zwölf Fahrgäste — der Staatsschutz übernahm die Ermittlungen.",
      "source_name": "t-online Aachen",
      "source_url": "https://aachen.t-online.de/region/aachen/id_101198490/ice-von-aachen-nach-frankfurt-mann-zuendet-sprengstoff-zwoelf-verletzte.html",
      "ort": "Siegburg, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/sprengsatze-im-ice-bei-siegburg/"
    },
    {
      "title": "Mehrfach-Messerangriff im Schienenersatzverkehr in Wuppertal",
      "date": "2026-02-14",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "mehrfach-messerangriff-im-schienenersatzverkehr-in-wuppertal",
      "lead": "In einem Schienenersatzverkehr-Bus am Wuppertaler Robert-Daum-Platz wurden drei Fahrgäste niedergestochen — die provisorische Transportform bot noch weniger Schutz als reguläre Züge.",
      "source_name": "Westdeutsche Zeitung",
      "source_url": "https://www.wz.de/nrw/wuppertal/wuppertal-messerstecher-verletzt-mehrere-fahrgaeste-im-schienenersatzverkehr_aid-143882291",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/mehrfach-messerangriff-im-schienenersatzverkehr-in-wuppertal/"
    },
    {
      "title": "Tödlicher Angriff auf Zugbegleiter bei Fahrkartenkontrolle",
      "date": "2026-02-03",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "todlicher-angriff-auf-zugbegleiter-bei-fahrkartenkontrolle",
      "lead": "Ein Zugbegleiter wurde bei einer Fahrkartenkontrolle in einem Regionalexpress so schwer geschlagen, dass er zwei Tage später an einer Hirnblutung verstarb.",
      "source_name": "Homburg1",
      "source_url": "https://homburg1.de/eskalation-bei-fahrkartenkontrolle-zugbegleiter-in-lebensgefahr-237815/",
      "ort": "Landstuhl / Homburg, Rheinland-Pfalz",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/todlicher-angriff-auf-zugbegleiter-bei-fahrkartenkontrolle/"
    },
    {
      "title": "Silvester-Eskalation gegen Einsatzkräfte in mehreren Großstädten",
      "date": "2025-12-31",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "silvester-eskalation-gegen-einsatzkrafte-in-mehreren-grossstadten",
      "lead": "In der Silvesternacht 2025/26 erreichten die Angriffe auf Rettungskräfte eine neue Qualität: In Frankfurt wurde ein Rettungswagen beschossen und instrumentalisiert, in Berlin ersetzte ein Wasserwerfer die handlungsunfähige Feuerwehr.",
      "source_name": "t-online / Tagesspiegel / komba NRW",
      "source_url": "https://frankfurt.t-online.de/region/frankfurt-am-main/id_101064410/frankfurt-sanitaeter-in-silvesternacht-angegriffen-und-verletzt.html",
      "ort": "Frankfurt, Berlin, Duisburg, Leipzig",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/silvester-eskalation-gegen-einsatzkrafte-in-mehreren-grossstadten/"
    },
    {
      "title": "Arzt in Darmstädter Klinikum bewusstlos geschlagen",
      "date": "2025-12-14",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "arzt-in-darmstadter-klinikum-bewusstlos-geschlagen",
      "lead": "Ein 55-Jähriger schlug einen diensthabenden Arzt im Klinikum Darmstadt mit Schlägen gegen den Kopf bewusstlos — weil sein Begleiter nicht als Notfall eingestuft wurde.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/mit-kopfverletzungen-auf-intensivstation-mann-attackiert-arzt-im-klinikum-darmstadt-v1,arzt-zusammengeschlagen-100.html",
      "ort": "Darmstadt, Hessen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/arzt-in-darmstadter-klinikum-bewusstlos-geschlagen/"
    },
    {
      "title": "Fahrzeug-Angriff auf Kirmes-Besucher in Niederdorla",
      "date": "2025-09-21",
      "created": "2026-07-01T21:39:05.027Z",
      "slug": "fahrzeug-angriff-auf-kirmes-besucher-in-niederdorla",
      "lead": "Ein 41-Jähriger fuhr mit einem Pick-up-Truck in eine Menschenmenge auf einer Kirmes in Niederdorla und verletzte fünf Besucher — zuvor war er bereits wegen Raserei aufgefallen.",
      "source_name": "t-online.de",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100923892/niederdorla-in-thueringen-mann-faehrt-mit-pick-up-truck-in-kirmes-verletzte.html",
      "ort": "Niederdorla, Thüringen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeug-angriff-auf-kirmes-besucher-in-niederdorla/"
    },
    {
      "title": "Messerattacke an Leipziger Zentralhaltestelle",
      "date": "2025-09-01",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "messerattacke-an-leipziger-zentralhaltestelle",
      "lead": "An der Zentralhaltestelle direkt vor dem Leipziger Hauptbahnhof wurde ein 40-Jähriger am Samstagmorgen niedergestochen.",
      "source_name": "Blaulicht-Ticker",
      "source_url": "https://www.blaulicht-ticker.de/leipzig/messerangriff-an-zentralhaltestelle-in-leipzig-am-samstagmorgen-3050290",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-an-leipziger-zentralhaltestelle/"
    },
    {
      "title": "Messerangriff auf Zivilcourage-Helfer in Dresdner Straßenbahn",
      "date": "2025-08-24",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "messerangriff-auf-zivilcourage-helfer-in-dresdner-strassenbahn",
      "lead": "Ein 20-jähriger Fahrgast, der in einer Dresdner Straßenbahn belästigte Frauen verteidigte, wurde von den Belästigern mit einem Messer ins Gesicht gestochen.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdfheute.de/panorama/messerattacke-dresden-strassenbahn-opfer-jonathan-rudat-spricht-100.html",
      "ort": "Dresden, Sachsen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-auf-zivilcourage-helfer-in-dresdner-strassenbahn/"
    },
    {
      "title": "Massenschlägerei bei Kampfsportveranstaltung in Ense",
      "date": "2025-08-10",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "massenschlagerei-bei-kampfsportveranstaltung-in-ense",
      "lead": "Bei einer Kampfsportveranstaltung in einer Industriehalle eskalierte ein Fanstreit zu einer Massenschlägerei mit etwa 100 Beteiligten.",
      "source_name": "Presseportal / Kreispolizeibehörde Soest",
      "source_url": "https://www.presseportal.de/blaulicht/pm/65855/6093599",
      "ort": "Ense, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/massenschlagerei-bei-kampfsportveranstaltung-in-ense/"
    },
    {
      "title": "Femizid trotz Fußfessel in Frankfurt-Bonames",
      "date": "2025-07-02",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "femizid-trotz-fussfessel-in-frankfurt-bonames",
      "lead": "Ein 36-Jähriger tötete einen Mann und griff seine Ehefrau mit einem Messer an — neun Tage, nachdem seine GPS-Fußfessel nach Ablauf der gesetzlichen Höchstfrist abgenommen worden war.",
      "source_name": "hessenschau.de",
      "source_url": "https://www.hessenschau.de/panorama/messerangriff-in-frankfurt-mutmasslicher-moerder-trug-bis-vor-kurzem-fussfessel-v2,mann-stirbt-frankfurt-mordverdacht-100.html",
      "ort": "Frankfurt-Bonames, Hessen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/femizid-trotz-fussfessel-in-frankfurt-bonames/"
    },
    {
      "title": "Sanitäter im Rettungswagen angegriffen in Karlsruhe",
      "date": "2025-06-28",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "sanitater-im-rettungswagen-angegriffen-in-karlsruhe",
      "lead": "Ein Patient attackierte während des Transports einen Sanitäter im Inneren des Rettungswagens und verletzte auch einen intervenierenden Polizeibeamten.",
      "source_name": "ka-news.de",
      "source_url": "https://www.ka-news.de/karlsruhe/polizeibericht-angriff-im-rettungswagen-verletzt-sanitaeter-und-polizist-in-karlsruhe-114589670",
      "ort": "Karlsruhe, Baden-Württemberg",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/sanitater-im-rettungswagen-angegriffen-in-karlsruhe/"
    },
    {
      "title": "Soziale-Medien-getriggerte Messerattacke am Frankfurter Hauptbahnhof",
      "date": "2025-06-15",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof",
      "lead": "Auf dem Vorplatz des Frankfurter Hauptbahnhofs wurde ein 18-Jähriger von einer Gruppe niedergestochen — Auslöser war offenbar ein TikTok-Video.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100748324/frankfurt-hauptbahnhof-messer-attacke-18-jaehriger-schwer-verletzt.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof/"
    },
    {
      "title": "Massenconfrontation mit Waffenarsenal in Dortmund-Nordstadt",
      "date": "2025-05-26",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt",
      "lead": "Ein Streit zwischen zwei kleinen Gruppen eskalierte auf der Schleswiger Straße zu einer Massenkonfrontation mit 250 bis 300 Beteiligten — mit Messern, Machete, Axt und Schusswaffe.",
      "source_name": "Rundblick Unna",
      "source_url": "https://rundblick-unna.de/2026/05/27/gewalteskalation-in-do-nord-mit-messern-machete-axt-schusswaffe-sieben-beteiligte-mehrere-hundert-gaffer/",
      "ort": "Dortmund-Nordstadt, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt/"
    },
    {
      "title": "Massenangriff am Hamburger Hauptbahnhof",
      "date": "2025-05-23",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenangriff-am-hamburger-hauptbahnhof",
      "lead": "Am Hamburger Hauptbahnhof wurden 15 Reisende niedergestochen — der Täter war einen Tag zuvor aus einer psychiatrischen Einrichtung entlassen worden.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_am_Hamburger_Hauptbahnhof_2025",
      "ort": "Hamburg",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenangriff-am-hamburger-hauptbahnhof/"
    },
    {
      "title": "Elfjährige Schülerin ersticht Mitschüler in Remscheid",
      "date": "2025-05-22",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "elfjahrige-schulerin-ersticht-mitschuler-in-remscheid",
      "lead": "Ein elfjähriges Kind verletzte einen 13-jährigen Mitschüler mit einem Küchenmesser — das Kind liegt unterhalb der Strafmündigkeitsgrenze.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/nach-messerangriff-auf-13-jahrigen-polizei-in-remscheid-ubergibt-11-jahrigen-wieder-den-eltern-13740730.html",
      "ort": "Remscheid, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/elfjahrige-schulerin-ersticht-mitschuler-in-remscheid/"
    },
    {
      "title": "Islamistischer Anschlag mit verkleideter Stockwaffe in Bielefeld",
      "date": "2025-05-18",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld",
      "lead": "Ein Angreifer tarnte sich als Gehbehinderter, nutzte einen zu einer Stichwaffe umgebauten Gehstock und attackierte in den Morgenstunden fünf Personen vor einer Gaststätte.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Bielefeld_2025",
      "ort": "Bielefeld, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld/"
    },
    {
      "title": "Messerangriff auf Supermarkt-Kundin nach Hausverbot in Rochlitz",
      "date": "2025-04-17",
      "created": "2026-07-01T21:39:05.026Z",
      "slug": "messerangriff-auf-supermarkt-kundin-nach-hausverbot-in-rochlitz",
      "lead": "Nach einem Hausverbot kehrte ein 23-Jähriger zum Supermarkt zurück und stach auf eine unbeteiligte Kundin ein — ein 18-jähriger Mitarbeiter, der eingriff, wurde lebensgefährlich verletzt.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/vorfall-im-sachsischen-rochlitz-zwei-menschen-bei-messerangriff-vor-supermarkt-schwer-verletzt-13561288.html",
      "ort": "Rochlitz, Sachsen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-supermarkt-kundin-nach-hausverbot-in-rochlitz/"
    },
    {
      "title": "Tödliche Messerattacke an U-Bahnhof Sophie-Charlotte-Platz",
      "date": "2025-04-12",
      "created": "2026-07-01T21:39:05.025Z",
      "slug": "todliche-messerattacke-an-u-bahnhof-sophie-charlotte-platz",
      "lead": "Ein 43-Jähriger erstach einen 29-Jährigen am U-Bahnhof Sophie-Charlotte-Platz — obwohl gegen ihn seit Monaten ein Haftbefehl vorlag, den keine Behörde vollstreckt hatte.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/todlicher-messerangriff-in-berliner-u-bahn-shadi-s-hatte-langst-in-haft-sitzen-mussen-13549201.html",
      "ort": "Berlin-Charlottenburg",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/todliche-messerattacke-an-u-bahnhof-sophie-charlotte-platz/"
    },
    {
      "title": "Messerattacke in Berliner Straßenbahn am Alexanderplatz",
      "date": "2025-04-10",
      "created": "2026-07-01T21:39:05.022Z",
      "slug": "messerattacke-in-berliner-strassenbahn-am-alexanderplatz",
      "lead": "In der Straßenbahnlinie M2 stieg ein Mann zu, begann zu schreien und stach beim Halt am Alexanderplatz auf einen 57-jährigen Fahrgast ein, der gerade aussteigen wollte.",
      "source_name": "Polizei Berlin",
      "source_url": "https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1550558.php",
      "ort": "Berlin-Mitte",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-in-berliner-strassenbahn-am-alexanderplatz/"
    },
    {
      "title": "Messerattacke auf Bahnsteig des Frankfurter Hauptbahnhofs",
      "date": "2025-03-15",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs",
      "lead": "Auf dem Bahnsteig 104 des Frankfurter Hauptbahnhofs stach ein 19-Jähriger auf einen 25-Jährigen ein — einer von mehreren Messervorfällen am selben Bahnhof im Jahr 2025.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/messerangriff-am-gleis-im-frankfurter-hauptbahnhof-v1,kurz-angriff-324.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs/"
    },
    {
      "title": "Messerangriff auf Lebensmittelkontrolleure in Gelsenkirchen",
      "date": "2025-03-12",
      "created": "2026-07-01T21:39:05.022Z",
      "slug": "messerangriff-auf-lebensmittelkontrolleure-in-gelsenkirchen",
      "lead": "Bei einer routinemäßigen Lebensmittelkontrolle in einer Eisdiele stach der Betreiber mit einem Messer auf zwei städtische Kontrolleure ein — einer erlitt lebensgefährliche Verletzungen.",
      "source_name": "Polizei Gelsenkirchen / Staatsanwaltschaft Essen",
      "source_url": "https://gelsenkirchen.polizei.nrw/presse/gemeinsame-pressemitteilung-der-staatsanwaltschaft-essen-und-der-polizei-gelsenkirchen-versuchtes-toetungsdelikt-bei-lebensmittelkontrolle-in-horst",
      "ort": "Gelsenkirchen-Horst, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-auf-lebensmittelkontrolleure-in-gelsenkirchen/"
    },
    {
      "title": "Messerangriff auf DB-Mitarbeiter am Dortmunder Hauptbahnhof",
      "date": "2025-03-06",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "messerangriff-auf-db-mitarbeiter-am-dortmunder-hauptbahnhof",
      "lead": "Ein 22-Jähriger kehrte eine Stunde nach einem Streit um ein Busticket an den Fahrkartenschalter des Dortmunder Hauptbahnhofs zurück und stach einem 56-jährigen DB-Mitarbeiter lebensgefährlich in den Körper.",
      "source_name": "Polizei Dortmund",
      "source_url": "https://dortmund.polizei.nrw/presse/22-jaehriger-sticht-mit-einem-messer-auf-einen-mitarbeiter-im-hauptbahnhof-dortmund-ein-polizei-nimmt-tatverdaechtigen-fest",
      "ort": "Dortmund, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-db-mitarbeiter-am-dortmunder-hauptbahnhof/"
    },
    {
      "title": "Fahrzeugangriff auf Fastnachtsmarkt in Mannheim",
      "date": "2025-03-03",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim",
      "lead": "Ein Pkw wurde während des Fastnachtsmarkts in die Fußgängerzone der Planken gesteuert — zwei Menschen starben, elf wurden verletzt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_in_Mannheim_2025",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim/"
    },
    {
      "title": "Messerangriff auf Grundschulkinder in Duisburg-Marxloh",
      "date": "2025-02-28",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-grundschulkinder-in-duisburg-marxloh",
      "lead": "Ein 21-Jähriger griff zwei Grundschulkinder im Alter von neun und zehn Jahren mit einem Messer an — sein eigener Vater entwaffnete und überwältigte ihn.",
      "source_name": "Ruhr Nachrichten",
      "source_url": "https://www.ruhrnachrichten.de/regionales/messerangriff-in-duisburg-zwei-kinder-schwer-verletzt-21-jaehriger-festgenommen-w849734-2001123189/",
      "ort": "Duisburg-Marxloh, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-grundschulkinder-in-duisburg-marxloh/"
    },
    {
      "title": "Fahrzeugangriff auf Gewerkschaftsdemonstration in München",
      "date": "2025-02-13",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen",
      "lead": "Ein Pkw wurde in einen ver.di-Demonstrationszug in der Seidlstraße gesteuert — eine Mutter und ihr zweijähriges Kind starben, 44 Personen wurden verletzt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_in_M%C3%BCnchen_2025",
      "ort": "München, Bayern",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen/"
    },
    {
      "title": "Messerangriff auf Jugendlichen an Bushaltestelle in Erfurt",
      "date": "2025-02-02",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "messerangriff-auf-jugendlichen-an-bushaltestelle-in-erfurt",
      "lead": "An einer Bushaltestelle in Erfurt stach ein 16-Jähriger auf einen 14-Jährigen ein — das Opfer musste mit dem Rettungshubschrauber abtransportiert werden, der Täter wurde freigelassen.",
      "source_name": "NIUS",
      "source_url": "https://www.nius.de/kriminalitaet/news/erfurt-messerattacke-14-jaehriger-16-jaehriger-not-operation-bushaltestelle-vieselbach/1dba3f91-fa84-4af0-a23a-c00e098a892b",
      "ort": "Erfurt-Vieselbach, Thüringen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-jugendlichen-an-bushaltestelle-in-erfurt/"
    },
    {
      "title": "Messerattacke am Leipziger Hauptbahnhof",
      "date": "2025-01-30",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-am-leipziger-hauptbahnhof",
      "lead": "Am Leipziger Hauptbahnhof — 2025 der Bahnhof mit den meisten Gewaltdelikten in Deutschland — wurde ein Mann niedergestochen.",
      "source_name": "Presseportal / Bundespolizei",
      "source_url": "https://www.presseportal.de/blaulicht/pm/74165/5979744",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerattacke-am-leipziger-hauptbahnhof/"
    },
    {
      "title": "Messerangriff auf Kindergartengruppe im Aschaffenburger Schöntal-Park",
      "date": "2025-01-22",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park",
      "lead": "Im Park Schöntal wurden ein Kleinkind und ein eingreifender Passant getötet sowie drei weitere Personen schwer verletzt — der polizeibekannte Täter befand sich trotz dokumentierter Gewaltbereitschaft ohne Aufsicht.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/aschaffenburg-messerangriff-chronologie-behoerden-100.html",
      "ort": "Aschaffenburg, Bayern",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park/"
    },
    {
      "title": "Silvester-Angriffe auf Rettungskräfte in Berlin und Leipzig",
      "date": "2024-12-31",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig",
      "lead": "In der Silvesternacht 2024/2025 wurden in Berlin 430 Personen festgenommen und 37 Polizeibeamte verletzt — in Leipzig mussten Feuerwehr und Polizei vor massivem Pyrotechnik-Beschuss taktisch zurückweichen.",
      "source_name": "Polizei Berlin",
      "source_url": "https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1517844.php",
      "ort": "Berlin und Leipzig",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig/"
    },
    {
      "title": "Fahrzeuganschlag auf den Magdeburger Weihnachtsmarkt",
      "date": "2024-12-20",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt",
      "lead": "Ein Pkw durchbrach die Sicherheitsabsperrung des Weihnachtsmarkts auf dem Alten Markt und tötete sechs Menschen — über 300 wurden verletzt, die höchste Opferzahl eines Einzelanschlags in Deutschland seit 2016.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_auf_den_Magdeburger_Weihnachtsmarkt",
      "ort": "Magdeburg, Sachsen-Anhalt",
      "relevance": 10,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt/"
    },
    {
      "title": "Bewaffnete Massenschlägerei in Mockrehna",
      "date": "2024-10-25",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "bewaffnete-massenschlagerei-in-mockrehna",
      "lead": "Rund 40 Personen prügelten mit Schaufeln, Baseballschlägern und Stöcken aufeinander ein — die Kleinstadt benötigte Polizeiverstärkung aus drei Jurisdiktionen.",
      "source_name": "MS Aktuell",
      "source_url": "https://ms-aktuell.de/welt/massenschlaegerei-mockrehna-polizeieinsatz-verletzte/",
      "ort": "Mockrehna, Nordsachsen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/bewaffnete-massenschlagerei-in-mockrehna/"
    },
    {
      "title": "Messerangriff mit Selbstjustiz-Verfolgung in Duisburg",
      "date": "2024-10-24",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "messerangriff-mit-selbstjustiz-verfolgung-in-duisburg",
      "lead": "Nach einer Messerattacke auf offener Straße verfolgten Angehörige des Opfers den fliehenden Täter im Auto und griffen das Fahrzeug mit Holzlatten an.",
      "source_name": "Presseportal / Polizei Duisburg",
      "source_url": "https://www.presseportal.de/blaulicht/pm/50510/5897629",
      "ort": "Duisburg, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-mit-selbstjustiz-verfolgung-in-duisburg/"
    },
    {
      "title": "Gruppenangriff auf Klinikpersonal nach Todesfall in Essener Notaufnahme",
      "date": "2024-09-20",
      "created": "2026-07-01T21:39:05.021Z",
      "slug": "gruppenangriff-auf-klinikpersonal-nach-todesfall-in-essener-notaufnahme",
      "lead": "Nach dem Tod einer 87-jährigen Patientin während der Reanimation stürmten mehrere Angehörige den Behandlungsraum des Elisabeth-Krankenhauses und verletzten sechs Mitarbeiter.",
      "source_name": "ZDF Nachrichten",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/essen-krankenhaus-besucher-mitarbeiter-angriff-verletzte-100.html",
      "ort": "Essen-Huttrop, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/gruppenangriff-auf-klinikpersonal-nach-todesfall-in-essener-notaufnahme/"
    },
    {
      "title": "Evakuierung des Thüringen-Parks nach Messer- und Pfefferspray-Angriff",
      "date": "2024-09-19",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "evakuierung-des-thuringen-parks-nach-messer-und-pfefferspray-angriff",
      "lead": "Nach einem Messerangriff mit gleichzeitigem Pfeffersprayeinsatz musste das gesamte Einkaufszentrum Thüringen-Park in Erfurt evakuiert und abgesperrt werden.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100493332/thueringen-park-in-erfurt-einkaufszentrum-nach-angriff-evakuiert.html",
      "ort": "Erfurt, Thüringen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/evakuierung-des-thuringen-parks-nach-messer-und-pfefferspray-angriff/"
    },
    {
      "title": "Säureattacke auf Nachbarn in Stralsund",
      "date": "2024-09-12",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "saureattacke-auf-nachbarn-in-stralsund",
      "lead": "In Stralsund attackierte ein 42-Jähriger seinen 34-jährigen Nachbarn nachts mit Säure und verursachte lebensbedrohliche Verätzungen — die Staatsanwaltschaft klagte wegen versuchten Mordes mit Heimtücke an.",
      "source_name": "t-online.de",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100488522/stralsund-saeure-attacke-opfer-schwebt-in-lebensgefahr.html",
      "ort": "Stralsund, Mecklenburg-Vorpommern",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/saureattacke-auf-nachbarn-in-stralsund/"
    },
    {
      "title": "Hochzeitsfeier endet in Massenschlägerei mit Messereinsatz in Wuppertal",
      "date": "2024-08-31",
      "created": "2026-07-01T21:39:05.020Z",
      "slug": "hochzeitsfeier-endet-in-massenschlagerei-mit-messereinsatz-in-wuppertal",
      "lead": "Eine Hochzeitsfeier in Wuppertal-Elberfeld eskalierte zu einer Massenschlägerei mit rund 60 Beteiligten, bei der ein 23-Jähriger Polizisten mit einem Messer bedrohte.",
      "source_name": "Wuppertaler Rundschau",
      "source_url": "https://www.wuppertaler-rundschau.de/stadtteile/suedstadt/hochzeitsfeier-in-wuppertal-endet-mit-massenschlaegerei_aid-118512017",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/hochzeitsfeier-endet-in-massenschlagerei-mit-messereinsatz-in-wuppertal/"
    },
    {
      "title": "Terroranschlag auf dem Solinger Stadtfest",
      "date": "2024-08-23",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-dem-solinger-stadtfest",
      "lead": "Beim Stadtfest zum 650-jährigen Jubiläum Solingens wurden drei Menschen durch Messerstiche getötet und acht verletzt — der IS reklamierte die Tat, der Täter hätte nach Dublin-Verordnung überstellt werden müssen.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messeranschlag_in_Solingen",
      "ort": "Solingen, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-dem-solinger-stadtfest/"
    },
    {
      "title": "Massenschlägerei mit improvisierten Waffen bei Hochzeit in Schleswig",
      "date": "2024-08-12",
      "created": "2026-07-01T21:39:05.019Z",
      "slug": "massenschlagerei-mit-improvisierten-waffen-bei-hochzeit-in-schleswig",
      "lead": "Bei einer Hochzeitsfeier in Schleswig eskalierte eine Schlägerei mit rund 60 Beteiligten, die mit Schaufeln, Fahrradschläuchen und Baseballschlägern aufeinander losgingen.",
      "source_name": "foerde.news",
      "source_url": "https://www.foerde.news/blaulicht/nach-massenschlaegerei-mit-rund-60-beteiligten-personen-im-kattenhunder-weg-polizei-ermittelt.html",
      "ort": "Schleswig, Schleswig-Holstein",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/massenschlagerei-mit-improvisierten-waffen-bei-hochzeit-in-schleswig/"
    },
    {
      "title": "Axt- und Hammerangriff im ICE bei Straßkirchen",
      "date": "2024-08-08",
      "created": "2026-07-01T21:39:05.019Z",
      "slug": "axt-und-hammerangriff-im-ice-bei-strasskirchen",
      "lead": "In einem voll besetzten ICE mit rund 430 Fahrgästen griff ein Reisender mehrere Menschen mit Hammer und Axt an — ein Mitreisender konnte den Angreifer überwältigen.",
      "source_name": "ZDF heute",
      "source_url": "https://www.zdfheute.de/panorama/kriminalitaet/angriff-ice-bahn-bayern-verletzte-100.html",
      "ort": "Straßkirchen, Niederbayern",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/axt-und-hammerangriff-im-ice-bei-strasskirchen/"
    },
    {
      "title": "Kaskadierende Gewalt im Dortmunder Freibad Volkspark",
      "date": "2024-08-06",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "kaskadierende-gewalt-im-dortmunder-freibad-volkspark",
      "lead": "Im Dortmunder Freibad Volkspark löste eine Jugendschlägerei eine Kette von vier getrennten Gewaltakten aus, die sich über den gesamten Abend und mehrere Stadtteile erstreckte.",
      "source_name": "Ruhr Nachrichten",
      "source_url": "https://www.ruhrnachrichten.de/dortmund/polizeieinsatz-im-freibad-am-bvb-stadion-notruf-wegen-schlaegerei-w919892-2001318169/",
      "ort": "Dortmund, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/kaskadierende-gewalt-im-dortmunder-freibad-volkspark/"
    },
    {
      "title": "Serielle Fahrzeugangriffe auf Frauen in Essen und Köln",
      "date": "2024-08-05",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln",
      "lead": "Ein Taxifahrer fuhr am selben Abend in zwei Städten gezielt weibliche Fußgängerinnen an — in Essen erlitt eine Frau lebensbedrohliche Verletzungen, in Köln wurden vier weitere Frauen verletzt.",
      "source_name": "Taxi Times",
      "source_url": "https://taxi-times.com/taxifahrer-faehrt-passantinnen-in-essen-und-koeln-an-das-geschah-wirklich/",
      "ort": "Essen und Köln, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln/"
    },
    {
      "title": "Femizid in Berlin-Friedrichsfelde trotz behördlicher Hilfesuche",
      "date": "2024-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche",
      "lead": "Eine 28-jährige Frau wurde von ihrem ehemaligen Partner vor ihrer Wohnung getötet — sie hatte zuvor Schutz bei den Behörden gesucht.",
      "source_name": "One Billion Rising Deutschland",
      "source_url": "https://www.onebillionrising.de/femizid-opfer-meldungen-2024/",
      "ort": "Berlin-Friedrichsfelde",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche/"
    },
    {
      "title": "Gruppengewalt gegen Jugendliche im Berliner Sommerbad",
      "date": "2024-07-06",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "gruppengewalt-gegen-jugendliche-im-berliner-sommerbad",
      "lead": "Rund 20 Jugendliche griffen zwei Brüder im Sommerbad Gropiusstadt an — die erste erzwungene Frühschließung eines Berliner Freibads in der Saison 2024.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/gruppe-schlagt-auf-zwei-bruder-ein-freibad-in-berlin-neukolln-nach-randale-vorzeitig-geschlossen-12060092.html",
      "ort": "Berlin-Neukölln",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/gruppengewalt-gegen-jugendliche-im-berliner-sommerbad/"
    },
    {
      "title": "Angriff auf DRK-Sanitäter bei Patientenversorgung in Neukölln",
      "date": "2024-07-02",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "angriff-auf-drk-sanitater-bei-patientenversorgung-in-neukolln",
      "lead": "Ein DRK-Sanitäter wurde während der Versorgung einer bewusstlosen Patientin auf offener Straße von Umstehenden attackiert und musste selbst ins Krankenhaus.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/sanitater-musste-ins-krankenhaus-rettungskrafte-bei-einsatz-in-berlin-neukolln-angegriffen-11952593.html",
      "ort": "Berlin-Neukölln",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/angriff-auf-drk-sanitater-bei-patientenversorgung-in-neukolln/"
    },
    {
      "title": "Messerangriff auf Bundespolizisten am Bahnhof Lauf",
      "date": "2024-06-30",
      "created": "2026-07-01T21:39:05.018Z",
      "slug": "messerangriff-auf-bundespolizisten-am-bahnhof-lauf",
      "lead": "Am Bahnhof Lauf an der Pegnitz griff ein 34-Jähriger drei Bundespolizisten mit einem Messer an — der Angreifer war trotz abgelehntem Asylantrag und polizeilicher Vorgeschichte nicht in Gewahrsam.",
      "source_name": "Bayerisches Staatsministerium der Justiz",
      "source_url": "https://www.justiz.bayern.de/gerichte-und-behoerden/staatsanwaltschaft/nuernberg-fuerth/presse/2025/1.php",
      "ort": "Lauf an der Pegnitz, Bayern",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-auf-bundespolizisten-am-bahnhof-lauf/"
    },
    {
      "title": "Angriffsserie während der EM-Übertragung in Wolmirstedt",
      "date": "2024-06-14",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt",
      "lead": "Während des EM-Eröffnungsspiels tötete ein Angreifer zunächst einen Mann in einem Wohnhaus und griff dann eine private Gartenparty an — die Polizei erschoss den Täter.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/em-party-tote-polizei-100.html",
      "ort": "Wolmirstedt, Sachsen-Anhalt",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt/"
    },
    {
      "title": "Messerattacke im Regionalzug bei Saarbrücken",
      "date": "2024-06-10",
      "created": "2026-07-01T21:39:05.017Z",
      "slug": "messerattacke-im-regionalzug-bei-saarbrucken",
      "lead": "In einem Regionalzug kurz vor dem Saarbrücker Hauptbahnhof wurde ein 21-jähriger Fahrgast ohne jede Vorinteraktion von einem Unbekannten in den Hals gestochen.",
      "source_name": "Presseportal / Bundespolizei Trier",
      "source_url": "https://www.presseportal.de/blaulicht/pm/70138/5798275",
      "ort": "Saarbrücken",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-im-regionalzug-bei-saarbrucken/"
    },
    {
      "title": "Terroranschlag auf Kundgebung am Mannheimer Marktplatz",
      "date": "2024-05-31",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-kundgebung-am-mannheimer-marktplatz",
      "lead": "Bei einem islamistisch motivierten Messerangriff auf eine politische Kundgebung wurde ein Polizeibeamter getötet und fünf Personen schwer verletzt — gegen den Täter bestand seit 2019 ein offener Haftbefehl.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Mannheim_am_31._Mai_2024",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-kundgebung-am-mannheimer-marktplatz/"
    },
    {
      "title": "Flusssäure-Anschlag an der Wohnungstür in Rosenheim",
      "date": "2024-05-13",
      "created": "2026-07-01T21:39:05.017Z",
      "slug": "flusssaure-anschlag-an-der-wohnungstur-in-rosenheim",
      "lead": "Ein maskierter Angreifer klingelte an einer Wohnung in Rosenheim und schüttete dem Öffnenden Flusssäure ins Gesicht — ein industriell beschaffter Gefahrstoff als Angriffswaffe.",
      "source_name": "Bayerische Polizei",
      "source_url": "https://www.polizei.bayern.de/aktuelles/pressemitteilungen/067783/index.html",
      "ort": "Rosenheim, Bayern",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/flusssaure-anschlag-an-der-wohnungstur-in-rosenheim/"
    },
    {
      "title": "Dreistündige Massenschlägerei am Tollensesee",
      "date": "2024-05-09",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "dreistundige-massenschlagerei-am-tollensesee",
      "lead": "Bei der Eröffnung einer Strandbar am Tollensesee eskalierte eine Schlägerei mit rund 40 Beteiligten, die sich über drei Stunden hinzog — trotz Polizeipräsenz.",
      "source_name": "Nordkurier",
      "source_url": "https://www.nordkurier.de/regional/neubrandenburg/schlaegerei-mit-verletzten-bei-eroeffnung-von-strandbar-in-neubrandenburg-2514061",
      "ort": "Neubrandenburg, Mecklenburg-Vorpommern",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/dreistundige-massenschlagerei-am-tollensesee/"
    },
    {
      "title": "Tötung eines Forensik-Arztes in Wasserburg am Inn",
      "date": "2024-04-08",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totung-eines-forensik-arztes-in-wasserburg-am-inn",
      "lead": "Ein ehemaliger Patient erstach einen Oberarzt der forensischen Psychiatrie auf dem Klinikgelände — der Arzt hatte in einem Strafverfahren ein Gutachten gegen ihn erstellt.",
      "source_name": "Bayerische Polizei",
      "source_url": "https://www.polizei.bayern.de/aktuelles/pressemitteilungen/065292/index.html",
      "ort": "Wasserburg am Inn, Bayern",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/totung-eines-forensik-arztes-in-wasserburg-am-inn/"
    },
    {
      "title": "Messerangriff in Regionalbahn bei Niederlahnstein",
      "date": "2024-04-08",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "messerangriff-in-regionalbahn-bei-niederlahnstein",
      "lead": "In der Regionalbahn RB10 zwischen Koblenz und Lahnstein wurde ein 20-jähriger Fahrgast mit einem Messer schwer verletzt — der Bahnhof wurde gesperrt, ein Großeinsatz ausgelöst.",
      "source_name": "56aktuell.de",
      "source_url": "https://56aktuell.de/grosseinsatz-in-lahnstein-messerattacke-in-der-regionalbahn-ein-schwerverletzter/",
      "ort": "Niederlahnstein, Rheinland-Pfalz",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-in-regionalbahn-bei-niederlahnstein/"
    },
    {
      "title": "Schulattacke am Wilhelm-Dörpfeld-Gymnasium in Wuppertal",
      "date": "2024-02-22",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal",
      "lead": "Ein 17-jähriger Schüler verletzte vier Mitschüler mit einem Klappmesser im Oberstufenraum — ein Lehrer konnte den Angreifer zum Ablegen der Waffe bewegen.",
      "source_name": "Euronews",
      "source_url": "https://www.euronews.com/2024/02/22/four-injured-in-school-stabbing-in-western-germany",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal/"
    },
    {
      "title": "Doppelmord am Oberhausener Hauptbahnhof durch Minderjährige",
      "date": "2024-02-10",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige",
      "lead": "Zwei Basketballspieler wurden am Oberhausener Hauptbahnhof von einer Gruppe Minderjähriger mit Messerstichen getötet — die Täter waren zwischen 14 und 16 Jahre alt.",
      "source_name": "Sportschau / WDR",
      "source_url": "https://www.sportschau.de/regional/wdr/wdr-messerattacke-in-oberhausen-zweiter-ukrainischer-basketballer-gestorben-102.html",
      "ort": "Oberhausen, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige/"
    },
    {
      "title": "Gewalt in der Notaufnahme des Sana-Klinikums Berlin",
      "date": "2024-01-01",
      "created": "2026-07-01T21:39:05.016Z",
      "slug": "gewalt-in-der-notaufnahme-des-sana-klinikums-berlin",
      "lead": "In der Notaufnahme des Sana-Klinikums schlugen zwei Angehörige einen behandelnden Arzt und eine Krankenschwester zusammen — weil ihnen die Wartezeit bei einer Bagatellverletzung zu lang war.",
      "source_name": "Amtsgericht Tiergarten Berlin",
      "source_url": "https://www.berlin.de/gerichte/presse/pressemitteilungen-der-ordentlichen-gerichtsbarkeit/2025/pressemitteilung.1539774.php",
      "ort": "Berlin-Lichtenberg",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/gewalt-in-der-notaufnahme-des-sana-klinikums-berlin/"
    },
    {
      "title": "Straßenschlacht bei eritreischer Veranstaltung in Stuttgart",
      "date": "2023-09-16",
      "created": "2026-07-01T21:39:05.015Z",
      "slug": "strassenschlacht-bei-eritreischer-veranstaltung-in-stuttgart",
      "lead": "Bei einer Veranstaltung im Stuttgarter Stadtteil Hallschlag wurden 39 Polizeibeamte durch nagelbesetzte Holzlatten, Metallstangen und Wurfgeschosse verletzt.",
      "source_name": "Stuttgarter Zeitung",
      "source_url": "https://www.stuttgarter-zeitung.de/inhalt.prozess-nach-randale-in-stuttgart-hallschlag-drei-jahre-und-neun-monate-haft-fuer-angriff-auf-polizisten.3e634b4e-5356-492e-8cad-e9e67c323013.html",
      "ort": "Stuttgart-Hallschlag, Baden-Württemberg",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/strassenschlacht-bei-eritreischer-veranstaltung-in-stuttgart/"
    },
    {
      "title": "Freispruch trotz Geständnis vor US-Militärgericht in Wittlich",
      "date": "2023-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich",
      "lead": "Nach einer tödlichen Messerstecherei auf einer Kirmes wurde der geständige Täter von einem US-Militärgericht freigesprochen — wegen eines Übersetzungsfehlers in der Anklageschrift.",
      "source_name": "Legal Tribune Online",
      "source_url": "https://www.lto.de/recht/hintergruende/h/freispruch-trotz-gestaendnis-wittlich-us-militaergericht-justice",
      "ort": "Wittlich, Rheinland-Pfalz",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich/"
    },
    {
      "title": "Ausschreitungen beim Eritrea-Festival in Gießen",
      "date": "2023-07-08",
      "created": "2026-07-01T21:39:04.999Z",
      "slug": "ausschreitungen-beim-eritrea-festival-in-giessen",
      "lead": "Bei einem Diaspora-Festival in Gießen eskalierte ein transnationaler politischer Konflikt zu massiver Straßengewalt gegen über tausend eingesetzte Polizeikräfte.",
      "source_name": "hessenschau.de",
      "source_url": "https://www.hessenschau.de/gesellschaft/eritrea-festival-in-giessen-2023-weitere-bewaehrungsstrafen-nach-ausschreitungen-v1,eritrea-festival-urteil-100.html",
      "ort": "Gießen, Hessen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/ausschreitungen-beim-eritrea-festival-in-giessen/"
    },
    {
      "title": "Massenschlägerei im Mannheimer Herzogenriedbad",
      "date": "2023-06-18",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "massenschlagerei-im-mannheimer-herzogenriedbad",
      "lead": "Eine Auseinandersetzung zwischen Kindern eskalierte innerhalb von Minuten zu einer Massenschlägerei mit über 40 Beteiligten und Messereinsatz in einem öffentlichen Freibad.",
      "source_name": "RNF",
      "source_url": "https://www.rnf.de/mannheim-verletzte-bei-schlaegerei-von-rund-40-personen-im-herzogenriedbad-mann-mit-messer-verletzt-353899/",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/massenschlagerei-im-mannheimer-herzogenriedbad/"
    },
    {
      "title": "Tötungsdelikt in fränkischem Kinderheim",
      "date": "2023-04-03",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totungsdelikt-in-frankischem-kinderheim",
      "lead": "Ein zehnjähriges Mädchen wurde in einem Kinderheim getötet — die Ermittlungen ergaben ein Versagen der Schutzeinrichtung bei der Verhinderung eines externen Eindringens.",
      "source_name": "Frankenpost",
      "source_url": "https://www.frankenpost.de/inhalt.wunsiedel-mord-an-maedchen-40-koepfige-soko-ermittelt.25af368f-79c4-4439-a675-0bbf6c266d6e.html",
      "ort": "Wunsiedel, Bayern",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/totungsdelikt-in-frankischem-kinderheim/"
    },
    {
      "title": "Massenschießerei in Hamburger Königreichssaal",
      "date": "2023-03-09",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "massenschiesserei-in-hamburger-konigreichssaal",
      "lead": "Bei einem Angriff auf eine Gemeindeversammlung der Zeugen Jehovas wurden sieben Menschen erschossen und neun schwer verletzt — der Schütze besaß eine legale Waffenerlaubnis.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amoktat_in_Hamburg-Alsterdorf_2023",
      "ort": "Hamburg-Alsterdorf",
      "relevance": 10,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenschiesserei-in-hamburger-konigreichssaal/"
    },
    {
      "title": "Messerangriff im Regionalzug bei Brokstedt",
      "date": "2023-01-25",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "messerangriff-im-regionalzug-bei-brokstedt",
      "lead": "In einem Regionalzug zwischen Kiel und Hamburg wurden zwei Fahrgäste getötet und fünf weitere verletzt — der Täter war sechs Tage zuvor aus der Untersuchungshaft entlassen worden.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerattacke_in_Brokstedt_am_25._Januar_2023",
      "ort": "Brokstedt, Schleswig-Holstein",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-im-regionalzug-bei-brokstedt/"
    }
  ]
}
;
