window.NOVA_DATA =
{
  "generated": "2026-07-01T20:14:30.547Z",
  "items": [
    {
      "title": "Freibad-Räumung nach Eskalation in Bochum-Werne",
      "date": "2026-06-24",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "freibad-raumung-nach-eskalation-in-bochum-werne",
      "lead": "Ein Streit zwischen zwei Badegästen führte zur Räumung von 4.000 Besuchern unter Polizeischutz — am Folgetag wurden in allen Bochumer Bädern Ausweiskontrollen eingeführt.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_101312784/freibad-pruegelei-in-bochum-sorgt-fuer-raeumung-grosser-polizei-einsatz.html",
      "ort": "Bochum-Werne, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/freibad-raumung-nach-eskalation-in-bochum-werne/"
    },
    {
      "title": "Amokfahrt in der Leipziger Grimmaischen Straße",
      "date": "2026-05-04",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "amokfahrt-in-der-leipziger-grimmaischen-strasse",
      "lead": "Ein SUV durchfuhr 450 Meter der Leipziger Fußgängerzone mit geschätzten 70-80 km/h — erst vorhandene Poller in einer Seitenstraße stoppten das Fahrzeug.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_von_Leipzig",
      "ort": "Leipzig, Sachsen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/amokfahrt-in-der-leipziger-grimmaischen-strasse/"
    },
    {
      "title": "Arzt in Darmstädter Klinikum bewusstlos geschlagen",
      "date": "2025-12-14",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "arzt-in-darmstadter-klinikum-bewusstlos-geschlagen",
      "lead": "Ein 55-Jähriger schlug einen diensthabenden Arzt im Klinikum Darmstadt mit Schlägen gegen den Kopf bewusstlos — weil sein Begleiter nicht als Notfall eingestuft wurde.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/mit-kopfverletzungen-auf-intensivstation-mann-attackiert-arzt-im-klinikum-darmstadt-v1,arzt-zusammengeschlagen-100.html",
      "ort": "Darmstadt, Hessen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/arzt-in-darmstadter-klinikum-bewusstlos-geschlagen/"
    },
    {
      "title": "Messerattacke an Leipziger Zentralhaltestelle",
      "date": "2025-09-01",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "messerattacke-an-leipziger-zentralhaltestelle",
      "lead": "An der Zentralhaltestelle direkt vor dem Leipziger Hauptbahnhof wurde ein 40-Jähriger am Samstagmorgen niedergestochen.",
      "source_name": "Blaulicht-Ticker",
      "source_url": "https://www.blaulicht-ticker.de/leipzig/messerangriff-an-zentralhaltestelle-in-leipzig-am-samstagmorgen-3050290",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-an-leipziger-zentralhaltestelle/"
    },
    {
      "title": "Massenschlägerei bei Kampfsportveranstaltung in Ense",
      "date": "2025-08-10",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "massenschlagerei-bei-kampfsportveranstaltung-in-ense",
      "lead": "Bei einer Kampfsportveranstaltung in einer Industriehalle eskalierte ein Fanstreit zu einer Massenschlägerei mit etwa 100 Beteiligten.",
      "source_name": "Presseportal / Kreispolizeibehörde Soest",
      "source_url": "https://www.presseportal.de/blaulicht/pm/65855/6093599",
      "ort": "Ense, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/massenschlagerei-bei-kampfsportveranstaltung-in-ense/"
    },
    {
      "title": "Sanitäter im Rettungswagen angegriffen in Karlsruhe",
      "date": "2025-06-28",
      "created": "2026-07-01T20:14:30.531Z",
      "slug": "sanitater-im-rettungswagen-angegriffen-in-karlsruhe",
      "lead": "Ein Patient attackierte während des Transports einen Sanitäter im Inneren des Rettungswagens und verletzte auch einen intervenierenden Polizeibeamten.",
      "source_name": "ka-news.de",
      "source_url": "https://www.ka-news.de/karlsruhe/polizeibericht-angriff-im-rettungswagen-verletzt-sanitaeter-und-polizist-in-karlsruhe-114589670",
      "ort": "Karlsruhe, Baden-Württemberg",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/sanitater-im-rettungswagen-angegriffen-in-karlsruhe/"
    },
    {
      "title": "Soziale-Medien-getriggerte Messerattacke am Frankfurter Hauptbahnhof",
      "date": "2025-06-15",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof",
      "lead": "Auf dem Vorplatz des Frankfurter Hauptbahnhofs wurde ein 18-Jähriger von einer Gruppe niedergestochen — Auslöser war offenbar ein TikTok-Video.",
      "source_name": "t-online",
      "source_url": "https://www.t-online.de/nachrichten/panorama/kriminalitaet/id_100748324/frankfurt-hauptbahnhof-messer-attacke-18-jaehriger-schwer-verletzt.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/soziale-medien-getriggerte-messerattacke-am-frankfurter-hauptbahnhof/"
    },
    {
      "title": "Massenconfrontation mit Waffenarsenal in Dortmund-Nordstadt",
      "date": "2025-05-26",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt",
      "lead": "Ein Streit zwischen zwei kleinen Gruppen eskalierte auf der Schleswiger Straße zu einer Massenkonfrontation mit 250 bis 300 Beteiligten — mit Messern, Machete, Axt und Schusswaffe.",
      "source_name": "Rundblick Unna",
      "source_url": "https://rundblick-unna.de/2026/05/27/gewalteskalation-in-do-nord-mit-messern-machete-axt-schusswaffe-sieben-beteiligte-mehrere-hundert-gaffer/",
      "ort": "Dortmund-Nordstadt, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenconfrontation-mit-waffenarsenal-in-dortmund-nordstadt/"
    },
    {
      "title": "Massenangriff am Hamburger Hauptbahnhof",
      "date": "2025-05-23",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "massenangriff-am-hamburger-hauptbahnhof",
      "lead": "Am Hamburger Hauptbahnhof wurden 15 Reisende niedergestochen — der Täter war einen Tag zuvor aus einer psychiatrischen Einrichtung entlassen worden.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_am_Hamburger_Hauptbahnhof_2025",
      "ort": "Hamburg",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenangriff-am-hamburger-hauptbahnhof/"
    },
    {
      "title": "Elfjährige Schülerin ersticht Mitschüler in Remscheid",
      "date": "2025-05-22",
      "created": "2026-07-01T20:14:30.530Z",
      "slug": "elfjahrige-schulerin-ersticht-mitschuler-in-remscheid",
      "lead": "Ein elfjähriges Kind verletzte einen 13-jährigen Mitschüler mit einem Küchenmesser — das Kind liegt unterhalb der Strafmündigkeitsgrenze.",
      "source_name": "Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/gesellschaft/panorama/nach-messerangriff-auf-13-jahrigen-polizei-in-remscheid-ubergibt-11-jahrigen-wieder-den-eltern-13740730.html",
      "ort": "Remscheid, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/elfjahrige-schulerin-ersticht-mitschuler-in-remscheid/"
    },
    {
      "title": "Islamistischer Anschlag mit verkleideter Stockwaffe in Bielefeld",
      "date": "2025-05-18",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld",
      "lead": "Ein Angreifer tarnte sich als Gehbehinderter, nutzte einen zu einer Stichwaffe umgebauten Gehstock und attackierte in den Morgenstunden fünf Personen vor einer Gaststätte.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Bielefeld_2025",
      "ort": "Bielefeld, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/islamistischer-anschlag-mit-verkleideter-stockwaffe-in-bielefeld/"
    },
    {
      "title": "Messerattacke auf Bahnsteig des Frankfurter Hauptbahnhofs",
      "date": "2025-03-15",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs",
      "lead": "Auf dem Bahnsteig 104 des Frankfurter Hauptbahnhofs stach ein 19-Jähriger auf einen 25-Jährigen ein — einer von mehreren Messervorfällen am selben Bahnhof im Jahr 2025.",
      "source_name": "hessenschau",
      "source_url": "https://www.hessenschau.de/panorama/messerangriff-am-gleis-im-frankfurter-hauptbahnhof-v1,kurz-angriff-324.html",
      "ort": "Frankfurt am Main, Hessen",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerattacke-auf-bahnsteig-des-frankfurter-hauptbahnhofs/"
    },
    {
      "title": "Fahrzeugangriff auf Fastnachtsmarkt in Mannheim",
      "date": "2025-03-03",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim",
      "lead": "Ein Pkw wurde während des Fastnachtsmarkts in die Fußgängerzone der Planken gesteuert — zwei Menschen starben, elf wurden verletzt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amokfahrt_in_Mannheim_2025",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-fastnachtsmarkt-in-mannheim/"
    },
    {
      "title": "Messerangriff auf Grundschulkinder in Duisburg-Marxloh",
      "date": "2025-02-28",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-grundschulkinder-in-duisburg-marxloh",
      "lead": "Ein 21-Jähriger griff zwei Grundschulkinder im Alter von neun und zehn Jahren mit einem Messer an — sein eigener Vater entwaffnete und überwältigte ihn.",
      "source_name": "Ruhr Nachrichten",
      "source_url": "https://www.ruhrnachrichten.de/regionales/messerangriff-in-duisburg-zwei-kinder-schwer-verletzt-21-jaehriger-festgenommen-w849734-2001123189/",
      "ort": "Duisburg-Marxloh, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-grundschulkinder-in-duisburg-marxloh/"
    },
    {
      "title": "Fahrzeugangriff auf Gewerkschaftsdemonstration in München",
      "date": "2025-02-13",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen",
      "lead": "Ein Pkw wurde in einen ver.di-Demonstrationszug in der Seidlstraße gesteuert — eine Mutter und ihr zweijähriges Kind starben, 44 Personen wurden verletzt.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_in_M%C3%BCnchen_2025",
      "ort": "München, Bayern",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeugangriff-auf-gewerkschaftsdemonstration-in-munchen/"
    },
    {
      "title": "Messerattacke am Leipziger Hauptbahnhof",
      "date": "2025-01-30",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerattacke-am-leipziger-hauptbahnhof",
      "lead": "Am Leipziger Hauptbahnhof — 2025 der Bahnhof mit den meisten Gewaltdelikten in Deutschland — wurde ein Mann niedergestochen.",
      "source_name": "Presseportal / Bundespolizei",
      "source_url": "https://www.presseportal.de/blaulicht/pm/74165/5979744",
      "ort": "Leipzig, Sachsen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerattacke-am-leipziger-hauptbahnhof/"
    },
    {
      "title": "Messerangriff auf Kindergartengruppe im Aschaffenburger Schöntal-Park",
      "date": "2025-01-22",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park",
      "lead": "Im Park Schöntal wurden ein Kleinkind und ein eingreifender Passant getötet sowie drei weitere Personen schwer verletzt — der polizeibekannte Täter befand sich trotz dokumentierter Gewaltbereitschaft ohne Aufsicht.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/kriminalitaet/aschaffenburg-messerangriff-chronologie-behoerden-100.html",
      "ort": "Aschaffenburg, Bayern",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-auf-kindergartengruppe-im-aschaffenburger-schontal-park/"
    },
    {
      "title": "Silvester-Angriffe auf Rettungskräfte in Berlin und Leipzig",
      "date": "2024-12-31",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig",
      "lead": "In der Silvesternacht 2024/2025 wurden in Berlin 430 Personen festgenommen und 37 Polizeibeamte verletzt — in Leipzig mussten Feuerwehr und Polizei vor massivem Pyrotechnik-Beschuss taktisch zurückweichen.",
      "source_name": "Polizei Berlin",
      "source_url": "https://www.berlin.de/polizei/polizeimeldungen/2025/pressemitteilung.1517844.php",
      "ort": "Berlin und Leipzig",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/silvester-angriffe-auf-rettungskrafte-in-berlin-und-leipzig/"
    },
    {
      "title": "Fahrzeuganschlag auf den Magdeburger Weihnachtsmarkt",
      "date": "2024-12-20",
      "created": "2026-07-01T20:14:30.529Z",
      "slug": "fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt",
      "lead": "Ein Pkw durchbrach die Sicherheitsabsperrung des Weihnachtsmarkts auf dem Alten Markt und tötete sechs Menschen — über 300 wurden verletzt, die höchste Opferzahl eines Einzelanschlags in Deutschland seit 2016.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Anschlag_auf_den_Magdeburger_Weihnachtsmarkt",
      "ort": "Magdeburg, Sachsen-Anhalt",
      "relevance": 10,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/fahrzeuganschlag-auf-den-magdeburger-weihnachtsmarkt/"
    },
    {
      "title": "Bewaffnete Massenschlägerei in Mockrehna",
      "date": "2024-10-25",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "bewaffnete-massenschlagerei-in-mockrehna",
      "lead": "Rund 40 Personen prügelten mit Schaufeln, Baseballschlägern und Stöcken aufeinander ein — die Kleinstadt benötigte Polizeiverstärkung aus drei Jurisdiktionen.",
      "source_name": "MS Aktuell",
      "source_url": "https://ms-aktuell.de/welt/massenschlaegerei-mockrehna-polizeieinsatz-verletzte/",
      "ort": "Mockrehna, Nordsachsen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/bewaffnete-massenschlagerei-in-mockrehna/"
    },
    {
      "title": "Messerangriff mit Selbstjustiz-Verfolgung in Duisburg",
      "date": "2024-10-24",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "messerangriff-mit-selbstjustiz-verfolgung-in-duisburg",
      "lead": "Nach einer Messerattacke auf offener Straße verfolgten Angehörige des Opfers den fliehenden Täter im Auto und griffen das Fahrzeug mit Holzlatten an.",
      "source_name": "Presseportal / Polizei Duisburg",
      "source_url": "https://www.presseportal.de/blaulicht/pm/50510/5897629",
      "ort": "Duisburg, Nordrhein-Westfalen",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/messerangriff-mit-selbstjustiz-verfolgung-in-duisburg/"
    },
    {
      "title": "Terroranschlag auf dem Solinger Stadtfest",
      "date": "2024-08-23",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-dem-solinger-stadtfest",
      "lead": "Beim Stadtfest zum 650-jährigen Jubiläum Solingens wurden drei Menschen durch Messerstiche getötet und acht verletzt — der IS reklamierte die Tat, der Täter hätte nach Dublin-Verordnung überstellt werden müssen.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messeranschlag_in_Solingen",
      "ort": "Solingen, Nordrhein-Westfalen",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-dem-solinger-stadtfest/"
    },
    {
      "title": "Serielle Fahrzeugangriffe auf Frauen in Essen und Köln",
      "date": "2024-08-05",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln",
      "lead": "Ein Taxifahrer fuhr am selben Abend in zwei Städten gezielt weibliche Fußgängerinnen an — in Essen erlitt eine Frau lebensbedrohliche Verletzungen, in Köln wurden vier weitere Frauen verletzt.",
      "source_name": "Taxi Times",
      "source_url": "https://taxi-times.com/taxifahrer-faehrt-passantinnen-in-essen-und-koeln-an-das-geschah-wirklich/",
      "ort": "Essen und Köln, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/serielle-fahrzeugangriffe-auf-frauen-in-essen-und-koln/"
    },
    {
      "title": "Femizid in Berlin-Friedrichsfelde trotz behördlicher Hilfesuche",
      "date": "2024-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche",
      "lead": "Eine 28-jährige Frau wurde von ihrem ehemaligen Partner vor ihrer Wohnung getötet — sie hatte zuvor Schutz bei den Behörden gesucht.",
      "source_name": "One Billion Rising Deutschland",
      "source_url": "https://www.onebillionrising.de/femizid-opfer-meldungen-2024/",
      "ort": "Berlin-Friedrichsfelde",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/femizid-in-berlin-friedrichsfelde-trotz-behordlicher-hilfesuche/"
    },
    {
      "title": "Gruppengewalt gegen Jugendliche im Berliner Sommerbad",
      "date": "2024-07-06",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "gruppengewalt-gegen-jugendliche-im-berliner-sommerbad",
      "lead": "Rund 20 Jugendliche griffen zwei Brüder im Sommerbad Gropiusstadt an — die erste erzwungene Frühschließung eines Berliner Freibads in der Saison 2024.",
      "source_name": "Der Tagesspiegel",
      "source_url": "https://www.tagesspiegel.de/berlin/gruppe-schlagt-auf-zwei-bruder-ein-freibad-in-berlin-neukolln-nach-randale-vorzeitig-geschlossen-12060092.html",
      "ort": "Berlin-Neukölln",
      "relevance": 7,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/gruppengewalt-gegen-jugendliche-im-berliner-sommerbad/"
    },
    {
      "title": "Angriffsserie während der EM-Übertragung in Wolmirstedt",
      "date": "2024-06-14",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt",
      "lead": "Während des EM-Eröffnungsspiels tötete ein Angreifer zunächst einen Mann in einem Wohnhaus und griff dann eine private Gartenparty an — die Polizei erschoss den Täter.",
      "source_name": "ZDF",
      "source_url": "https://www.zdf.de/nachrichten/panorama/em-party-tote-polizei-100.html",
      "ort": "Wolmirstedt, Sachsen-Anhalt",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/angriffsserie-wahrend-der-em-ubertragung-in-wolmirstedt/"
    },
    {
      "title": "Terroranschlag auf Kundgebung am Mannheimer Marktplatz",
      "date": "2024-05-31",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "terroranschlag-auf-kundgebung-am-mannheimer-marktplatz",
      "lead": "Bei einem islamistisch motivierten Messerangriff auf eine politische Kundgebung wurde ein Polizeibeamter getötet und fünf Personen schwer verletzt — gegen den Täter bestand seit 2019 ein offener Haftbefehl.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerangriff_in_Mannheim_am_31._Mai_2024",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/terroranschlag-auf-kundgebung-am-mannheimer-marktplatz/"
    },
    {
      "title": "Tötung eines Forensik-Arztes in Wasserburg am Inn",
      "date": "2024-04-08",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totung-eines-forensik-arztes-in-wasserburg-am-inn",
      "lead": "Ein ehemaliger Patient erstach einen Oberarzt der forensischen Psychiatrie auf dem Klinikgelände — der Arzt hatte in einem Strafverfahren ein Gutachten gegen ihn erstellt.",
      "source_name": "Bayerische Polizei",
      "source_url": "https://www.polizei.bayern.de/aktuelles/pressemitteilungen/065292/index.html",
      "ort": "Wasserburg am Inn, Bayern",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/totung-eines-forensik-arztes-in-wasserburg-am-inn/"
    },
    {
      "title": "Schulattacke am Wilhelm-Dörpfeld-Gymnasium in Wuppertal",
      "date": "2024-02-22",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal",
      "lead": "Ein 17-jähriger Schüler verletzte vier Mitschüler mit einem Klappmesser im Oberstufenraum — ein Lehrer konnte den Angreifer zum Ablegen der Waffe bewegen.",
      "source_name": "Euronews",
      "source_url": "https://www.euronews.com/2024/02/22/four-injured-in-school-stabbing-in-western-germany",
      "ort": "Wuppertal, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/schulattacke-am-wilhelm-dorpfeld-gymnasium-in-wuppertal/"
    },
    {
      "title": "Doppelmord am Oberhausener Hauptbahnhof durch Minderjährige",
      "date": "2024-02-10",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige",
      "lead": "Zwei Basketballspieler wurden am Oberhausener Hauptbahnhof von einer Gruppe Minderjähriger mit Messerstichen getötet — die Täter waren zwischen 14 und 16 Jahre alt.",
      "source_name": "Sportschau / WDR",
      "source_url": "https://www.sportschau.de/regional/wdr/wdr-messerattacke-in-oberhausen-zweiter-ukrainischer-basketballer-gestorben-102.html",
      "ort": "Oberhausen, Nordrhein-Westfalen",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/doppelmord-am-oberhausener-hauptbahnhof-durch-minderjahrige/"
    },
    {
      "title": "Freispruch trotz Geständnis vor US-Militärgericht in Wittlich",
      "date": "2023-08-01",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich",
      "lead": "Nach einer tödlichen Messerstecherei auf einer Kirmes wurde der geständige Täter von einem US-Militärgericht freigesprochen — wegen eines Übersetzungsfehlers in der Anklageschrift.",
      "source_name": "Legal Tribune Online",
      "source_url": "https://www.lto.de/recht/hintergruende/h/freispruch-trotz-gestaendnis-wittlich-us-militaergericht-justice",
      "ort": "Wittlich, Rheinland-Pfalz",
      "relevance": 8,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/freispruch-trotz-gestandnis-vor-us-militargericht-in-wittlich/"
    },
    {
      "title": "Massenschlägerei im Mannheimer Herzogenriedbad",
      "date": "2023-06-18",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "massenschlagerei-im-mannheimer-herzogenriedbad",
      "lead": "Eine Auseinandersetzung zwischen Kindern eskalierte innerhalb von Minuten zu einer Massenschlägerei mit über 40 Beteiligten und Messereinsatz in einem öffentlichen Freibad.",
      "source_name": "RNF",
      "source_url": "https://www.rnf.de/mannheim-verletzte-bei-schlaegerei-von-rund-40-personen-im-herzogenriedbad-mann-mit-messer-verletzt-353899/",
      "ort": "Mannheim, Baden-Württemberg",
      "relevance": 7,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/massenschlagerei-im-mannheimer-herzogenriedbad/"
    },
    {
      "title": "Tötungsdelikt in fränkischem Kinderheim",
      "date": "2023-04-03",
      "created": "2026-07-01T20:14:30.528Z",
      "slug": "totungsdelikt-in-frankischem-kinderheim",
      "lead": "Ein zehnjähriges Mädchen wurde in einem Kinderheim getötet — die Ermittlungen ergaben ein Versagen der Schutzeinrichtung bei der Verhinderung eines externen Eindringens.",
      "source_name": "Frankenpost",
      "source_url": "https://www.frankenpost.de/inhalt.wunsiedel-mord-an-maedchen-40-koepfige-soko-ermittelt.25af368f-79c4-4439-a675-0bbf6c266d6e.html",
      "ort": "Wunsiedel, Bayern",
      "relevance": 8,
      "minutes": 0,
      "href": "/neue-dimension-gewalt/totungsdelikt-in-frankischem-kinderheim/"
    },
    {
      "title": "Massenschießerei in Hamburger Königreichssaal",
      "date": "2023-03-09",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "massenschiesserei-in-hamburger-konigreichssaal",
      "lead": "Bei einem Angriff auf eine Gemeindeversammlung der Zeugen Jehovas wurden sieben Menschen erschossen und neun schwer verletzt — der Schütze besaß eine legale Waffenerlaubnis.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Amoktat_in_Hamburg-Alsterdorf_2023",
      "ort": "Hamburg-Alsterdorf",
      "relevance": 10,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/massenschiesserei-in-hamburger-konigreichssaal/"
    },
    {
      "title": "Messerangriff im Regionalzug bei Brokstedt",
      "date": "2023-01-25",
      "created": "2026-07-01T20:14:30.527Z",
      "slug": "messerangriff-im-regionalzug-bei-brokstedt",
      "lead": "In einem Regionalzug zwischen Kiel und Hamburg wurden zwei Fahrgäste getötet und fünf weitere verletzt — der Täter war sechs Tage zuvor aus der Untersuchungshaft entlassen worden.",
      "source_name": "Wikipedia",
      "source_url": "https://de.wikipedia.org/wiki/Messerattacke_in_Brokstedt_am_25._Januar_2023",
      "ort": "Brokstedt, Schleswig-Holstein",
      "relevance": 9,
      "minutes": 1,
      "href": "/neue-dimension-gewalt/messerangriff-im-regionalzug-bei-brokstedt/"
    }
  ]
}
;
