// Auto-generated by pipeline/render.mjs. Quelle: zutaten/bildgebung/articles.js.
window.BILDGEBUNG_DATA = {
  "items": [
    {
      "href": "hopfen-jenseits-vom-bier/",
      "title": "Hopfen jenseits vom Bier",
      "lead": "Die am besten erforschte Nervenpflanze Europas wird als Schlaftee verkauft. Ihr pharmakologisches Profil reicht von Anxiolyse bis Onkologie.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 3,
      "filters": [
        "ruhe"
      ]
    },
    {
      "href": "igelstachelbart-nerven-wachsen/",
      "title": "Der Pilz, der Nerven wachsen lässt",
      "lead": "Die einzige bekannte Nahrungsquelle, die Nervenwachstumsfaktor im Gehirn stimuliert, steht im Asia-Markt neben den Shiitake.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 4,
      "filters": [
        "klarheit"
      ]
    }
  ]
};
