// Auto-generated by pipeline/render.mjs. Quelle: zutaten/bildgebung/articles.js.
window.BILDGEBUNG_DATA = {
  "items": [
    {
      "href": "hopfen-jenseits-vom-bier/",
      "title": "Hopfen jenseits vom Bier",
      "lead": "Die am besten erforschte Nervenpflanze Europas wird als Schlaftee verkauft. Was die Forschung weiß und das Regal verschweigt.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 3,
      "filters": [
        "ruhe"
      ]
    },
    {
      "href": "igelstachelbart-nerven-wachsen/",
      "title": "Der Pilz, der Nerven wachsen lässt",
      "lead": "Die einzige bekannte Nahrungsquelle, die Nervenwachstumsfaktor im Gehirn stimuliert, steht im Asia-Markt neben den Shiitake.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 3,
      "filters": [
        "klarheit"
      ]
    },
    {
      "href": "spilanthol-trigeminale-aktivierung/",
      "title": "Das Molekül, das die Zunge vibrieren lässt",
      "lead": "Spilanthol aktiviert Berührungsfasern im Gesicht mit einer messbaren Frequenz von fünfzig Hertz. Die Empfindung gehört weder zum Geschmack noch zum Schmerz. Sie gehört zum Tastsinn.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 3,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "adaptogene-ueberblick/",
      "title": "Der nützlichste Begriff, der nichts bedeutet",
      "lead": "Ein sowjetischer Toxikologe hat 1947 ein Wort erfunden, das heute auf jeder zweiten Supplement-Packung steht. Die Pflanzen dahinter sind interessant. Das Wort ist das Problem.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ruhe"
      ]
    },
    {
      "href": "ashwagandha-ksm66-schilddruese/",
      "title": "Die bestuntersuchte Pflanze, vor der niemand warnt",
      "lead": "Ashwagandha senkt Cortisol, verbessert Schlaf und stimuliert die Schilddrüse. Für die ersten beiden Wirkungen gibt es Etiketten. Für die dritte gibt es Fallberichte in der Notaufnahme.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ruhe"
      ]
    },
    {
      "href": "magnolia-phellodendron-relora/",
      "title": "Zwei Baumrinden, ein Patent",
      "lead": "Honokiol aus Magnolienrinde bindet an GABA-A-Rezeptoren wie ein Benzodiazepin, ohne Abhängigkeit auszulösen. Das wäre eine Nachricht. Stattdessen steht es auf einer Diätpille.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ruhe"
      ]
    },
    {
      "href": "gaba-glycin-magnesium-glycinat/",
      "title": "Drei Wege zur Bremse, einer davon funktioniert nicht",
      "lead": "GABA ist der wichtigste hemmende Neurotransmitter im Gehirn. Als Supplement geschluckt erreicht er es wahrscheinlich nicht. Die Supplement-Industrie verkauft ihn trotzdem.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ruhe",
        "substanz"
      ]
    },
    {
      "href": "bacopa-monnieri-langsame-wirkung/",
      "title": "Die Pflanze, die erst nach zwölf Wochen wirkt",
      "lead": "Jede positive Humanstudie zu Bacopa monnieri misst den Effekt nach zwölf Wochen. Vorher passiert nichts. Die Nootropic-Community will Ergebnisse nach einer Stunde. Das erklärt, warum die meisten aufgeben, bevor die Substanz anfängt zu wirken.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "klarheit"
      ]
    },
    {
      "href": "cholin-alpha-gpc-citicolin/",
      "title": "Die Substanz, die auf dem Etikett fehlt",
      "lead": "2003 hat eine Studie an 261 Alzheimer-Patienten gezeigt, dass Alpha-GPC die Kognition signifikant verbessert. Seitdem ist nichts passiert. Die Substanz lässt sich nicht patentieren.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "klarheit"
      ]
    },
    {
      "href": "sulforaphan-nrf2-entgiftung/",
      "title": "Der Schalter, den Brokkoli umlegt",
      "lead": "Sulforaphan aktiviert Nrf2, den Transkriptionsfaktor, der über zweihundert Schutzgene gleichzeitig hochfährt. Die beste Quelle wächst in drei Tagen auf der Fensterbank.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "nad-nmn-sirtuine-langlebigkeit/",
      "title": "Das Molekül, an dem die Biohacker sterben wollen",
      "lead": "NAD+ sinkt mit dem Alter. NMN hebt es an. Ob das den Menschen länger leben lässt, weiß niemand. Der Markt verkauft die Antwort trotzdem, für fünfzig Euro im Monat.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "dmso-loesungsmittel-heilmittel/",
      "title": "Das Lösungsmittel, das durch die Haut geht",
      "lead": "DMSO durchdringt die Haut in Sekunden und nimmt mit, was darauf liegt. Stanley Jacob entdeckte das 1963, als er es verschüttete und Knoblauch schmeckte. Sechzig Jahre später hat die FDA eine einzige Indikation genehmigt. Zwölfhundert Publikationen sagen, es hätten mehr sein müssen.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "kokoswasser-elektrolyte-hydration/",
      "title": "Das Getränk, das Gatorade überflüssig macht",
      "lead": "Kokoswasser enthält mehr Kalium als eine Banane, mehr Magnesium als die meisten Mineralwässer und null Farbstoffe. Die Sportgetränke-Industrie hat siebzig Jahre gebraucht, um synthetisch zu kopieren, was in einer Kokosnuss schon drin war.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "chlorophyll-was-gruen-kann/",
      "title": "Pflanzenblut",
      "lead": "Chlorophyll und Hämoglobin teilen sich ein Molekülgerüst. Der Unterschied liegt im Zentralatom. Was daraus folgt, ist Pharmakologie. Was TikTok daraus macht, ist Dekoration.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "ingwer-gingerol-pharmakologie/",
      "title": "Die Wurzel, die die EMA ernst nimmt",
      "lead": "Die Europäische Arzneimittelagentur stuft Ingwer als »well-established use« gegen Reiseübelkeit ein. Fast kein anderer Pflanzenextrakt erreicht diese Klassifikation. Das Regal behandelt ihn trotzdem wie ein Gewürz.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "olivenoel-oleocanthal-entzuendung/",
      "title": "Das Öl, das im Hals brennt, wenn es gut ist",
      "lead": "Frisches Olivenöl enthält einen COX-Hemmer mit der Potenz von Ibuprofen. Man erkennt ihn am Kratzen im Hals. Wenn das Öl nicht kratzt, fehlt der Wirkstoff.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "brennnessel-urtica-prostata/",
      "title": "Das Unkraut mit der Arzneimittelzulassung",
      "lead": "Brennnessel hat sechs randomisierte Studien an über tausend Prostatapatienten. In Deutschland steht sie in der Pharmakopöe. Im Garten reißen die meisten sie raus.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "kokosoel-mct-laurinsaeure/",
      "title": "Das Fett, das die Ernährungswissenschaft nicht einordnen kann",
      "lead": "Kokosöl besteht zur Hälfte aus Laurinsäure, einem Antimikrobikum, das die Lipidhülle von Viren zerstört. Die American Heart Association behandelt es trotzdem wie Butter. Das sagt mehr über die AHA als über Kokosöl.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    },
    {
      "href": "szechuanpfeffer-sanshool-vibration/",
      "title": "Das Gewürz, das die Lippen auf 50 Hertz vibrieren lässt",
      "lead": "Szechuanpfeffer enthält Hydroxy-alpha-Sanshool, eine Substanz, die Mechanorezeptoren der Haut aktiviert und ein messbares Vibrieren bei 50 Hertz erzeugt. Das Kribbeln im Mund ist physikalisch real.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "substanz"
      ]
    }
  ]
};
