// Auto-generated by pipeline/render.mjs. Quelle: zutaten/bildgebung/articles.js.
window.BILDGEBUNG_DATA = {
  "items": [
    {
      "href": "hopfen-jenseits-vom-bier/",
      "title": "Hopfen jenseits vom Bier",
      "lead": "Die am besten erforschte Nervenpflanze Europas wird als Schlaftee verkauft. Was die Forschung weiß und das Regal verschweigt.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 3,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "igelstachelbart-nerven-wachsen/",
      "title": "Der Pilz, der Nerven wachsen lässt",
      "lead": "Die einzige bekannte Nahrungsquelle, die Nervenwachstumsfaktor im Gehirn stimuliert, steht im Asia-Markt neben den Shiitake.",
      "date": "2026-06-21",
      "created": "2026-06-21",
      "minutes": 3,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "spilanthol-trigeminale-aktivierung/",
      "title": "Das Molekül, das die Zunge vibrieren lässt",
      "lead": "Spilanthol aktiviert Berührungsfasern im Gesicht mit einer messbaren Frequenz von fünfzig Hertz. Die Empfindung gehört weder zum Geschmack noch zum Schmerz. Sie gehört zum Tastsinn.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 3,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "adaptogene-ueberblick/",
      "title": "Der nützlichste Begriff, der nichts bedeutet",
      "lead": "Ein sowjetischer Toxikologe hat 1947 ein Wort erfunden, das heute auf jeder zweiten Supplement-Packung steht. Die Pflanzen dahinter sind interessant. Das Wort ist das Problem.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ueberschaetzt"
      ]
    },
    {
      "href": "ashwagandha-ksm66-schilddruese/",
      "title": "Die bestuntersuchte Pflanze, vor der niemand warnt",
      "lead": "Ashwagandha senkt Cortisol, verbessert Schlaf und stimuliert die Schilddrüse. Für die ersten beiden Wirkungen gibt es Etiketten. Für die dritte gibt es Fallberichte in der Notaufnahme.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "magnolia-phellodendron-relora/",
      "title": "Zwei Baumrinden, ein Patent",
      "lead": "Honokiol aus Magnolienrinde bindet an GABA-A-Rezeptoren wie ein Benzodiazepin, ohne Abhängigkeit auszulösen. Das wäre eine Nachricht. Stattdessen steht es auf einer Diätpille.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "gaba-glycin-magnesium-glycinat/",
      "title": "Drei Wege zur Bremse, einer davon funktioniert nicht",
      "lead": "GABA ist der wichtigste hemmende Neurotransmitter im Gehirn. Als Supplement geschluckt erreicht er es wahrscheinlich nicht. Die Supplement-Industrie verkauft ihn trotzdem.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "ueberschaetzt"
      ]
    },
    {
      "href": "bacopa-monnieri-langsame-wirkung/",
      "title": "Die Pflanze, die erst nach zwölf Wochen wirkt",
      "lead": "Jede positive Humanstudie zu Bacopa monnieri misst den Effekt nach zwölf Wochen. Vorher passiert nichts. Die Nootropic-Community will Ergebnisse nach einer Stunde. Das erklärt, warum die meisten aufgeben, bevor die Substanz anfängt zu wirken.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "cholin-alpha-gpc-citicolin/",
      "title": "Die Substanz, die auf dem Etikett fehlt",
      "lead": "2003 hat eine Studie an 261 Alzheimer-Patienten gezeigt, dass Alpha-GPC die Kognition signifikant verbessert. Seitdem ist nichts passiert. Die Substanz lässt sich nicht patentieren.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "sulforaphan-nrf2-entgiftung/",
      "title": "Der Schalter, den Brokkoli umlegt",
      "lead": "Sulforaphan aktiviert Nrf2, den Transkriptionsfaktor, der über zweihundert Schutzgene gleichzeitig hochfährt. Die beste Quelle wächst in drei Tagen auf der Fensterbank.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "nad-nmn-sirtuine-langlebigkeit/",
      "title": "Das Molekül, an dem die Biohacker sterben wollen",
      "lead": "NAD+ ist der zentrale Redox-Cofaktor in jeder menschlichen Zelle. Sein Spiegel sinkt mit dem Alter um bis zu sechzig Prozent. Die Tierdaten zur Supplementierung sind spektakulär. Die Humandaten kommen gerade erst.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "dmso-loesungsmittel-heilmittel/",
      "title": "Das Lösungsmittel, das durch die Haut geht",
      "lead": "DMSO durchdringt die Haut in Sekunden und nimmt mit, was darauf liegt. Stanley Jacob entdeckte das 1963, als er es verschüttete und Knoblauch schmeckte. Sechzig Jahre später hat die FDA eine einzige Indikation genehmigt. Zwölfhundert Publikationen sagen, es hätten mehr sein müssen.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "kokoswasser-elektrolyte-hydration/",
      "title": "Das Getränk, das Gatorade überflüssig macht",
      "lead": "Kokoswasser enthält mehr Kalium als eine Banane, mehr Magnesium als die meisten Mineralwässer und null Farbstoffe. Die Sportgetränke-Industrie hat siebzig Jahre gebraucht, um synthetisch zu kopieren, was in einer Kokosnuss schon drin war.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "chlorophyll-was-gruen-kann/",
      "title": "Pflanzenblut",
      "lead": "Chlorophyll und Hämoglobin teilen sich ein Molekülgerüst. Der Unterschied liegt im Zentralatom. Was daraus folgt, ist Pharmakologie. Was TikTok daraus macht, ist Dekoration.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "ingwer-gingerol-pharmakologie/",
      "title": "Die Wurzel, die die EMA ernst nimmt",
      "lead": "Die Europäische Arzneimittelagentur stuft Ingwer als »well-established use« gegen Reiseübelkeit ein. Fast kein anderer Pflanzenextrakt erreicht diese Klassifikation. Das Regal behandelt ihn trotzdem wie ein Gewürz.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "olivenoel-oleocanthal-entzuendung/",
      "title": "Das Öl, das im Hals brennt, wenn es gut ist",
      "lead": "Frisches Olivenöl enthält einen COX-Hemmer mit der Potenz von Ibuprofen. Man erkennt ihn am Kratzen im Hals. Wenn das Öl nicht kratzt, fehlt der Wirkstoff.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "brennnessel-urtica-prostata/",
      "title": "Das Unkraut mit der Arzneimittelzulassung",
      "lead": "Brennnessel hat sechs randomisierte Studien an über tausend Prostatapatienten. In Deutschland steht sie in der Pharmakopöe. Im Garten reißen die meisten sie raus.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "kokosoel-mct-laurinsaeure/",
      "title": "Das Fett, das die Ernährungswissenschaft nicht einordnen kann",
      "lead": "Kokosöl besteht zur Hälfte aus Laurinsäure, einem Antimikrobikum, das die Lipidhülle von Viren zerstört. Die American Heart Association behandelt es trotzdem wie Butter. Das sagt mehr über die AHA als über Kokosöl.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "szechuanpfeffer-sanshool-vibration/",
      "title": "Das Gewürz, das die Lippen auf 50 Hertz vibrieren lässt",
      "lead": "Szechuanpfeffer enthält Hydroxy-alpha-Sanshool, eine Substanz, die Mechanorezeptoren der Haut aktiviert und ein messbares Vibrieren bei 50 Hertz erzeugt. Das Kribbeln im Mund ist physikalisch real.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 2,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "kalium-elektrolyt-blutdruck/",
      "title": "Das Defizit, das kein Blutbild zeigt",
      "lead": "Die WHO empfiehlt 3510 Milligramm Kalium am Tag. Westliche Bevölkerungen nehmen im Schnitt 2500 auf. Die Differenz verursacht Bluthochdruck, Schlaganfälle und Knochenverlust. Kein Arzt misst sie.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "wacholder-juniperus-terpinen/",
      "title": "Die Beere mit vier Karrieren",
      "lead": "Wacholder steht in der Europäischen Pharmakopöe und auf der Zutatenliste von Gin. Die Beere enthält über achtzig Monoterpene, ein kaliumsparendes Diuretikum und ein Breitband-Antimikrobikum. Das Regal verkauft sie als Gewürz.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "petersilie-apigenin-nad/",
      "title": "Das teuerste Kraut liegt neben dem Steak",
      "lead": "Petersilie enthält pro hundert Gramm mehr Vitamin C als Orangen, mehr Vitamin K als jedes Gemüse im Supermarkt und Apigenin, einen CD38-Hemmer, der den NAD+-Abbau bremst. Die Gastronomie schiebt sie an den Tellerrand.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "biophotonen-ultraschwache-photonenemission/",
      "title": "Das Licht, das beide Seiten ruiniert haben",
      "lead": "Jede lebende Zelle emittiert messbare Photonen. Die Physik ist reproduziert, die Messung steht. Die Esoterik hat das Phänomen vereinnahmt, die Wissenschaft hat aufgehört hinzusehen. Beide haben versagt.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "zitronenverbene-verbascoside-sport/",
      "title": "Das Antioxidans, das die Anpassung nicht sabotiert",
      "lead": "Hochdosiertes Vitamin C nach dem Sport kann die Trainingsanpassung blockieren. Zitronenverbene schützt die Muskeln, ohne die Adaptation zu stören. Das macht sie pharmakologisch einzigartig unter den Antioxidantien.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "probiotika-staemme-evidenz/",
      "title": "Zwanzig Milliarden Keime, null Belege",
      "lead": "Die Supplement-Industrie verkauft Probiotika nach Milliarden und Stämmen. Mehr klingt nach besser. Die Evidenz sagt: weniger, aber geprüft. Nur einzelne Stämme haben Belege. Der Rest ist Arithmetik für Ahnungslose.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "ueberschaetzt"
      ]
    },
    {
      "href": "akkermansia-muciniphila-darmbarriere/",
      "title": "Der Keim, der tot besser wirkt als lebendig",
      "lead": "Akkermansia muciniphila frisst die Schleimhaut des Darms und repariert sie dabei. Pasteurisiert wirkt besser als lebend. Beides widerspricht allem, was die Probiotika-Industrie über Darmbakterien erzählt.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "praebiotika-ballaststoffe-butyrat/",
      "title": "Das Futter, das wichtiger ist als der Keim",
      "lead": "Die Supplement-Industrie verkauft Probiotika für dreißig Euro im Monat. Was die gekauften Keime am Leben hält, sind Ballaststoffe, die in Haferflocken, kalten Kartoffeln und Chicorée stecken. Niemand wirbt dafür, weil sich Hafer schlecht patentieren lässt.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "ala-nac-glutathion-recycling/",
      "title": "Das Antioxidans, das alle anderen recycelt",
      "lead": "Alpha-Liponsäure ist das einzige Antioxidans, das sowohl in Wasser als auch in Fett arbeitet. Es regeneriert verbrauchtes Glutathion, Vitamin C und Vitamin E zurück in ihre aktive Form. Die Supplement-Industrie verkauft lieber die Einzelteile.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "chlorella-spirulina-detox-kontamination/",
      "title": "Die Algen, die entgiften sollen und selbst vergiftet sind",
      "lead": "Chlorella und Spirulina werden als Detox-Superfoods verkauft. Kontrollierte Humanstudien zur Schwermetall-Ausleitung existieren praktisch nicht. Dafür existieren Laboranalysen, in denen die Algen selbst mit Blei, Cadmium und Arsen kontaminiert sind.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "ueberschaetzt"
      ]
    },
    {
      "href": "glutamin-zink-carnosin-schleimhaut/",
      "title": "Zwei Substanzen für eine Wand, die niemand sieht",
      "lead": "L-Glutamin ist der Hauptenergieträger der Darmschleimhaut. Zink-Carnosin ist in Japan als Magenmedikament zugelassen. Im Westen wird das eine für den Bizeps verkauft und das andere kennt niemand.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "saeure-basen-basenpulver-ph/",
      "title": "Die Krankheit, die das Marketing erfunden hat",
      "lead": "Chronische Übersäuerung durch moderne Ernährung klingt plausibel. Der Blut-pH ist durch drei Puffersysteme so eng reguliert, dass kein Lebensmittel ihn verschieben kann. Basenpulver behandeln eine Krankheit, die außerhalb pathologischer Stoffwechselzustände nicht existiert.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "ueberschaetzt"
      ]
    },
    {
      "href": "spermidin-autophagie-longevity/",
      "title": "Der Nobelpreis-Mechanismus ohne Interventionsdaten",
      "lead": "Spermidin stößt Autophagie an, den zellulären Selbstreinigungsprozess, für dessen Aufklärung Ohsumi 2016 den Nobelpreis bekam. Tiermodelle zeigen Lebensverlängerung. Epidemiologie zeigt Korrelation. Was fehlt, sind große Interventionsstudien am Menschen. Die Supplement-Industrie wartet nicht.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 1,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "resveratrol-pterostilben-bioverfuegbarkeit/",
      "title": "Das Molekül, das siebzig Prozent absorbiert und unter einem Prozent ankommt",
      "lead": "Resveratrol ist das meistverkaufte Anti-Aging-Polyphenol der Welt. Der menschliche Körper zerlegt es in Minuten. Sein methylierter Verwandter Pterostilben erreicht die Zielorgane vierfach besser. Verkauft wird trotzdem Resveratrol, weil es die bessere Geschichte hat.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 4,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "senolytika-fisetin-quercetin-zombiezellen/",
      "title": "Die Jagd auf Zombiezellen läuft — ohne Humandaten",
      "lead": "Zombiezellen sind kein Marketingbegriff. Sie existieren, sie akkumulieren, und sie vergiften alles, was sie umgibt. Die Frage ist, ob man sie loswerden kann. In Mäusen ja. Am Menschen weiß es niemand.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 4,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "curcumin-pains-bioverfuegbarkeit/",
      "title": "Das Molekül, das in jedem Test gewinnt und in keinem Körper ankommt",
      "lead": "Curcumin ist die meistuntersuchte Pflanzensubstanz der Welt. Über hundertzwanzig klinische Studien, Zehntausende In-vitro-Papers, ein eigenes Journal. 2017 veröffentlicht das Journal of Medicinal Chemistry eine Analyse, die das Fundament wegzieht. Das Molekül ist ein systematischer Falschspieler. Oder ein verkanntes Genie. Oder beides.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 4,
      "filters": [
        "unklar"
      ]
    },
    {
      "href": "mitochondrien-coq10-pqq-alcar/",
      "title": "Die Kraftwerke sterben leise",
      "lead": "Mitochondrien produzieren das ATP, von dem jede Zelle lebt. Ihre Kapazität sinkt mit dem Alter um zehn bis fünfzehn Prozent pro Dekade. Drei Substanzen greifen an verschiedenen Stellen ein. Die Supplement-Industrie verkauft sie einzeln und erklärt den Zusammenhang nie.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 4,
      "filters": [
        "unterschaetzt"
      ]
    },
    {
      "href": "vitamin-d-k2-magnesium-triade/",
      "title": "Drei Defizite, eine Triade, null Leitlinien",
      "lead": "Achtzig Prozent der Mitteleuropäer haben im Winter suboptimale Vitamin-D-Spiegel. Die Hälfte der Erwachsenen liegt unter der empfohlenen Magnesiumzufuhr. K2 misst niemand. Die drei Substanzen bilden ein System. Einzeln supplementiert können sie schaden.",
      "date": "2026-06-22",
      "created": "2026-06-22",
      "minutes": 4,
      "filters": [
        "unterschaetzt"
      ]
    }
  ]
};
